### ISSUE TITLE
I can't access this profile but I get as "Could interest you"

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1005]
<img width="1524" alt="Bildschirmfoto 2024-09-02 um 13 41 17" src="https://github.com/user-attachments/assets/695f0711-96d1-4439-b367-cd976541318b">

Is this a bug or should we solve this differently? This doesn't make sense.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer   , let me have a look

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , the PR I have fixed assumes this user has `registration_completed_at` as nil , could you confirm that with


```
alias Animina.Accounts.User
user = User.by_username!("sabrina")
user.registration_completed_at
```

**Comment by wintermeyer** [comment]
> I have fixed assumes this user has registration_completed_at as nil 

Yes, that is correct. It is `nil`.
