### ISSUE TITLE
First message help only returns one message and the copy button is missing

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1015]
<img width="1201" alt="Bildschirmfoto 2024-09-03 um 13 25 37" src="https://github.com/user-attachments/assets/9c7775ed-9cb0-419e-8c9a-f8ca21e467c4">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , the copy button for the first message occurs after the second message starts generating for context btw . With this information , is this still a problem?

**Comment by wintermeyer** [comment]
I never saw a second message.

**Comment by Kimutai01** [comment]
@wintermeyer 
It must be an issue with the prompt, to ensure that it always gives 3 messages
