### ISSUE TITLE
New spark config

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1017]
Zach Daniel's code igniter uses the following Spark configuration. I think it would be a good idea to use the same one to make it easier for new developers. This wouldn't change a single bit of programming logic but would change the order in a lot of files with one commit. So I don't want to do this while a lot of people are working at the code simultaneous.

For anybody who doesn't know what this does: Spark uses this config to sort and format code when `mix format` is called.

```elixir
config :spark,
  formatter: [
    remove_parens?: true,
    "Ash.Resource": [
      section_order: [
        :postgres,
        :resource,
        :code_interface,
        :actions,
        :policies,
        :pub_sub,
        :preparations,
        :changes,
        :validations,
        :multitenancy,
        :attributes,
        :relationships,
        :calculations,
        :aggregates,
        :identities
      ]
    ],
    "Ash.Domain": [section_order: [:resources, :policies, :authorization, :domain, :execution]]
  ]
```

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 , @briankariuki , @Kimutai01 What would be a good date for this? What weekday is the least busy one for you?

**Comment by MICHAELMUNAVU83** [comment]
For me , Wednesday is best

**Comment by Kimutai01** [comment]
Wednesday would also be okay for me.

**Comment by wintermeyer** [comment]
hmmmm... so today wouldn't be a bad choice.

**Comment by wintermeyer** [comment]
Done. I hope that it didn't interfere too much with existing work.
