### ISSUE TITLE
Country required error when running mix task seed_demo_system

### ISSUE THREAD

**Issue by briankariuki** [wintermeyer/animina#1029]
Running mix seed_demo_system produces the following error:

```
** (Ash.Error.Invalid) Invalid Error

* attribute country is required
  (elixir 1.17.0) lib/process.ex:864: Process.info/2
  (ash 3.3.3) lib/ash/error/changes/required.ex:5: Ash.Error.Changes.Required.exception/1
  (ash 3.3.3) lib/ash/changeset/changeset.ex:3007: Ash.Changeset.add_required_attribute_error/2
  (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 3.3.3) lib/ash/changeset/changeset.ex:1706: Ash.Changeset.do_for_action/4
  (animina 0.2.0) deps/ash/lib/ash/code_interface.ex:694: Animina.Accounts.User.create!/2
  (animina 0.2.0) lib/mix/tasks/seed_demo_system.ex:378: Mix.Tasks.SeedDemoSystem.create_demo_user/1
  (elixir 1.17.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
  (animina 0.2.0) lib/mix/tasks/seed_demo_system.ex:26: Mix.Tasks.SeedDemoSystem.run/1
  (mix 1.17.0) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.17.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2

```

Thrown because creating a user now requires the country be passed in.

**Comment by wintermeyer** [comment]
This is a tricky one. I had the same problem in https://github.com/animina-dating/animina/commit/9c0965d6f19625bb98f78fab0a95aa2aadf0628b

- Please do ask the Ash gods in https://elixirforum.com what would be the best solution for the given problem since it is never a good idea to change migrations which are in the past.
- Follow along my way of solving it in the meantime. Adding something like this to the old migration and to the new one.

```elxir
    # First, add the new column if it doesn't exist
    unless column_exists?(:traits_flags, :photo_flagable) do
      alter table(:traits_flags) do
        add :photo_flagable, :boolean, default: false
      end
    end

    # Flush changes to ensure the column exists before inserting data
    flush()
```

**Comment by briankariuki** [comment]
> This is a tricky one. I had the same problem in [9c0965d](https://github.com/animina-dating/animina/commit/9c0965d6f19625bb98f78fab0a95aa2aadf0628b)
> 
> * Please do ask the Ash gods in https://elixirforum.com what would be the best solution for the given problem since it is never a good idea to change migrations which are in the past.
> * Follow along my way of solving it in the meantime. Adding something like this to the old migration and to the new one.
> 
> ```
>     # First, add the new column if it doesn't exist
>     unless column_exists?(:traits_flags, :photo_flagable) do
>       alter table(:traits_flags) do
>         add :photo_flagable, :boolean, default: false
>       end
>     end
> 
>     # Flush changes to ensure the column exists before inserting data
>     flush()
> ```

@wintermeyer is this comment related to this issue? All I had to do was add `country: "Germany"` to User.create() in the mix task to fix the problem

**Comment by wintermeyer** [comment]
> is this comment related to this issue?

Forget what I added to this issue. I thought it was a different problem.
