### ISSUE TITLE
Remove Incognito Option

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1044]
<img width="1198" alt="Bildschirmfoto 2024-09-13 um 08 33 56" src="https://github.com/user-attachments/assets/01e605e8-5ce3-449b-9062-157543d846ee">

I don't know how this made it to production. Please remove the `incognito` option here. A normal user can not make him-/herself invisible.

PS: Do we have policies to check for this? We should. Otherwise one can do it via an API call.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I believe other apps have this in place . If I want to go incognito , I can , I visit people's accounts  anonymously , mostly for guys who do not want co workers etc from knowing they are on dating apps .

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 I totally understand why other platforms offer this feature. But that is not a reason why we should too. Other platforms generate money with this feature. We don't. I am ok with users to hibernate their account. But I don't see the benefit for incognito for our concept. Please remove the option in the GUI.
