### ISSUE TITLE
Creating/Updating a story takes for ever

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1048]
Please have a look into this problem. It takes forever to create or update a story. At one time at the end we even get an error message. This is all on production.

![ScreenFlow](https://github.com/user-attachments/assets/0460c290-55d0-49c4-aa0b-b96a32710f35)

Please find out the problem and fix it.

**Comment by MICHAELMUNAVU83** [comment]
This is most probably caused by the photo tagging bit by AI , is it possible to spawn that function @Kimutai01

**Comment by Kimutai01** [comment]
@MICHAELMUNAVU83 
We can spawn the function. I also realized it was timing out at times on localhost but I thought it was because I was running the model locally,
but I'm looking into it

**Comment by wintermeyer** [comment]
We do not need the tags right away but we need the story to be saved as soon as possible. So any kind of queuing mechanism would work fine too. Something that is robust enough to survive a) a new deployment and b) a reboot of the server.

**Comment by wintermeyer** [comment]
>  I also realized it was timing out at times on localhost but I thought it was because I was running the model locally

ALWAYS test this on production after deployment too. It must not be the case that I am the only one who catches these kind of problems/bugs.

**Comment by Kimutai01** [comment]
I

> > I also realized it was timing out at times on localhost but I thought it was because I was running the model locally
> 
> ALWAYS test this on production after deployment too. It must not be the case that I am the only one who catches these kind of problems/bugs.

It's okay I'll always test it both on production and locally.
I'm working on it ASAP

**Comment by briankariuki** [comment]
@Kimutai01 @MICHAELMUNAVU83 I also think there's some refactoring opportunity here. after_action hooks in my opinion should not have any expensive functions attached. The `create_optimized_photos/1` and `create_photo_flags/1` may take time to execute

```elixir

change after_action(fn changeset, record, _ ->
   create_optimized_photos(record)
   create_photo_flags(record)
   #  spawn(fn -> create_photo_flags(record) end)

   {:ok, record}
 end),
 on: [:create]

```

**Comment by MICHAELMUNAVU83** [comment]
Which is the best way to handle such an operation?

**Comment by briankariuki** [comment]
> Which is the best way to handle such an operation?

Use some task runner like oban, or a genserver/genstage setup.

**Comment by wintermeyer** [comment]
> Use some task runner like oban, or a genserver/genstage setup.

We tried Oban in the past but that didn't fit our requirements. We need some sort of pipeline which we can fill and use all free resources to work through that pile of work.

It might be a stone edge way of solving this but I do think extra attributes to e.g. Story or Photo would do the trick. We add timestamps for specific thing (e.g. photo_flagged_at) and as long as their are nil it means that task hasn't been done. We run some sort of background job which always looks out for these unfinished tasks and does them one by one. After finishing it we set the attribute to the current time. Than we even now how long it took to do the job.

**Comment by wintermeyer** [comment]
>   create_optimized_photos(record)
>   create_photo_flags(record)

My gut feeling says: 
- We can resize and optimised photos on the fly (at the time the resource gets saved) since this doesn't take much CPU time.
- We can never do the AI stuff right at the time we create the resource. That always has to be queued (at least with our current CPU power).
