### ISSUE TITLE
Edit Potential Partner Preferences: Maximale Größe

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1062]
Der Wert "egal" bei der maximalen Körpergröße führt dazu, dass mehrere Werte dieses Formulars auf Standard zurückgesetzt werden. "egal" wird nicht angenommen.

**Comment by wintermeyer** [comment]
Ich kann das Problem auf macOS mit Safari (alles aktuelle Software) nicht reproduzieren:

![ScreenFlow](https://github.com/user-attachments/assets/c6eeec6a-c27c-4b4f-a76c-abb47ed80c95)

Deshalb schliesse ich das Issue.

@marqqs Gerne wieder das Issue öffnen und einen Screenshot oder ein Video hinzufügen. Bitte mit Betriebssystem und Browserart. DANKE!
