### ISSUE TITLE
About-Me-Story lässt sich nicht löschen.

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1063]
Für die About-Me-Story kann man zwar auf den Lösch-Button klicken – es erscheint sogar eine Sicherheitsrückfrage – aber sie wird dadurch nicht gelöscht.

**Comment by wintermeyer** [comment]
Danke für die Fehlermeldung! Ich habe dazu das Issue #1064 angelegt, weil wir intern alles auf Englisch behandeln.

Erklärung: Wir wollen auf jeden Fall immer eine "About me" Story für jeden User haben. Ohne ist ein User Eintrag in der Datenbank nicht gültig. Deshalb kann man die nicht löschen. Aber es ist natürlich Blödsinn, dann den Button für das löschen überhaupt zur Verfügung zu stellen. Wird gefixt.
