### ISSUE TITLE
"About me" story should have a delete functionality

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1064]
In #1063 a user says that it is possible to click on the "delete" button for a "About me" story but that this doesn't work. Obviously because we don't allow to delete the "About me" story.

Please remove the button for this case. We shouldn't offer a delete if we know that we will not allow it.

**Comment by marqqs** [comment]
> Please remove the button for this case. We shouldn't offer a delete if we know that we will not allow it.

If you do not allow to delete the "about me" story, please add a function to replace the photo in it.

Perhaps it would be easier to allow the deletion of the "about me" story and reset the profile to an inactive state in this case – same state it was when the user created it and hadn't written this story yet.

**Comment by wintermeyer** [comment]
> if you do not allow to delete the "about me" story, please add a function to replace the photo in it.

@MICHAELMUNAVU83 Please double check if this is possible or not. If it isn't: Create an issue and fix it.

> Perhaps it would be easier to allow the deletion of the "about me" story and reset the profile to an inactive state

Not a bad idea but I fear that many non technical users have a hard time to understand the consequences of this state and how to return to the normal state. I prefer not to do that.
