### ISSUE TITLE
Replace confirmation link with PIN

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1066]
I received a bug report from a non techie user who wasn't able to create a new account because she wasn't able to click on the link.

<img width="737" alt="Bildschirmfoto 2024-09-24 um 13 50 24" src="https://github.com/user-attachments/assets/01e9bd65-25fe-47d2-8e49-5086458ac7bd">

I can think of a thousand reasons why this could be a problem. Maybe the email client doesn't display URLs as links and not everybody knows how to cut and paste on a mobile devise.

**It is our job to make it as easy as possible for the user!** So in this case easy seems to be a random PIN code which we send via email to the user. Please rewrite the process. We don't send a confirmation link but a random 6 digit PIN code by email. We present a form which can be used to enter that PIN. The user has 3 attempts to enter the PIN correctly. After that we give the feedback "We couldn't match this PIN to your account. We deleted your data. Please do create a new account." Obviously we delete the data of that user.

BTW: The email has to be translatable to other languages.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , as a temporary fix for current registrations , can we have such a button , of course better designed , instead of the link

![Screenshot 2024-09-24 at 15 21 19](https://github.com/user-attachments/assets/0002b76a-bad8-4e6a-8b24-b728627a31be)

**Comment by wintermeyer** [comment]
No need to spend time on something we will through away in a week or so.
