### ISSUE TITLE
Cannot change photo in "about me" story

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1067]
Since the "about me" story cannot be deleted, one cannot delete nor update the photo in this story.
Perhaps adding an "update photo" function should be considered.

**Comment by wintermeyer** [comment]
We have to make sure that one can update the photo of a story.

**Comment by wintermeyer** [comment]
@marqqs Thanks for the bug report.

**Comment by wklaebe** [comment]
Just wanted to report the same...

**Comment by wintermeyer** [comment]
@wklaebe Thanks for your bug report! @MICHAELMUNAVU83 is working on it.
