### ISSUE TITLE
"Potential Partner Preferences" switch to default when setting Maximum height to "doesn't matter"

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1068]
[screenvideo_animinia_01.webm](https://github.com/user-attachments/assets/c488686b-1c24-499b-9f17-3baa1552aa90)

Browser: Chromium Version 129.0.6668.58 snap (64-Bit)

**Comment by wintermeyer** [comment]
@marqqs Thank you for this bug report!

@MICHAELMUNAVU83 @Kimutai01 Please have a look into this.

**Comment by MICHAELMUNAVU83** [comment]
This was closed here https://github.com/animina-dating/animina/pull/1069
