### ISSUE TITLE
Story photo is shown cropped, not as seen when uploaded

### ISSUE THREAD

**Issue by wklaebe** [wintermeyer/animina#1082]
I uploaded a 1364x1684 photo that contains my head in the upper quarter. It is completely shown in the "Edit Story" view. In the "Show Profile" view, that photo is cropped from top and bottom to about a 4:3 landscape format, removing my face from the nose upwards.
This is made worse by #1067.

**Comment by wintermeyer** [comment]
#1067 will be fixed asap. Sorry for the inconvenience.

I am not sure about #1082. I see your point but I also know why we did it differently. I will close the issue for now and will think about it.

**Comment by wklaebe** [comment]
Fixing #1067 would let me work around this, thanks :)
