### ISSUE TITLE
Some profiles can't be seen

### ISSUE THREAD

**Issue by Kimutai01** [wintermeyer/animina#1114]
For some reason, some profiles can't be seen.
I tried @wintermeyer profile and I got this
<img width="1440" alt="Screenshot 2024-11-04 at 09 28 12" src="https://github.com/user-attachments/assets/729b2154-9663-4c96-8c55-98c154f4eecd">

I also can't view it in my account
<img width="1440" alt="Screenshot 2024-11-04 at 08 44 05" src="https://github.com/user-attachments/assets/7f0f0b28-2759-4738-b455-de1ae55e5b86">

**Comment by wintermeyer** [comment]
@Kimutai01 Good catch!

@MICHAELMUNAVU83 Do you have an idea what this is? My account should be public.

**Comment by MICHAELMUNAVU83** [comment]
Let me have a look and advise

**Comment by MICHAELMUNAVU83** [comment]
Hey @wintermeyer  , I am not able to replicate this locally as I can acces profiles on my side , is it possible for you to share the log errors from prod?

**Comment by wintermeyer** [comment]
> Hey @wintermeyer , I am not able to replicate this locally as I can acces profiles on my side , is it possible for you to share the log errors from prod?

Please send me an email with your SSH pub key and the Linux username you prefer.

**Comment by briankariuki** [comment]
This needs more investigating as its not a /v2/profile route.

**Comment by wintermeyer** [comment]
@briankariuki Send me an email in case you need access to the logs.

**Comment by MICHAELMUNAVU83** [comment]
Here is the error from logs
```
Request: GET /wintermeyer
                                                         ** (exit) an exception was raised:
                                                             ** (RuntimeError) found duplicate ID "story_33efaf76-90cb-4edc-aecf-6f3471ad86cc" for component AniminaWeb.StoryComponent when rendering templa
````

Let me see how to fix this

**Comment by MICHAELMUNAVU83** [comment]
@briankariuki  , @wintermeyer  sent me the list of his stories and they have unique ids , what might the issue be?

**Comment by briankariuki** [comment]
Paste logs please

**Comment by MICHAELMUNAVU83** [comment]
Logs 
```
Request: GET /wintermeyer
                                                         ** (exit) an exception was raised:
                                                             ** (RuntimeError) found duplicate ID "story_33efaf76-90cb-4edc-aecf-6f3471ad86cc" for component AniminaWeb.StoryComponent when rendering template
```


And these are his storiesm in DB

![unnamed](https://github.com/user-attachments/assets/257d233b-e44a-4458-81b3-0ee4d16d0364)

**Comment by wintermeyer** [comment]
Just to be sure I searched the database. There is no other story with that id:

<img width="864" alt="Bildschirmfoto 2024-11-08 um 09 31 58" src="https://github.com/user-attachments/assets/9ffc7309-72f9-409b-8522-1bbefa0a913e">

**Comment by briankariuki** [comment]
I've figured out this issue.

**Comment by briankariuki** [comment]
This is caused by stories which have updated photos. See video below. 

For some reason when a story is edited and photo updated, the original photo is not removed from the database. 

This has also been reported by marqqs here https://github.com/animina-dating/animina/issues/1093#issuecomment-2464720070.

![Screen Recording 2024-11-08 at 16 47 52](https://github.com/user-attachments/assets/07ada0ad-15fe-4cab-bae0-5911761d3acc)


And in database the old photo exists which has the same story id. The FastStory sql query left join's with the photos table, and if two photos have the same story id, it duplicates the story in the query result.

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/52ab0fbc-ec09-4368-b43b-5dfa912fb052">

**Comment by wintermeyer** [comment]
@briankariuki Good catch! Can we fix this with a migration which removes the buggy entries and deletes old photo files of needed?
