### ISSUE TITLE
Orphaned pictures are still in the database.

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1134]
Thanks for fixing this.
However, orphaned pictures are still available via deep link.
The delete function might work correctly, but pictures which have been uploaded in the past are still in the database.

_Originally posted by @marqqs in https://github.com/animina-dating/animina/issues/1093#issuecomment-2464720070_

**Comment by briankariuki** [comment]
See https://github.com/animina-dating/animina/issues/1114#issuecomment-2464826340

**Comment by briankariuki** [comment]
I think the main issue is with this validation, here https://github.com/animina-dating/animina/blob/f0388109439921f3b94b0132c8d3d445dba53175/lib/animina/accounts/resources/photo.ex#L216

Not sure why photos resource has a validation for a story, maybe @MICHAELMUNAVU83 and @Kimutai01 you can look into it and see if the validation works as you expected.

**Comment by wintermeyer** [comment]
@marqqs Can you do me a favour and re-check this? I don't know which deep link you are using otherwise I would have checked it myself.

**Comment by marqqs** [comment]
> @marqqs Can you do me a favour and re-check this?
Unfortunately, it's still there, at least at this moment.

However, I am not sure which pictures are currently activated in the test profile since I cannot access it anymore: https://github.com/animina-dating/animina/issues/1135
(profile access throws "Internal Server Error")

**Comment by briankariuki** [comment]
@marqqs I've created an account in the past hour and I did not encounter this issue.

**Comment by wintermeyer** [comment]
> @marqqs Can you do me a favour and re-check this? I don't know which deep link you are using otherwise I would have checked it myself.

Please use the same deep link in an other browser to check if this is a caching issue. If it isn’t please post the deep link here so that we can figure out the problem.

**Comment by marqqs** [comment]
I just checked via Firefox – a browser which I never used for this – on a separate computer. Still there.
May I send you a PM?

**Comment by wintermeyer** [comment]
> I just checked via Firefox – a browser which I never used for this – on a separate computer. Still there. May I send you a PM?

sw@wintermeyer-consulting.de

**Comment by MICHAELMUNAVU83** [comment]
I can see when we change the profile picture we do delete from the database

```
[debug] QUERY OK source="photos" db=2.4ms
DELETE FROM "photos" AS p0 WHERE (p0."id" = $1) ["cd673059-3fa1-4c74-9a20-b1c13e050174"]

```

**Comment by MICHAELMUNAVU83** [comment]
Similar to when we change the image of a story , @briankariuki  what case did the migrations you added account for?

```
[debug] QUERY OK source="photos" db=2.0ms
DELETE FROM "photos" AS p0 WHERE (p0."id" = $1) ["38afb215-1ca5-4887-bea6-d6acb60db913"]
```

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , There was a validation you had asked for a while back to ensure the about me story photo is never deleted , I guess I will have to remove this , kindly confirm if i should?

**Comment by briankariuki** [comment]
> Similar to when we change the image of a story , @briankariuki what case did the migrations you added account for?
> 
> ```
> [debug] QUERY OK source="photos" db=2.0ms
> DELETE FROM "photos" AS p0 WHERE (p0."id" = $1) ["38afb215-1ca5-4887-bea6-d6acb60db913"]
> ```

The migration removes any photos entries with a non-null story_id. It first groups the photos by story_id, picks the most recent photo for a given story and then deletes the rest of the photos which are the orphaned photos left when a user updates the photo in a story.

IMHO the validation in photos needs to be looked at again. Its not working as expected when a story photo is destroyed

**Comment by wintermeyer** [comment]
> @wintermeyer , There was a validation you had asked for a while back to ensure the about me story photo is never deleted , I guess I will have to remove this , kindly confirm if i should?

Ahhhh! So the problem is that the user can not delete the photo because it belongs to the about me story and we don't allow the about me story to be deleted?

So once we fixed #1135 the user (@marqqs) can log in and exchange the photo to that story without a problem?

**Comment by briankariuki** [comment]
> > @wintermeyer , There was a validation you had asked for a while back to ensure the about me story photo is never deleted , I guess I will have to remove this , kindly confirm if i should?
> 
> Ahhhh! So the problem is that the user can not delete the photo because it belongs to the about me story and we don't allow the about me story to be deleted?
> 
> So once we fixed #1135 the user (@marqqs) can log in and exchange the photo to that story without a problem?

This is the reason why the photos remain in the database and filesystem

**Comment by MICHAELMUNAVU83** [comment]
My latest PR will allow us to delete an about me story @wintermeyer  , check in a few

**Comment by wintermeyer** [comment]
> My latest PR will allow us to delete an about me story @wintermeyer , check in a few

Please have a look at #1139

**Comment by MICHAELMUNAVU83** [comment]
Okay , I will have to put that PR on hold as we discuss then
