### ISSUE TITLE
"Internal Server Error" when trying to login

### ISSUE THREAD

**Issue by marqqs** [wintermeyer/animina#1135]
After logging in there is a redirect to https://animina.de/my/dashboard
It opens an empty page with just these words: "Internal Server Error".

Since this is for several days now I hope this error can be found in the log files...

**Comment by briankariuki** [comment]
https://github.com/animina-dating/animina/issues/1134#issuecomment-2468444864

**Comment by wintermeyer** [comment]
<img width="797" alt="Bildschirmfoto 2024-11-12 um 08 04 40" src="https://github.com/user-attachments/assets/c969a3b9-7788-42ad-a5d9-07eea45b8ec6">

😱

**Comment by MICHAELMUNAVU83** [comment]
I believe this issue is also closed @wintermeyer  , kindly confirm

**Comment by wintermeyer** [comment]
@marqqs Could you do me a favour and check if it works for you? It does for me.

**Comment by marqqs** [comment]
It works fine! Thanks for fixing this! :-)

**Comment by wintermeyer** [comment]
> It works fine! Thanks for fixing this! :-)

Thank YOU for reporting the bug!
