### ISSUE TITLE
Change the handling of deleting the last story

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1139]
#1134 displayed a potential problem with the current logic.

I wanted to be sure that nor orphaned profiles without a single story are in the system but this leads to this problem. The only solution which I can come up with is that we allow users to delete even their about_you story (which is THE one story that should always be there) but auto change their visibility to hibernate (is that the name we use?) but only after we told the user that this is the consequence of remove the about_you story.

GUI wise we have to display it to a user when he/she is in hibernation. On every screen. In their face! And we have to make it easy to get back to normal mode again.

Please propose a better solution in this issue if you have an idea.

**Comment by MICHAELMUNAVU83** [comment]
- [ ] Create a banner to be shown to the user all through the system if they are hibernated
- [ ] Ensure if a user hibernates themselevs in the profile visibility page , they can go back to normal if and only if they meet requirements eg profile photo and about me story
- [ ] Ensure a user can delete a profile photo for their profile  , we show them a modal informing them of consequences then they can delete , we need to now make the user hibernated.
