### ISSUE TITLE
Images are not Visible If they Are approved

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#1143]
Images are not visible that are approved , this is because we have a checker that is looking for the state :appoved but ash returns it as "approved" , thus , we do not see the image

![Screenshot 2024-11-13 at 06 02 33](https://github.com/user-attachments/assets/0aa825d7-f212-4bfb-a2dc-8824c31b2a13)

**Comment by wintermeyer** [comment]
An additional arrow or two go a long way in describing a bug.

<img width="559" alt="Bildschirmfoto 2024-11-13 um 08 57 00" src="https://github.com/user-attachments/assets/75a74f26-0490-4478-8831-0c8971ff45b2">
