### ISSUE TITLE
FlagsLive form content should load from the database

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#118]
# Idea

The following pages should be filled with the according flags of the `current_user`. When they are called the first time no flags are saved in the database and therefore none are selected. But later they should display the current state for `current_user` (flags which are saved in the database for that user).

- live "/registration/white-flags", FlagsLive, :white
- live "/registration/green-flags", FlagsLive, :green
- live "/registration/red-flags", FlagsLive, :red

# Thoughts

- By doing that a user can use the back button in the browser to fix a mistake he/she made. 
- We can recycle the same pages to change the flags anytime in the future and not just in the registration process.

**Comment by philipp-kempgen** [comment]
I would probably not make it a 5-or-more-step sign-up. After the sign-up, show a reminder like "You can enhance your profile by adding hashtags.". Not sure though.

**Comment by wintermeyer** [comment]
> I would probably not make it a 5-or-more-step sign-up.

I hear you but I’d like to test this first. It is a thin line.
