### ISSUE TITLE
Add story interface

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#127]
# Idea

Since animina is a dating app the user should be able to tell stories about him/herself. @wintermeyer created a basic `Animina.Narratives.Story` resource but that has to be upgraded with an image. Stories are displayed as some sort of card (e.g. https://v1.tailwindcss.com/components/cards). They are sorted by the `position` attribute.

# Story

- A story belongs_to `Animina.Narratives.Headline` but that can be `nil` too (no headline for that story than). 
- A story `content` which is written in Markdown and has to be rendered to become HTML. I was thinking about using https://github.com/am-kantox/md but that is not set in stone. `content` can be `nil` too.
- A story has one image (can be nil too than no image is displayed). Ideally we can recycle the `photo` resource or create a new resource which than gets

## The first story

The first story is a special case. We use the already uploaded image of the user as an image for that and set the `headline` to `About me`.

## Validations 

- `content` can be nil and can not be longer than 1024 characters
- The image should not be bigger than 10 MB and the x/y ratio should be one of the following: 1:1, 3:4, 4:3, 16:9, 9:16, 4:3 and 3:4 (please tell me if I forgot a popular ratio here). Please divide the higher through the lower number (e.g. 4:3). The result should be between 1 and 2. Those are valid. All others are invalid (for now).
- A user can't have more than 10 stories. 
- `position` of a `story` has to be unique per `user`. It can't be nil.
- The `story` with the `position` 1 has to have the headline with the subject `About me`.

## Image StateMaschine

Please implement something similar to the `Animina.Accounts.Photo` resource. Display a placeholder image (e.g. from https://placeholderimage.dev) until an image is approved. The owner of the image can always see that image. All others only until the image is approved.

## Registration Workflow

After the white, red and green flag LiveView there has to be some sort of entry system for these stories. That LiveView should be used also for editing those stories later.

@briankariuki Please do not hesitate to ask questions about this. I am not 100% sure if I covered everything that is needed in this issue.

**Comment by philipp-kempgen** [comment]
>     * A story `content` which is written in Markdown

or AsciiDoc, alternatively?

>     * The image should not be bigger than 10 MB and the x/y ratio should be one of the following: 1:1, 3:4, 4:3, 16:9, 9:16, 4:3 and 3:4 (please tell me if I forgot a popular ratio here).

The most popular ratio on "real" photo cameras is 3:2 (resp. 2:3 in portrait orientation).

**Comment by wintermeyer** [comment]
Let’s add 3x2 and 2x3

Good catch @philipp-kempgen !

**Comment by wintermeyer** [comment]
> or AsciiDoc, alternatively?

IMO markdown is better for non tech users.

**Comment by philipp-kempgen** [comment]
- Granted, "real" photo cameras are kind of a niche market these days compared to smartphones.
- My phone can take photos in 9:16 (portrait orientation).
- The resolution isn't guaranteed to be exactly the expected ratio for every image sensor. Examples:
  - Sony A7 IV: 7040 × 4688 => isn't exactly 3:2
  - Canon R5: 8192 × 5464 => isn't exactly 3:2
- 16:9 is never exactly 16:9.
- For a validation, you would have to add some factor of uncertainty.
- Actually, why do you want to restrict the ratios? The user may have cropped the image to an unusual format. I would simply validate that the x/y ratio isn't too extreme. It should probably be between 3/1 and 1/3.
- Maybe even something like 4/1 could be allowed. Panoramas.

**Comment by wintermeyer** [comment]
> Actually, why do you want to restrict the ratios? 

I don't want to have a crazy ratio uploaded. Something like 1:9 or so. That is purely a design and layout thing. That is the reason I want to have some sort of validation here for the ratio. But I think I have an "easy" solution for the problem. We divide the higher number through the lower number and that result should be between 1 and 2. That should be a good enough validation for the problem.

**Comment by philipp-kempgen** [comment]
That's just what I suggested, I'd say, except I was being a bit more generous with the ratio. :-)

**Comment by briankariuki** [comment]
@wintermeyer There's a `position` attribute on the `Headline` resource. Is this position the same as the one in `Story` ?

**Comment by wintermeyer** [comment]
> @wintermeyer There's a `position` attribute on the `Headline` resource. Is this position the same as the one in `Story` ?

Yes and no. The `position` in the `Headline` resource is meant as a sorting order to display the headlines in a pull down menu. The `position` in the `Story` resource is meant as a sorting order of the stories within a profile.

**Comment by briankariuki** [comment]
Thanks for the clarification

> > @wintermeyer There's a `position` attribute on the `Headline` resource. Is this position the same as the one in `Story` ?
> 
> Yes and no. The `position` in the `Headline` resource is meant as a sorting order to display the headlines in a pull down menu. The `position` in the `Story` resource is meant as a sorting order of the stories within a profile.

Thanks for the clarification
