### ISSUE TITLE
Visualisation of Height

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#138]
The height of a potential partner is a very important information for most users. I want to visualise this on the profile page to "see" it right away. Have a look at https://max-interactive.com/projects/people/ by @xamiam to get an idea of the concept. The current_user and the profile person stand next to each other in front of a visible 2,00 m and 1,50 m mark. The basic idea:

<img width="151" alt="Bildschirmfoto 2024-03-06 um 14 48 42" src="https://github.com/animina-dating/animina/assets/69770/96b4c47b-ebc7-4ce8-8b47-3355089c946c">

It should be placed above the fold on a mobile phone. But it can be small. 

I will send @briankariuki additional files which GitHub doesn't allow me to attach to this issue.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , good news , I have been able to do this bit as you see in the first image and second image , we will be passing  px to represent centimeters , so for 200 cm we pass 200px and it shows .
I am now wondering where in the system to add it , which page  , is it the one in the third image.


![Screenshot 2024-04-02 at 14 14 24](https://github.com/animina-dating/animina/assets/86654131/03dc773c-854a-4b03-ba74-daefee7df2f7)


![Screenshot 2024-04-02 at 14 31 08](https://github.com/animina-dating/animina/assets/86654131/9b69758e-bb34-4656-8a0b-7fc39f9f1c37)


![Screenshot 2024-04-02 at 14 16 34](https://github.com/animina-dating/animina/assets/86654131/3f1d12fe-18eb-4d0f-bc47-ec84ea239e5f)

**Comment by xamiam** [comment]
Please be aware that the limbs should all be sized separately in CSS to keep the sizes correct.

**Comment by MICHAELMUNAVU83** [comment]
Hey @xamiam  , for this I have used svgs then I adjust the height would they work , specifically https://www.svgrepo.com/svg/83016/woman-standing-silhouette-black-shape and https://www.svgrepo.com/svg/103742/man-silhouette

**Comment by xamiam** [comment]
Maybe a bit more like this? https://max-interactive.com/projects/people/

**Comment by xamiam** [comment]
Let me know if you need help understanding the code...

**Comment by MICHAELMUNAVU83** [comment]
This is nice @xamiam  , in this case each element has been styled with CSS?

**Comment by wintermeyer** [comment]
Two things:

- Please add lines for 100 cm and 50 cm. I think that looks nicer. But I am not sure.
- @xamiam is right BUT done is better than perfect. I would prefer @xamiam version but right now anything is better than nothing. We can fix this later. @MICHAELMUNAVU83: Fire at will.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer thanks  , on which page should people see the comparison then?

**Comment by xamiam** [comment]
> This is nice @xamiam , in this case each element has been styled with CSS?

yes, correct. It tries to make the proportions more anatomically correct - though we are talking about stick figures ;)
I agree with @wintermeyer: We can fix this later. Maybe just take the SVGs I used in the demo so the look doesn't change too much later.

**Comment by wintermeyer** [comment]
This should be seen on the profile page.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I have an interesting scenario here , if the current user selects "male" as the gender , we would show the male stick figure vs "their preferred gender" , so if it is a man , we show a male figure , female a female figure and if diverse  , both male and female figures .
The problem is when the user selects a diverse gender for themselves , how should we display this?

**Comment by wintermeyer** [comment]
> The problem is when the user selects a diverse gender for themselves , how should we display this?

Good point! We don't show the height display at all if there is diverse involved and kick the can down the road. Done is better than perfect.
