### ISSUE TITLE
Validate that there is always an "About me" story

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#147]
Problem: I want to make sure that we always have a "About me" story for every profile. All the other headlines can change and can be deleted. But the "About me" one should be a stable part of the profile page.

**Comment by briankariuki** [comment]
@wintermeyer Maybe you could shed more light on this. At what point should this validation take place?

**Comment by wintermeyer** [comment]
> @wintermeyer Maybe you could shed more light on this. At what point should this validation take place?

Sometime in the future I want to open an API to the system. That is one of the reasons we use Ash. So I want all this to happen in the resource. When a 3rd party system uses the API I want to be sure that it can not create a first new story which is not an "About me" story. And I want to be sure that no one can delete an "About me" story if it is not the only story.

Is it clear what I mean?
