### ISSUE TITLE
Adding A landing page to tell the users what the site is about

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#151]
- When I run the system , I am taken to the sign up page automatically , could we have a one page landing page to tell the users what the site is about ? Something as simple as 

![WhatsApp Image 2024-03-22 at 5 49 09 PM](https://github.com/animina-dating/animina/assets/86654131/9db01df7-b7e8-4fbe-b551-902a07e06be5)

**Comment by wintermeyer** [comment]
This is our landing page:

<img width="476" alt="Bildschirmfoto 2024-03-22 um 16 59 04" src="https://github.com/animina-dating/animina/assets/69770/0ab818ef-b9fd-41f9-b2c5-16a80ab84d53">

We can add or other content into this box. But THAT'S IT. I want a minimal amount of clicks registration process. Users are either curious and than they'll dive right into it or they are not.
