### ISSUE TITLE
Improve Desktop Version of the Flag selection (white, green and red).

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#155]
Please improve the desktop view for this page and add a dark mode version.

I think the usability of that page can be increased a lot.

@MICHAELMUNAVU83 Feel free to surprise me.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , I remember you  mentioned that you'd want the button to save flags to not be at the bottom as people may not be able to scroll , would it work if we have a button at the top left of the pages , something like .

We can have the button fixed at the bottom too and top such that no one has to scroll to ssave the flags .
![Screenshot 2024-04-01 at 10 48 30](https://github.com/animina-dating/animina/assets/86654131/6938fc89-397b-4b13-9478-5827f3020ae0)
![Screenshot 2024-04-01 at 10 48 12](https://github.com/animina-dating/animina/assets/86654131/2cb63a1c-f3f6-4bef-bed5-d5a63fe6003a)

**Comment by wintermeyer** [comment]
> We can have the button fixed at the bottom too and top such that no one has to scroll to ssave the flags . !

I like the idea of having one button at the top and one at the bottom.
