### ISSUE TITLE
Notificationbox doesn't look nice on the desktop

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#159]
Should be wider.

<img width="702" alt="Bildschirmfoto 2024-03-27 um 08 18 33" src="https://github.com/animina-dating/animina/assets/69770/e9cea526-5230-4b6c-95e6-53f98d72b46e">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should I go with the design emma has  on the figma?

![Screenshot 2024-04-08 at 09 25 38](https://github.com/animina-dating/animina/assets/86654131/05f0fdd8-9f5c-4fa0-b3c6-5d9bf34b0833)

**Comment by wintermeyer** [comment]
>  should I go with the design emma has on the figma?

No, because that design doesn't cover all the needs we have for this box. Just make it wider. That's good enough for now.
