### ISSUE TITLE
Query for potential partner

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#174]
Obviously this is a key feature of the system. It will take a bit of time to fine tune it. Please create a new module/function for this.

Let's solve this step by step:

- [x] #186
- [x] #188
- [x] #190
- [x] #199

Feel free to split this into several issues.

**Comment by briankariuki** [comment]
@wintermeyer I've started working on this feature. So far I have this for the first task.

```
def get_random_users(limit \\ 10) do
    User
    |> Ash.Query.for_read(:random_users)
    |> Ash.Query.limit(limit)
    |> Accounts.read!()
 end
```

Should I go ahead and modify this same function to allow filtering by gender, height e.t.c, or create another function(s) for that?

**Comment by wintermeyer** [comment]
I am not happy with the function name. Why would we ever want to get random users? Why not something like:

```elixir
def potential_partners(user, limit \\ 10) do
...
```

**Comment by wintermeyer** [comment]
> Should I go ahead and modify this same function to allow filtering by gender, height e.t.c, or create another function(s) for that?

I am not sure right now what the best way is here. We want to call `potential_partners/2` in the code base and be sure that this functions takes care of all the filtering. How those filters are split up in that module: I don't care right now. I guess we are going to refactor that module in the future anyway. Just get started.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I see all the tasks have been marked as complete , should this task be open?
