### ISSUE TITLE
Add photo to a dummy account

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#177]
`Mix.Tasks.CreateDummyAccounts` creates dummy accounts for easier development.

Right now a photo is missing. There is `random_photo_url/1` which gives a URL from a portrait but I don't know how to use that to create the avatar photo.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , just to be clear, you are talking about this ?
![Screenshot 2024-04-01 at 21 08 02](https://github.com/animina-dating/animina/assets/86654131/20dbec6a-46f4-48d8-bad1-a3739683891b)

**Comment by wintermeyer** [comment]
> Hello @wintermeyer , just to be clear, you are talking about this ?

hmmmm... no. I made a mistake here.

Better create a first "About me" story with that photo.

**Comment by wintermeyer** [comment]
hmmm... what I really meant was the photo which gets uploaded at http://localhost:4000/profile/profile-photo

That and the first "About me" story can use the same photo.

**Comment by briankariuki** [comment]
I'll check this. But my thought would be to download the photos or something when running mix task, and then create the story

**Comment by wintermeyer** [comment]
@briankariuki Please don't forget to set the "in progress" label to this issue if you are working on it.
