### ISSUE TITLE
Add Dark Mode toggle

### ISSUE THREAD

**Issue by briankariuki** [wintermeyer/animina#182]
It would be nice to have a button to switch between dark and light mode. Its a pain to work on pages that are not yet optimized for dark mode. @MICHAELMUNAVU83 what do you think? 

<img width="1449" alt="image" src="https://github.com/animina-dating/animina/assets/34672053/cb19887b-fab2-4a8d-8649-48ea7ec07711">

**Comment by MICHAELMUNAVU83** [comment]
I believe it would be nice , @wintermeyer  , should I add this , I will have to write some javascript though

**Comment by briankariuki** [comment]
> I believe it would be nice , @wintermeyer , should I add this , I will have to write some javascript though

Take a look https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection

**Comment by wintermeyer** [comment]
I don't want a dark mode toggle. At least not now. We use the mode which is asked for by the browser. That is good for the majority of scenarios.
