### ISSUE TITLE
Beautify User Profile

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#185]
See https://www.figma.com/file/nXBUkSKufGRE0NO7yMNOCn/FIVER-DATING?type=design&node-id=1-7046&mode=design&t=PA8eqfTlSDhneqBa-0#-1

<img width="432" alt="Bildschirmfoto 2024-04-03 um 16 13 40" src="https://github.com/animina-dating/animina/assets/69770/c9d3a7ee-f4cb-463d-b4fc-1b696fa3d79d">

**Comment by wintermeyer** [comment]
<img width="295" alt="Bildschirmfoto 2024-04-03 um 19 55 09" src="https://github.com/animina-dating/animina/assets/69770/e44f6c46-5607-4fcf-a810-e634fc6b36f1">

I really would like to have this or at least most of it above the fold on a mobile devise. I have no idea how to do this. I guess downscaling the image a bit would be key.

**Comment by MICHAELMUNAVU83** [comment]
This will be my task tomorrow , I will have a look but we can probably have the image on top then the text follow .
