### ISSUE TITLE
Add the GEO distance to the query.

### ISSUE THREAD

**Issue by briankariuki** [wintermeyer/animina#190]

**Comment by philipp-kempgen** [comment]
Regarding pull request #198:

Seeing GEO-related queries without an index on the database table always makes me nervous.
Wouldn't it make sense to let the database calculate distance?
I think there should be a spatial index on the coordinates.

- https://www.postgresql.org/docs/current/earthdistance.html
- https://postgis.net/

**Comment by philipp-kempgen** [comment]
Also keep in mind that a postal code in Germany can have some 35 km in diameter. So I guess the search radius needs to be set accordingly, because otherwise 2 people who live maybe 1 km apart but on opposite sides of a postal code "border" may not find each other.

**Comment by philipp-kempgen** [comment]
Also I think that GEO-coding functions (user-provided location name to coordinates) should be created in a way that they can later be replaced by some API such as OpenStreetmap Geocoding API:

- https://nominatim.org/
- https://wiki.openstreetmap.org/wiki/Nominatim

**Comment by briankariuki** [comment]
> Regarding pull request #198:
> 
> Seeing GEO-related queries without an index on the database table always makes me nervous. Wouldn't it make sense to let the database calculate distance? I think there should be a spatial index on the coordinates.
> 
> * https://www.postgresql.org/docs/current/earthdistance.html
> * https://postgis.net/

I looked into both of these methods. 

earthdistance assumes the globe is a perfect sphere, which may give inaccurate results.

Postgis is the go to for geo stuff, but requires additional setup to install it. And in our case we only need one function to calculate the distance from one location to the other. And the postgis result is not that off from the haversine formula. the database carries out this calculation

**Comment by briankariuki** [comment]
> Also keep in mind that a postal code in Germany can have some 35 km in diameter. So I guess the search radius needs to be set accordingly, because otherwise 2 people who live maybe 1 km apart but on opposite sides of a postal code "border" may not find each other.

This is not an issue in my implementation. We are only considering the lat and lon columns to get cities closer to the user's city. I assume if two towns are 1km apart, their coordinates should not be that far off and this is well taken care of by the haversine formular. After getting the cities, then we extract, their zip_codes and use that list to filter.

**Comment by briankariuki** [comment]
> Regarding pull request #198:
> 
> Seeing GEO-related queries without an index on the database table always makes me nervous. Wouldn't it make sense to let the database calculate distance? I think there should be a spatial index on the coordinates.
> 
> * https://www.postgresql.org/docs/current/earthdistance.html
> * https://postgis.net/

I will create a new PR that adds indices on the lat, lon columns

**Comment by philipp-kempgen** [comment]
@briankariuki I didn't mean to imply there's anything wrong with your implementation. That's why I assigned the issue to @wintermeyer so he can decide if he wants anything changed or added. Maybe it's not even required. I didn't investigate.

**Comment by wintermeyer** [comment]
> Seeing GEO-related queries without an index on the database table always makes me nervous.

I already forgot the code which you are discussing here. In case just an index is missing: Please open an issue with that information (which attribute needs to be indexed) and assign it to me.

**Comment by wintermeyer** [comment]
@all Right now I don't care I this is the best implementation or not. It is one implementation which makes sense today. We can kick this can down the road. 

We can tackle this problem later and improve everything. But we don't have to do it right now. 

Done is better than perfect!

**Comment by briankariuki** [comment]
> @briankariuki I didn't mean to imply there's anything wrong with your implementation. That's why I assigned the issue to @wintermeyer so he can decide if he wants anything changed or added. Maybe it's not even required. I didn't investigate.

Thanks.
