### ISSUE TITLE
Height diagram doesn't work

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#191]
This is what I see:

<img width="283" alt="Bildschirmfoto 2024-04-04 um 18 20 39" src="https://github.com/animina-dating/animina/assets/69770/2d6b946b-a998-4a05-a196-7207ad46aad3">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  ,it works on my side , let me have a look at what the issue could be
