### ISSUE TITLE
Colour white flags in current_user's green and red

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#195]
When a user visits a profile page of an other user he/she should see those white flags which are his/her green or red flag coloured in that colour. So that it becomes immediately obvious how good a fit that profile is.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , just to get it right , we show flags that are only and only similar to the 2 users or should we just color the ones similar with a different color?

**Comment by wintermeyer** [comment]
No, we show all white flags. But we colour code those which are red or green for the current_user. 

Our aim is to help the current_user to SEE right away if this is a good fit or not.

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Please git pull. I changed quite a bit. Sorry for the additional work!

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , the new version has no tooltip for a flag , should I leave it as such?

**Comment by wintermeyer** [comment]
Yes, no tooltip. I liked your idea but it took too much real estate.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , would this communicate with the user well enough , if a white flag is green for the current user, they see a green circle and if it is a red one ,  a red one as such 

![Screenshot 2024-04-09 at 06 11 52](https://github.com/animina-dating/animina/assets/86654131/584893bc-9f99-423b-86ff-05e8cebe5be1)

**Comment by wintermeyer** [comment]
> would this communicate with the user well enough

Let's go with that for now. I don't have a better idea.
