### ISSUE TITLE
Add the green and red flags to the query.

### ISSUE THREAD

**Issue by briankariuki** [wintermeyer/animina#199]

**Comment by wintermeyer** [comment]
I am sure about the green flags. 

But when possible we should go lightly on the red flags. And I have no idea how to do that. Maybe it is a good idea to have two results:

- Strict red flags where any red flag becomes a death sentence.
- We don't care about the red flags at all but display them in the profile. I think we should start with this.

**Comment by briankariuki** [comment]
@wintermeyer I've done a PR for this. Please take a look. For now I'm matching on a current user's green flags with the potential partner's white flags. Perhaps we could also match with the potential partner's green flags, and this would match two people with the same set of green flags.

**Comment by wintermeyer** [comment]
>  Perhaps we could also match with the potential partner's green flags, and this would match two people with the same set of green flags.

IMO we should match the potential partner green flags with the white flags of the current_user.
