### ISSUE TITLE
Change profile layout

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#206]
<img width="924" alt="Bildschirmfoto 2024-04-05 um 18 38 23" src="https://github.com/animina-dating/animina/assets/69770/ef4da605-9b48-4f93-94f7-ae58c7294916">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , I have made the change according to the image but it does not look right , advise if I have made the layout as you wanted 
![Screenshot 2024-04-07 at 09 50 39](https://github.com/animina-dating/animina/assets/86654131/983e87e7-4c32-4f2d-860b-a7d69669efeb)

**Comment by wintermeyer** [comment]
Please put the hight thing in the middle column too. The story content is the only thing in the right column.

**Comment by MICHAELMUNAVU83** [comment]
Okay , @wintermeyer  , I have a  question , on the mobile view , what should be on top , the height thing or the bio , I currently have it as such 
![Screenshot 2024-04-07 at 10 24 51](https://github.com/animina-dating/animina/assets/86654131/79e3ae6f-8d5e-4c65-a12b-b83e877b62fb)
![Screenshot 2024-04-07 at 10 32 46](https://github.com/animina-dating/animina/assets/86654131/31b22abc-7f31-42cd-aeba-2401d2773131)

**Comment by wintermeyer** [comment]
>  I currently have it as such

Let's roll with that right now. It is a moving target. I don't know the best way of presenting the info yet.
