### ISSUE TITLE
Different way to display the heights

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#207]
I am not 100% happy with the way we compare the height of the profile and the current_user. The proportions are hard to get right and without that it always looks slightly off. So I'd like to try an alternative idea:

<img width="236" alt="Bildschirmfoto 2024-04-05 um 18 46 52" src="https://github.com/animina-dating/animina/assets/69770/54d05578-e203-4432-91d3-4f62924ebf96">

Draw the people as two columns (forget the bulges it should be a rectangle) and put the username of each person in that column. The font has to run 90 degrees turned.

I have a hard time to describe what I mean. In case it is not clear ping me again and I do a drawing.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I get the concept , I will send a PR and you check if it is as you have described.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , how do you think we should handle really really long usernames , I have this so far . Also is this how the layout should be , with the username to the right.
![Screenshot 2024-04-06 at 08 48 23](https://github.com/animina-dating/animina/assets/86654131/597c468c-29f7-42d9-bc32-bc713eb73c7a)

**Comment by wintermeyer** [comment]
Trim too long usernames.
