### ISSUE TITLE
Just one block per person - Height comparison

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#209]
I just want one block per person. That block should represent the height of that person and in that block his/her name should be written. If the name is too long, trim it to the first couple of letters.

If possible: Rotate the font by 180 degrees. The first letter should start at the bottom. But only if possible.

<img width="247" alt="Bildschirmfoto 2024-04-06 um 10 27 32" src="https://github.com/animina-dating/animina/assets/69770/963bd3b2-fb03-4d3f-9bb2-e8334f858483">

**Comment by wintermeyer** [comment]
BTW: With this new way of displaying the height we can remove the special case for diverse profiles. We can always show it.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I now understand , the name should be inside the block not outiside.

**Comment by wintermeyer** [comment]
> @wintermeyer , I now understand , the name should be inside the block not outiside.

Yes! But this is a moving target. I am not sure what the best way to display this is either. We have to play around with it a bit.

**Comment by wintermeyer** [comment]
Second idea: Maybe we can put a little circle avatar of the current_user and the profile user at the bottom of each column.

@MICHAELMUNAVU83 Please play with that idea and fire at will. If it looks good we go with it. But maybe it is too crowded.

**Comment by wintermeyer** [comment]
@xamiam I liked the original idea of having human like figures. But at the end the proportions were a problem and somehow it didn't feel natural. I think going totally abstract is a better way. I don't want the current_user to think too much about this. It should be a feature and not a distraction.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I think the circle avatar is really genius , let me see how this looks
