### ISSUE TITLE
Reorganise the display of white flags on the profile page

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#212]
Right now the flags are displayed this way on the profile page:

<img width="390" alt="Bildschirmfoto 2024-04-06 um 11 06 45" src="https://github.com/animina-dating/animina/assets/69770/8029b750-3b43-40e9-8367-38607bbe446f">

It doesn't look nice and it takes a big amount of real estate. 

Let's try this:
Don't display the categories but list all the flags in the order of their priority. But add a some sort of tool tip with that category information to that flag. And all without adding JavaScript. In case this is not possible without JavaScrip: Just display the flag and not category information at all. We can kick that can down the road a bit.

PS: Please replace "My white flags" with "Flags".

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Please make sure to git pull the current main before committing anything. I changed quite a bit today. Your work for this issue shouldn't be a problem. But auto merging might come to its limits without human interaction.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer okay , could you also clarify what you meant by tool tip in the description

**Comment by wintermeyer** [comment]
Tooltip example: https://flowbite.com/docs/components/tooltips/

But I want something without JavaScript. Maybe that is impossible. Then I want nothing at all. The idea was to give the information about the category in some sort of hidden second layer.

**Comment by MICHAELMUNAVU83** [comment]
Thanks for the link , it has given me an idea of how to impliment it.
