### ISSUE TITLE
Profile problem

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#217]
#216 introduced a bug:

<img width="925" alt="Bildschirmfoto 2024-04-07 um 10 28 58" src="https://github.com/animina-dating/animina/assets/69770/413ae776-c42f-4faf-8c65-fa8fd9ff6ca0">

The second column should be top aligned.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , I have been looking at different screens trying to simulate the error, on which screen size is this , I have this  layout for mobile , tablet and desktop


![Screenshot 2024-04-07 at 15 14 18](https://github.com/animina-dating/animina/assets/86654131/ecf8e428-17dd-45ba-af9c-4b079138cc97)
![Screenshot 2024-04-07 at 15 14 31](https://github.com/animina-dating/animina/assets/86654131/d26cb077-3ae7-4703-8ae6-788440099cb5)
![Screenshot 2024-04-07 at 15 14 55](https://github.com/animina-dating/animina/assets/86654131/d4d873c6-a0ee-48ad-ad07-6da72ef3f527)

**Comment by wintermeyer** [comment]
> trying to simulate the error

You need to have a longer content in the "About me" story to simulate the problem.

**Comment by wintermeyer** [comment]
BTW: The headline should be "About me" and not "Description/Bio".
