### ISSUE TITLE
No one can delete an "About me" story if it is not the only story.

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#233]
- This is an addition to #147  , Ensure you cannot delete the 'About me' story if is the only one  remaining.

**Comment by wintermeyer** [comment]
I wouldn't mind to have a test for this kind of feature. Just to be sure that it always works.

**Comment by MICHAELMUNAVU83** [comment]
Okay , I will add unit tests for this feature
