### ISSUE TITLE
Add points to the profile the current_user is reading

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#234]
# Idea
A good/interesting profile should benefit from being good. I am thinking about given `credits` for the time those profiles are opened by other users.

I am not sure about the exact amounts and about the timing. So please code it in a way that we can change those values easily.

# How exactly

Every 5 seconds I open the profile of @example_user the system adds a 1 point `credit` to that user. In case that user is logged in he/she should see in the menu bar that he/she got more points. The point amount should be updated.

## Thoughts

```elixir
  def mount(_params, _session, socket) do
    if connected?(socket) do 
      :timer.send_interval(5000, self(), :tick) 
    end

    {:ok, socket}
  end

  def handle_info(:tick, socket) do 
    # Add credit to the database

    {:noreply, socket}
  end
```

PS. We should create a system wide timer/mechanism which gets triggered every second or every two seconds and which publishes updates of credits to logged in users. Otherwise we could run into a problem if one profile is very popular and a lot of users open it at the same time. => #235

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we add the points every 5 seconds or after the first 5 seconds only?

**Comment by wintermeyer** [comment]
Every 5 seconds
