### ISSUE TITLE
Create a pub/sub channel of every logged in user and trigger updates every 2 seconds

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#235]
When a user logs into the system he/she should subscribe to his/her own channel. We use this channel for updates.

Add a system wide timer which gets triggered every 2 seconds. It should select the credits which got inserted into the database in the last 2 seconds and update the credit/point information for those users who are logged in. Probably wise to add the currently logged in users to that select query.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , hello , I wanted to run my idea for this feature . I will have a Genserver that runs every 2 seconds as https://hexdocs.pm/elixir/1.12/GenServer.html#module-receiving-regular-messages , on the scheduled job we do the publishing , how do you find this implimentation?

**Comment by wintermeyer** [comment]
> Genserver that runs every 2 seconds

Go for it.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , I have made progress on this , But I am stuck at the end where I have to display the credits on the sidebar. 

https://github.com/animina-dating/animina/assets/86654131/e2a9366c-e95a-4b63-8c11-a37013ff3787


The sidebar is in a layout at `lib/animina_web/components/layouts/app.html.heex` and I am not sure how I can pass the updated credits here.

I have a handle info currently in the profile_index live that does the credit updating

```
def handle_info({:added, credits}, socket) do
    credit =
      case Enum.find(credits, fn credit -> credit["user_id"] == socket.assigns.user.id end) do
        nil -> socket.assigns.user.credit_points
        credit -> credit["points"]
      end
     {:noreply,
     socket
     |> assign(credit: credit)}
  end
```


How would you advise I proceed to ensure we display the users updated credit on the sidebar.

**Comment by wintermeyer** [comment]
> The sidebar is in a layout at `lib/animina_web/components/layouts/app.html.heex` and I am not sure how I can pass the updated credits here.

I don't know this either. ;-)

Please ask this question in https://elixirforum.com because this is a generic problem we have to solve for multiple pages and information. Feel free to link to the GitHub repo in your question. But maybe it is better to come up with a generic example for that question.

**Comment by wintermeyer** [comment]
Pleas add a link to your question in this issue.

**Comment by MICHAELMUNAVU83** [comment]
Okay, I will , waiting for the verification from their end.
Currently this is what I have done , we have different mount callbacks where we can add things to the socket , so I have added the current users default credit_points in the socket.
On each liveview , I also subscribe to the topic and have a handle_info call , this would be very repetitive , I have asked if there is a way around this  on the forum.

**Comment by wintermeyer** [comment]
> Okay, I will , waiting for the verification from their end.

Please add the URL of the question to this issue.

**Comment by MICHAELMUNAVU83** [comment]
https://elixirforum.com/t/do-i-need-to-subscribe-individually-to-each-live-view-that-accesses-a-value-from-a-channel-even-if-they-are-all-within-the-same-layout/62886

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , from this https://elixirforum.com/t/do-i-need-to-subscribe-individually-to-each-live-view-that-accesses-a-value-from-a-channel-even-if-they-are-all-within-the-same-layout/62886/2?u=michaelmunavu , it seems my implimentation can still work , should I go forward with it?

**Comment by wintermeyer** [comment]
Yes, go forward with your implementation. Worst case: We change it in the future.
