### ISSUE TITLE
Add the number of green and red flags above the fold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#240]
Right now I'd have to manually count the number of green and red flags of a given profile. Since this is a very interesting information we should calculate and display it for the current_user right at the top of each profile.

<img width="611" alt="Bildschirmfoto 2024-04-13 um 12 02 22" src="https://github.com/animina-dating/animina/assets/69770/759af799-4353-426f-aaf0-1ae965f48824">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , what do you suggest we do when a flag is both a green flag and a red flag for the user

**Comment by wintermeyer** [comment]
Display two entries. One for green and one for red.

**Comment by MICHAELMUNAVU83** [comment]
I have done so, I want clarity on if  for example User Bob has picked  "honesty" as both a red and green flag , how should we handle this , show both green and red buttons on "honesty"

**Comment by wintermeyer** [comment]
> I have done so, I want clarity on if for example User Bob has picked "honesty" as both a red and green flag , how should we handle this , show both green and red buttons on "honesty"

Good catch! We should make it impossible that this can happen in the first place. Please create a new issue for that. We have to add validations for that and fix the selecting of green and red flags page accordingly.

**Comment by MICHAELMUNAVU83** [comment]
Okay .
