### ISSUE TITLE
Display and Update the points of a user in their profile

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#249]
I am not 100% sure about this feature but lets test this one: Add the points of that user in their profile and update it with the same mechanism which we already use to update the points.

<img width="635" alt="Bildschirmfoto 2024-04-14 um 11 45 33" src="https://github.com/animina-dating/animina/assets/69770/3a9e0cba-5482-490f-acf7-e5c03d43963c">

**Comment by MICHAELMUNAVU83** [comment]
This would be amazing , if you see  a profile you like getting more points , it would make you act fast and send a message maybe , pay some money for more points to do so , amazing feature
