### ISSUE TITLE
Add edit icon/link to each story for current_user == user

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#255]
If on the profile page the `current_user == user` we should display a link/icon at the end of each story to the page where one can edit this story.

**Comment by wintermeyer** [comment]
While we are at it:
- Add an icon to delete the story (but do a double check with a modal to be sure that no one clicked on it by accident)
- Add an icon to add a new story at the end of all stories.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , wanted to get your take on 2 things for this task 

1. For the delete modal , would you want an actual modal or the default one that phoenix provides which is as such
![Screenshot 2024-04-16 at 17 57 25](https://github.com/animina-dating/animina/assets/86654131/92a75079-5012-461e-9aa4-fba13fa11799)

2. For the delete and edit icons , should we have them directly on the UI or should we have 3 buttons that once you hover , you see a submodal with the icons as such


https://github.com/animina-dating/animina/assets/86654131/41f6b6af-392e-4ef7-a5a9-74e212ffcad0

**Comment by wintermeyer** [comment]
> 1. For the delete modal , would you want an actual modal or the default one that phoenix provides

Yes, the default one. 

For the future: I am a big fan of vanilla. If not mentioned otherwise I always prefer vanilla. ;-) 

> 2. For the delete and edit icons , should we have them directly on the UI or should we have 3 buttons that once you hover , you see a submodal with the icons as such

Good question. Let's go with the direct approach. Two icons. One for each action.
