### ISSUE TITLE
Fix Bug on 250 points credits to be added on every consecutive 10 days 

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#298]
- I just noticed a bug we will encounter where we add the 250 points if a user is in the system for 10 days consecutively , currently if a user has credits with the subject for 10 straight days , we add the points , this would mean if the user uses the system on day 12 , in reality , he/she has used for system for 10 days , so he will get the 250 points bonus , which should not be so.

We can fix this by adding a streak column  to the user that is an integer value , it incriments each day I get a "Daily Bonus" credit  and if I miss a day , it resets to 0.

With this method ,  now we can add the 250 credits when the streak is 10 , when it hits 10 , we add the 250 points , then we reset it and use it to hold the count of the days the user has used the system.

Thoughts @wintermeyer

**Comment by wintermeyer** [comment]
I see how much you like the idea of a streak column. 😉

Go for it if you want to. I know that this can also be done with the `credits` table. But: Done is better than perfect. Go for a streak column.

But please write a couple of tests to cover these edge cases. On second thought: Forget it! That would involve time traveling in tests. I don't even know if that is possible. Probably yes, but a lot of work.

**Comment by MICHAELMUNAVU83** [comment]
Yeah , I tried adding tests for the previous PR by adding "inserted_at" as a time the previous week and It did not work

**Comment by wintermeyer** [comment]
When you have time: Please ask this in the Elixirforum. With a bit of luck there is already a good to go solution for the problem and we probably want to do that in tests.
