### ISSUE TITLE
New Messages Resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#300]
We need a `message` resources for the chat functionality. Right now this is a two way system only. One can send a direct message to an other user and vice versa. Here is my idea of the needed attributes. Please feel free to change it.

- ID (Primary Key)
- SenderID (Foreign Key referencing the ID of the Sender from your existing User Table)
- ReceiverID (Foreign Key referencing the ID of the Receiver from your existing User Table)
- Content (max 1.024 characters)
- Timestamps (inserted_at and created_at)
- read_at (timestamp)

Please don't forget indexes on `sender_id` and `receiver_id`.

I'd like to start using policies with the resource. A user can only create a message if the receiver has `preapproved_communication_only` set to `false`.  Please write tests to ensure the working of this.

**Comment by wintermeyer** [comment]
Please add has_many for sender and receiver to the `User` resource.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , the timestamps should be created_at and inserted_at or created_at and inserted_at as you have put it?

**Comment by wintermeyer** [comment]
> the timestamps should be created_at and inserted_at or created_at and inserted_at as you have put it?

The default. Not a typo by me. I always prefer vanilla for all computer problems.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , if a receiver has set `preapproved_communication_only` to true, but the receiver has liked the sender's profile, the message should go through right?

**Comment by wintermeyer** [comment]
> @wintermeyer , if a receiver has set `preapproved_communication_only` to true, but the receiver has liked the sender's profile, the message should go through right?

Correct

**Comment by MICHAELMUNAVU83** [comment]
Okay then , I think the best way forward would be I work on the messages first without policy as I need the likes resources for that, I then add the likes resources then have a separate task for adding policies

**Comment by wintermeyer** [comment]
Your call. You can start without the like too.

**Comment by wintermeyer** [comment]
I added a basic resource to handle likes: #303

**Comment by MICHAELMUNAVU83** [comment]
Okay..if it's good..merge it so I can pull from my side.
