### ISSUE TITLE
New Reactions Resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#303]
We have to create a new resource `reactions` to track who liked whom. 

- id
- sender_id
- receiver_id
- reaction (e.g. like, block, ...)
- created_at

Please add policies and tests. And add a policy for the `messages` that one can always create a message to a person which set a like to oneself.

Add a heard like icon to the right top of the page which can be clicked by the current_user to either like or unlike somebody. The unlike would be a destroy of that item in the database.

Example:

<img width="157" alt="Bildschirmfoto 2024-04-19 um 08 25 59" src="https://github.com/animina-dating/animina/assets/69770/3fe5503c-8d39-4b45-8e37-3f0eb4666769">

<img width="164" alt="Bildschirmfoto 2024-04-19 um 08 26 06" src="https://github.com/animina-dating/animina/assets/69770/31ab557d-e546-4eec-9fc9-f0ca68444f17">

**Comment by philipp-kempgen** [comment]
Does it make sense to use a more generic table (`user_reactions`/`user_flags`/`user_...`)? 🤔
- `id` (uuid)
- `snd_user_id` (uuid)
- `rcv_user_id` (uuid)
- `reaction`/`flag` (enum, e.g. "`like`", "`block`", ...),
- `created_at`
- `inserted_at`

**Comment by wintermeyer** [comment]
> Does it make sense to use a more generic table

Yes, it does. Good catch!

**Comment by wintermeyer** [comment]
I am not sure if actions are a good way to solve this or not. See
https://elixirforum.com/t/how-to-create-and-destroy-likes-and-blocks/63009

**Comment by wintermeyer** [comment]
I started with bb61bc3dd2911915064f34a0240a5219c9e0af03 but please take over if you want.

**Comment by MICHAELMUNAVU83** [comment]
I will be adding the policies to this and the message resource.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we allow users to

1. Send messages to themselves
2. Like their own profiles

**Comment by wintermeyer** [comment]
No

**Comment by MICHAELMUNAVU83** [comment]
I will add a policy and test for this
