### ISSUE TITLE
Create like, unlike, block, unblock, hide and unhide actions for Reaction

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#310]
Right now the `Reaction` resource provides `[:create, :read, :destroy]` actions. But actually we want:

- :read
- :like
- :unlike
- :block
- :unblock
- :hide
- :unhide

Get rid of `create` and `destroy`. Why? Because we want to be able to provide an external API with the standard Ash tools. If somebody accesses the `Reaction` model over an JSON-API and uses the `create` action we have the dataset in the database but we don't trigger any other things. We might want to update the webpage for that user. We only can do that if we have some sort of hook for that. A `like` action would provide that hook. I am not 100% sure how the `actor` works but if it works like I think it works a `like` action would only need the `receiver_id` as an argument to work.

Please feel free to discuss. 
See: https://elixirforum.com/t/how-to-create-and-destroy-likes-and-blocks/63009/2

My aim is to get "the needed to be done with that action code" into that action and not somewhere else. If we call that action and I don't care if we do it in a LiveView or a 3rd Party software via a JSON-API we want to be sure that everything got triggered by that action which needs to be done.

**Comment by wintermeyer** [comment]
If I call the `:like` action from the `iex` I expect the heart symbol on the webpage of that users pair to change.

**Comment by wintermeyer** [comment]
The `remove_like` handle event would look something like this (just an example with pseudo code):

```elixir
def handle_event("remove_like", _params, socket) do
  Reaction.unlike(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id})

  {:noreply, socket}
end
```

**Comment by wintermeyer** [comment]
Please treat hide and block similar right now. I haven't figured out if there is a difference or not. Hide is thought for situations where I e.g. want to hide my account from a co-worker but not necessarily want to block him/her.

**Comment by MICHAELMUNAVU83** [comment]
> The `remove_like` handle event would look something like this (just an example with pseudo code):
> 
> ```elixir
> def handle_event("remove_like", _params, socket) do
>   Reaction.unlike(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id})
> 
>   {:noreply, socket}
> end
> ```



@wintermeyer  , the `unlike` ,`unblock` and `unihide` actions IMO should be defined as custom actions that take the reaction and an actor  , they are different from the `like` , `block` and `hide` as we do not want people to define the name when creating the reactions and let it be

```
Reaction.like(%{sender_id: 123 , "receiver_id": 11}, actor: actor)

```
as opposed to 
```
Reaction.create(%{sender_id: 123 , receiver_id: 11 , name: :like }, actor: actor)

```

The custom destroy actions would just take the reaction to destroy , thoughts?

**Comment by wintermeyer** [comment]
Yes, custom actions. Always remember that I am a mediocre programmer when reading my writing. I wasn’t aware of the difference.

**Comment by MICHAELMUNAVU83** [comment]
> The `remove_like` handle event would look something like this (just an example with pseudo code):
> 
> ```elixir
> def handle_event("remove_like", _params, socket) do
>   Reaction.unlike(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id})
> 
>   {:noreply, socket}
> end
> ```

Also @wintermeyer  , I asked this question on discord and Rebecca advised for actors we have it as such

`the actor is added on as part of the opts to the function call, eg. Message.create(%{map: of_stuff}, actor: user)`

so it would be

`Reaction.like(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id , sender_id: sender})`
and
`Reaction.unlike(actor: socket.assigns.current_user, reaction)`

**Comment by wintermeyer** [comment]
> > The `remove_like` handle event would look something like this (just an example with pseudo code):
> > ```elixir
> > def handle_event("remove_like", _params, socket) do
> >   Reaction.unlike(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id})
> > 
> >   {:noreply, socket}
> > end
> > ```
> 
> Also @wintermeyer , I asked this question on discord and Rebecca advised for actors we have it as such
> 
> `the actor is added on as part of the opts to the function call, eg. Message.create(%{map: of_stuff}, actor: user)`
> 
> so it would be
> 
> `Reaction.like(actor: socket.assigns.current_user, %{receiver_id: socket.assigns.user.id , sender_id: sender})` and `Reaction.unlike(actor: socket.assigns.current_user, reaction)`

Good for me. It was just pseudo code. I am not very good in remembering correct syntax. Fire at will.
