### ISSUE TITLE
Chat shouldn't need a reload

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#314]
The `live "/:current_user/messages/:profile", ChatLive, :index` currently needs a reload of the page to receive new messages. That is not user-friendly. New messages should be displayed right away via some sort of LiveView push thing.

Example: https://fly.io/phoenix-files/building-a-chat-app-with-liveview-streams/

Please add a second route:
```elixir
live "/current_user/messages/:profile", ChatLive, :index
```

No `:` in front of `current_user`. That is a route which we can use in documentation because it works for all users.

**Comment by MICHAELMUNAVU83** [comment]
> Please add a second route:
> 
> ```elixir
> live "/current_user/messages/:profile", ChatLive, :index
> ```
> 
> No `:` in front of `current_user`. That is a route which we can use in documentation because it works for all users.


For this route , who will the sender be?

**Comment by wintermeyer** [comment]
The current_user is always the actor and we know who he is because he logged.
