### ISSUE TITLE
Rate limit for new messages

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#315]
Since we will open a 3rd party API we need to make sure that a user doesn't get bombarded with messages by a robot. 

Let's implement the following rules:

- [x] - A user can not create more than 10 messages within a minute to an other user.
- [x] - A user can not create more than 20 messages within a minute.
- [x] - A user can not create more than 50 messages within an hour to an other user.
- [x] - A user can not create more than 250 messages on a single day.

Please try to realise this with policies.

**Comment by philipp-kempgen** [comment]
A herd of robots each sending me 250 messages per day would still be a lot of noise.
But maybe it's not even a problem, as long as I don't get an e-mail notification for each of the messages.
Once I log back in I should probably be able to block these robots.

**Comment by wintermeyer** [comment]
> A herd of robots each sending me 250 messages per day would still be a lot of noise.

I am not searching for a 100% solution. 80% is good enough.
