### ISSUE TITLE
How to make sure that not 500 messages are loaded

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#320]
This is an edge case but how can we make sure that there is no scenario where we load 500 or more messages from the past in the current chat window?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , we can initial messages to maximum of 500 , then havea button that says "See More Messages" that would display all the messages

**Comment by wintermeyer** [comment]
> @wintermeyer , we can initial messages to maximum of 500 , then havea button that says "See More Messages" that would display all the messages

Very good idea. But than we can set the initial maximum to 40. In most cases that is going to be more than enough.

Edge case: I don't know how we can provide this feature to the external JSON-API. Maybe a custom `sneak_read` action which just pulls the newest 40 messages would be the solution.

**Comment by philipp-kempgen** [comment]
As a programmer, I wouldn't immediately understand what `sneak_read` does. `peek` is clearer, imho.
But then again, that's also not quite right. `peek` means: "Start at the beginning, get x items, but don't advance the position."
In this case it's more like `reverse_peek` (`rpeek`?), as you're starting at the end.

**Comment by wintermeyer** [comment]
After sleeping one night over this problem I have one question: Can we tell the `:read` action how many entries we want to fetch? Can we call `:read` with an argument? This might be the easiest solution for the problem. I don't care so much if a 3rd party API always fetches everything. I mainly want to make sure that we don't overload the browser client with 500 old messages.

**Comment by philipp-kempgen** [comment]
I took that for granted. `read( 50 )`, `rpeek( 50 )`, `read_newest( 50 )`, ...

**Comment by briankariuki** [comment]
> After sleeping one night over this problem I have one question: Can we tell the `:read` action how many entries we want to fetch? Can we call `:read` with an argument? This might be the easiest solution for the problem. I don't care so much if a 3rd party API always fetches everything. I mainly want to make sure that we don't overload the browser client with 500 old messages.

Yes. ash `:read` actions can accept a pagination configuration which can then be used to paginate results via limit and offset

**Comment by wintermeyer** [comment]
> Yes. ash `:read` actions can accept a pagination configuration which can then be used to paginate results via limit and offset

Perfect. Let us use this.
