### ISSUE TITLE
Message Markdown or Tailwind bug

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#322]
<img width="324" alt="Bildschirmfoto 2024-04-23 um 08 03 57" src="https://github.com/animina-dating/animina/assets/69770/78876ef1-9248-4be2-8012-f2f63c46141e">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I would want to reproduce this bug , what message did you send here

**Comment by wintermeyer** [comment]
> @wintermeyer , I would want to reproduce this bug , what message did you send here

I can't replicate it right now because of https://github.com/animina-dating/animina/issues/364

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I beleive the issue is sorted , Is it possible for you to give this a go so I can know what to be on the look out for?
