### ISSUE TITLE
Rename /profile route

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#325]
Let us rename the `/profile` routes into `/current_user` routes:

```elixir
# old
live "/profile/potential-partner", PotentialPartnerLive, :index
live "/profile/profile-photo", ProfilePhotoLive, :index
live "/profile/stories/new", StoryLive, :new
live "/profile/stories/:id/edit", StoryLive, :edit
live "/profile/flags/white", FlagsLive, :white
live "/profile/flags/green", FlagsLive, :green
live "/profile/flags/red", FlagsLive, :red
live "/profile/about-me", StoryLive, :about_me

# new
live "/current_user/potential-partner", PotentialPartnerLive, :index
live "/current_user/profile-photo", ProfilePhotoLive, :index
live "/current_user/stories/new", StoryLive, :new
live "/current_user/stories/:id/edit", StoryLive, :edit
live "/current_user/flags/white", FlagsLive, :white
live "/current_user/flags/green", FlagsLive, :green
live "/current_user/flags/red", FlagsLive, :red
live "/current_user/about-me", StoryLive, :about_me
```

**Comment by wintermeyer** [comment]
I am not 100% sure if this is a good idea or not. Just saying. 😉

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , for SEO , does having just 

```
live "/potential-partner", PotentialPartnerLive, :index
live "/profile-photo", ProfilePhotoLive, :index
live "/stories/new", StoryLive, :new
```

etc better , the only disadvantage would when we have a user wth a profile name of potential-partner

**Comment by wintermeyer** [comment]
> for SEO , does having just

No need to think about SEO here. No search engine will have a look into that directory.

**Comment by philipp-kempgen** [comment]
> Let us rename the `/profile` routes into `/current_user` routes:

> I am not 100% sure if this is a good idea or not. Just saying. 😉

I hate URLs with an underscore. It has to be "`-`". "`_`" is just for programmers. Just saying. :-)
How about "`my`" instead of "`current_user`"/"`current-user`"?
`/my/profile`, `/my/flags`, `/my/stories` ...
And don't allow "`my`" (or "`current_user`") as a username.

**Comment by wintermeyer** [comment]
I like the `/my` idea! @MICHAELMUNAVU83 is going to kill me for opening an other issue about this. 😉
