### ISSUE TITLE
Test the registration process

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#326]
I'd like to make sure that we don't pull the carpet we are standing on in the future with some additional feature or bugfix which adds a bug in the registration process which we don't see right away.

I'd like to have a integration test which registered a new user, uploads a photo, sets some flags and adds some stories.

@briankariuki Please share your thoughts about this. I don't want to burn days on this and don't have an idea how complex this task is.

**Comment by briankariuki** [comment]
@wintermeyer I'm thinking of creating one test that simulates the registration flow.

**Comment by wintermeyer** [comment]
Go for it!
