### ISSUE TITLE
Blacklist for problematic account names

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#329]
We need a mechanism where we can define/store not wanted usernames (e.g. I don't want anybody to use "hitler" as a username). Hardcoded is good enough right now. We can always move that to a database table later if needed.

**Comment by philipp-kempgen** [comment]
Don't allow `current_user` as a username.
https://github.com/animina-dating/animina/issues/325#issuecomment-2072951493

**Comment by wintermeyer** [comment]
Add `my` to the blacklist.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , for this , I am curious as to how you did the bad passwords bit , did you get them manually or is there a public api with most common passwords , wanted to use the same logic here.

**Comment by wintermeyer** [comment]
I used a public API of https://haveibeenpwned.com/

**Comment by MICHAELMUNAVU83** [comment]
Hey @wintermeyer  , did some digging around github and found this https://github.com/marteinn/The-Big-Username-Blocklist/blob/main/list_raw.txt , would love to hear your thoughts if this list is okay or I should  keep looking

**Comment by wintermeyer** [comment]
Maybe this is a misunderstanding. I am not searching for a list of words but just for an implementation of the mechanism. I’ll fill it with words while we move along.

**Comment by MICHAELMUNAVU83** [comment]
Thanks , this is well understood
