### ISSUE TITLE
Redirect /musterfrau to /Musterfrau

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#334]
Assuming a user created an account `Musterfrau` than her profile is available at http://localhost:4000/Musterfrau and http://localhost:4000/musterfrau and http://localhost:4000/musterfrAU but actually only the first one is correct.

Please do a proper redirect to the right username route in case there is a misspelling.

**Comment by wintermeyer** [comment]
We probably have the same problem with the chat route. Please doublecheck and fix if needed.

**Comment by MICHAELMUNAVU83** [comment]
Should it then redirect to the exact username ? So if I have `test` and I go to `Test` I should get an error?

**Comment by wintermeyer** [comment]
It should redirect to the exact username. In the ideal world this would be done with a 301 HTTP error code but that would be the icing on the cake.
