### ISSUE TITLE
Same user information

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#337]
When I open the chat for http://localhost:4000/wintermeyer/messages/Musterfrau I see this on top of that page:

<img width="816" alt="Bildschirmfoto 2024-04-24 um 08 12 34" src="https://github.com/animina-dating/animina/assets/69770/391d6cc2-bedf-49cb-88fa-8d9fb7b63ea9">

That doesn't help me as a user. The information from the profile page would give me a bit more background. So please refactor the following part and not only put it in the profile page but also use that as a replacement for the above blue thing for the chat page.

<img width="784" alt="Bildschirmfoto 2024-04-24 um 08 12 16" src="https://github.com/animina-dating/animina/assets/69770/84dfef5f-9c3a-4e5c-b8ae-14aaa0cd5e61">

PS: Please make sure that the heart is clickable and works on all pages it is used.

**Comment by MICHAELMUNAVU83** [comment]
> That doesn't help me as a user. The information from the profile page would give me a bit more background. So please refactor the following part and not only put it in the profile page but also use that as a replacement for the above blue thing for the chat page.
> 

Just for clarity , you would want the white bg text with the name and age etc to be at the top of the chat page , should it contain all that name , height , location , points and intersecting green and red flags?

**Comment by wintermeyer** [comment]
I want everything in the screenshot on both pages.
