### ISSUE TITLE
New system to update content

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#338]
I want to be sure that if a user works with multiple tabs/windows and something changes that all the tab/windows are updated with the new information. This should work for `user` and for `current_user`. And it should be implemented in a way that we can easily work with it.

**Example:** When a user (for what ever reason - it is just an example) changes his/her name than I want it to be updated on all open tabs/windows where this information is presented. The profile, all chats, all potential not yet written LiveView pages with that information.

# How to solve this

I don't know if this is the best idea (so please do feel free to present a better idea!): Add a Phoenix Presence for `user` and for `current_user`. Two different presences. One for all pages where I am logged in as a current_user and one for all the pages where my account gets used as user. So when I update my name we send an update request to both channels. That update request needs to trigger a reload of all information on that page so that LiveView can render the page and push an update if needed.

## preload

I guess we need to preload more things in the `User` resource to make this happen. I kind of hope that this would increase speed because we have less SQL queries. But of course we'd create a bigger `User` struct. We's have to live with that.

PS: I label this as a bug because as a normal user with no technical background I'd expect this to work automatically. But it doesn't in the current version.

**Comment by wintermeyer** [comment]
Please do ask questions if this is not totally clear. I understand that this involves quite a bit of refactoring. So I want to be sure that we are all on the same page.

**Comment by wintermeyer** [comment]
Just in case Presence is the wrong tool: I want to have two different "channels". If my account is `wintermeyer` than I want to have one channel where all the pages can be triggered for an update where this user is working as `wintermeyer` as the current_user and I want a second channel which gets triggered for an update where info about the user `wintermeyer` is published to (e.g. Chat).

I do not want to start hunting for code snippets which I might have to update if I change something in the future. I want to be sure that all pages reload all data automatically.

**Comment by briankariuki** [comment]
Looking at this maybe pubsub would be a better approach. Ash has a pubsub extension that can broadcast changes made to a document (for example a user struct). And then liveview's would subscribe to the  user's topic and receive these broadcast changes.

For live_components we could use the `update_many` callback to update the user for example in the message/story components.

**Comment by wintermeyer** [comment]
Pubsub sounds good.

**Comment by wintermeyer** [comment]
PubSub sounds very good. A LiveView would subscribe to a channel for `current_user` which would be in my case `wintermeyer` and in case other users are involved on that page those would subscribe to their channels.

**Comment by wintermeyer** [comment]
An other night, an other thought: We have to be careful with the approach of publishing a `User` struct to multiple pages because there is a chance that different users have different policies. Even if this is not a problem today it can become one in the future and then it is an easy one to oversee.

Long story short: Better trigger each LiveView to fetch the `User` data from the database with the correct `actor` so that we can be sure that the policies are in action.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , that makes sense , we will have to broadcast the user struct now everytime an action is performed , we have preloaded everything , so we should be good
