### ISSUE TITLE
sign-in leads to the registration process

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#342]
I am signed in on the left side. I open a new browser on the right side and sign in again with that account: That leads me to the registration process for that account.

But it should lead me to my profile.

![ScreenFlow](https://github.com/animina-dating/animina/assets/69770/7728aec4-4137-41f4-92b7-9aeddeb9d08b)

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I tested this out . If you refreshed or remounted on tab 2 after logging in on tab 1 , then on tab 2 , you would be automatically logged in as the tokens would have been stored in the session. This is a problem in phoenix applications and I am not sure if we can fix it

**Comment by wintermeyer** [comment]
We don't have the problem with tabs in the same browser because there we don't have to log in multiple times. But a lot of users will log into the application with their desktop browser AND their mobile phone browser. They will use the system in parallel on both devises. Or maybe even a 3rd or a 4th devise.

We know when somebody has gone through the registration process, don't we? If so we don't have to open the registration process again. We just redirect the user to his/her profile page after log-in.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I now understand , my idea here is to check if a user has filled details about his/her potential partner and if they have , they are taken to their profile , would this work .
Also should I  have a check for if they have added any flags , if not , we take them to the flags page , kindlly advise.
Something to consider is that users do not have to fill their preferred potential partner details.

**Comment by wintermeyer** [comment]
> @wintermeyer , I now understand , my idea here is to check if a user has filled details about his/her potential partner and if they have , they are taken to their profile , would this work

The best "test" would be the existence of an "about me" Story. With that we can redirect to the profile.

**Comment by MICHAELMUNAVU83** [comment]
Okay

**Comment by wintermeyer** [comment]
> Okay , if the story is not there, we redirect them to a page to add their first story , yes?

hmmm... the best thing probably would be an extra attribute to the `User` resource which stores the last LiveView page the user visited in the registration process. If there is no about me story we would redirect to that page.
