### ISSUE TITLE
NSFW image detection

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#350]
We don't want any NSFW images in the system. I want to use AI to solve a big part of this problem.

@briankariuki Please have a look at 
https://huggingface.co/Falconsai/nsfw_image_detection or similar systems and give me an estimate how much work (time wise) an implementation would take. I am pretty sure that we can solve this with Elixir but I have no idea how long it will take to program.

Image which are detected as NSFW would be deleted right away. I do not care about false positives at this stage of the application.

Brian: Please share your thoughts in this issue so that I can make a decision how to proceed.

**Comment by briankariuki** [comment]
I've looked at the model in the link you shared, and [https://github.com/elixir-nx/bumblebee/](https://github.com/elixir-nx/bumblebee/) might support it and that would greatly reduce the work for us. Allow me to test this and then I'll revert back to you with the findings.

**Comment by wintermeyer** [comment]
Go! 

I do think that this is absolute feasible within Elixir. But I don’t have the luxury to invest weeks into this. Please invest one day and add your findings here and suggest what we should do.

**Comment by wintermeyer** [comment]
This might be interesting or not. 
https://www.twitch.tv/alchemist_ubi

**Comment by wintermeyer** [comment]
On second thought: Let's not delete the image right away. Maybe we can use it to train our own AI in the future. Let's flag it or move it or something like that. 

We need some sort of queue for this. Where we can queue images to be rated by AI and humans to be safe or not.

BUT: We don't need to do this with this PR. I am just thinking loud. Delete is good enough for now.

**Comment by briankariuki** [comment]
@wintermeyer I've been able to get the model you shared working with bumblebee and it works great. I'll do a little bit more testing with different images. I'm now adding this into the animina code and I'll submit a PR for the feature.

<img width="1200" alt="image" src="https://github.com/animina-dating/animina/assets/34672053/96a7746b-1695-4ed9-be88-ec47c3aea504">

**Comment by briankariuki** [comment]
> On second thought: Let's not delete the image right away. Maybe we can use it to train our own AI in the future. Let's flag it or move it or something like that.
> 
> We need some sort of queue for this. Where we can queue images to be rated by AI and humans to be safe or not.
> 
> BUT: We don't need to do this with this PR. I am just thinking loud. Delete is good enough for now.

I'm thinking of incorporating ash_oban to do the queing and jobs processing for the uploaded photos. What do you think?

**Comment by wintermeyer** [comment]
> @wintermeyer I've been able to get the model you shared working with bumblebee and it works great. I'll do a little bit more testing with different images. I'm now adding this into the animina code and I'll submit a PR for the feature.

Great work! Please make sure not to add any NSFW photos in issues or in the repo. Otherwise all hell breaks loose.

**Comment by briankariuki** [comment]
> > @wintermeyer I've been able to get the model you shared working with bumblebee and it works great. I'll do a little bit more testing with different images. I'm now adding this into the animina code and I'll submit a PR for the feature.
> 
> Great work! Please make sure not to add any NSFW photos in issues or in the repo. Otherwise all hell breaks loose.

Noted

**Comment by wintermeyer** [comment]
> I'm thinking of incorporating ash_oban to do the queing and jobs processing for the uploaded photos. What do you think?

Sounds like a good idea.
