### ISSUE TITLE
user has_many flags through user_flags

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#353]
The following should be a has_many through relationship. We don't need the `user_flags` but the `flags` attached to the `User` resource.

```elixir
    has_many :flags, Traits.UserFlags do
      api Traits
    end
```

All the `current_user.user_flags(each).flag` code everywhere is suboptimal. It should be `current_user.flags`. The `user_flags` part should be invisible to most developers.

But please don't invest more than 4 hours into this. If this is a long thing just add that information to the issue and close it.

**Comment by wintermeyer** [comment]
Those flags should be preloaded by the `User` resource. No need to hit the database multiple times.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , it is possible with this 

```
many_to_many :flags, Traits.Flag do
      through Traits.UserFlags
      source_attribute_on_join_resource :user_id
      destination_attribute_on_join_resource :flag_id
end
```

I will refactor the flag live as well to ensure we do not hit the DB alot

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , I have created a PR , but I keep getting runtime errors , now I have this 
```
(RuntimeError) Resource `Animina.Traits.Flag` in relationship `:flags` is not in api `Animina.Accounts`. Please do one of the following
1. add the resource to the api `Animina.Accounts`
2. configure a different api

```
I followed the suggestions ash offered and it works
