### ISSUE TITLE
Enumerable not implemented for #Ash.NotLoaded<:relationship, field: :stories>

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#364]
On a fresh system I get (after a DB reset) on the second page of the registration process this error:

<img width="1155" alt="Bildschirmfoto 2024-04-30 um 07 39 04" src="https://github.com/animina-dating/animina/assets/69770/d0d06953-3764-4576-8455-c68c32ce10fc">

**Comment by briankariuki** [comment]
```
preparations do
    prepare build(load: [:age, :credit_points, :profile_photo, :city, :flags, :stories])
end
```
I believe the above is what's causing the error. I guess we should preload `:flags` and `:stories` only when needed and not for all actions calling the user's resource

**Comment by wintermeyer** [comment]
> I guess we should preload `:flags` and `:stories` only when needed and not for all actions calling the user's resource

I am fine with that but also wonder if this is a bug in Ash. Because shouldn't it act differently?

**Comment by briankariuki** [comment]
> > I guess we should preload `:flags` and `:stories` only when needed and not for all actions calling the user's resource
> 
> I am fine with that but also wonder if this is a bug in Ash. Because shouldn't it act differently?

I believe its not a bug. The login/registration route is essentially a json api endpoint, and most of ash structs are not json encodable by default. It tries encoding the user struct and fails.

I know of https://github.com/vonagam/ash_jason which tries to solve this but I believe in our case we can solve it simply without this package
