### ISSUE TITLE
Deactivate Machine Learning "Stuff" with a config switch

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#368]
It seems that the AI features we use have the downside of slowing down development on old hardware quite a bit.

@briankariuki Do you see a possibility to create some sort of switch which a developer can set to not have to use AI during his/her work in dev env?

**Comment by briankariuki** [comment]
I will add some configuration to enable/disable the ai modules

**Comment by wintermeyer** [comment]
> I will add some configuration to enable/disable the ai modules

As fare as I understood @MICHAELMUNAVU83 the problem involves compiling or installing mix packages. I have no idea if there is a way to make that optional too. Maybe a different dev environment?

**Comment by MICHAELMUNAVU83** [comment]
Yeah , we would probably look at this , @briankariuki  shared some ideas on how  I can fix my issue , I will explore them and advise

**Comment by wintermeyer** [comment]
@all Please don't forget to add what ever the solution is some information to the README.md about it.
