### ISSUE TITLE
Second avatar should be rotated by 12

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#37]
The second image should be rotated by 12.

<img width="454" alt="Bildschirmfoto 2024-02-14 um 09 04 22" src="https://github.com/animina-dating/animina/assets/69770/d62cf644-eb95-41ad-8859-32910e993c8c">

`notification_box/1` in `animina_components.ex`

**Comment by philipp-kempgen** [comment]
Tailwind `rotate-12` ?
https://tailwindcss.com/docs/rotate

**Comment by wintermeyer** [comment]
> Tailwind `rotate-12` ?

That is what we do right now:

```html
<div class="flex -space-x-4">
    <img class="w-16 h-16 border-2 border-white rotate-0" src="/images/unsplash/men/prince-akachi-4Yv84VgQkRM-unsplash.jpg" alt="">
    <img class="w-16 h-16 border-2 border-white rotate-12" src="/images/unsplash/women/stefan-stefancik-QXevDflbl8A-unsplash.jpg" alt="">
</div>
```

**Comment by wintermeyer** [comment]
@philipp-kempgen For what ever reason the `rotate-12` doesn't work here.

**Comment by philipp-kempgen** [comment]
Turns out the default values described on
https://tailwindcss.com/docs/rotate
aren't in `assets/tailwind.config.js`
(https://tailwindcss.com/docs/rotate#customizing-your-theme)
In this case though it's probably better to specify an arbitrary value
(https://tailwindcss.com/docs/rotate#arbitrary-values), as the amount of rotation is the result of a calculation.
=> `rotate-[12deg]`

**Comment by wintermeyer** [comment]
https://github.com/animina-dating/animina/commit/d0096906562644fa71441678b80a5f5c4b63a51b

**Comment by wintermeyer** [comment]
It still doesn't work. I checked it in Safari and in Chrome (both on macOS).

<img width="463" alt="Bildschirmfoto 2024-02-16 um 09 06 23" src="https://github.com/animina-dating/animina/assets/69770/5f48e51e-fe6b-42b3-aa5f-8e856f3881e8">

> Turns out the default values described on
https://tailwindcss.com/docs/rotate
aren't in assets/tailwind.config.js

As fare as I understand that page we don't need to set those values as long as we use the build in once (which 12 and 0 is). But @philipp-kempgen solution doesn't harm and opens up a good way for more avatars if needed.

I remember that it worked before but I changed something in the CSS around. Obviously without knowing what I was doing. ;-) My gut feeling tells me that the `flex` is the problem and that this is a bug in Tailwind. But I don't know what a good workaround could be.

**Comment by wintermeyer** [comment]
@philipp-kempgen @briankariuki Does the rotation work for you? Because if it does it could be some sort of building workflow bug on my system.

**Comment by wintermeyer** [comment]
Thank god we don't have to waste time on this. 😂😉

**Comment by briankariuki** [comment]
> @philipp-kempgen @briankariuki Does the rotation work for you? Because if it does it could be some sort of building workflow bug on my system.

Let me check

**Comment by briankariuki** [comment]
> @philipp-kempgen @briankariuki Does the rotation work for you? Because if it does it could be some sort of building workflow bug on my system.

<img width="479" alt="image" src="https://github.com/animina-dating/animina/assets/34672053/aa825ae4-f32c-474c-bcfe-7bccd47c9ea5">


It has worked, but after I had to put rotate-12 in the classes list. For some reason, tailwind does not detect classes that result from functions, in our case `"rotate-"<>rotate_by` will not be resolved by tailwind unless 'rotate-12' exists elsewhere as a class

**Comment by philipp-kempgen** [comment]
https://tailwindcss.com/docs/content-configuration#dynamic-class-names
> The most important implication of how Tailwind extracts class names is that it will only find classes that exist as complete unbroken strings in your source files.
> 
> If you use string interpolation or concatenate partial class names together, Tailwind will not find them and therefore will not generate the corresponding CSS

So try something like (pseudo-code):
`rotate = (index == 0) ? "rotate-[0deg]" : "rotate-[12deg]"`

Won't rotate the avatar any further than 12 degrees for more than 2 avatars though, but maybe that's not even a problem.

**Comment by philipp-kempgen** [comment]
BTW: What was wrong with how it looked with the circles from #5 ?

**Comment by wintermeyer** [comment]
> BTW: What was wrong with how it looked with the circles from #5 ?

Nothing. It is just that everybody uses circles. So I thought why not two rectangles. But this is not set in stone.
