### ISSUE TITLE
ENABLE_ML_FEATURES=true should be the default

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#375]
`ENABLE_ML_FEATURES=true` should be the default since most developers are going to use it at some point. Please make it the default so that one only has to do a `DISABLE_ML_FEATURES=true` in case he/she doesn't want ML. Sorry for the additional effort. I should have thought about this before.

Please update the README.md.

CC @MICHAELMUNAVU83

**Comment by wintermeyer** [comment]
Just to be clear: Please rename the config switch.

**Comment by briankariuki** [comment]
@wintermeyer Some clarification, Should I add the `DISABLE_ML_FEATURES` and still retain the  `ENABLE_ML_FEATURES` flag?

**Comment by briankariuki** [comment]
> @wintermeyer Some clarification, Should I add the `DISABLE_ML_FEATURES` and still retain the `ENABLE_ML_FEATURES` flag?

I've gone ahead and renamed the flag to `DISABLE_ML_FEATURES`

**Comment by wintermeyer** [comment]
> I've gone ahead and renamed the flag to DISABLE_ML_FEATURES

Yes, please do that and just reverse the default. The ML stuff should start by default.
