### ISSUE TITLE
Role system

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#385]
We need some sort of role system. So we need one resource which just has the attribute `name` which is an atom. We have to seed two roles `[:user, :admin]`. We need an other resource `UserRole` which is a between resource and we have to create a many_to_many relationship between `User` and `Role`.

- In the dev environment the first user that gets created should automatically become a :user and an :admin.
- In any environment every new user should become a :user

Please add a policy that only an :admin can add other users to the :admin group/role.

**Comment by philipp-kempgen** [comment]
> We need some sort of role system.

Just some food for thought: Why? :-)

Do you need roles in the normal user-facing frontend?
Or is is maybe better to have a second admin-only frontend?
I really don't know what's easier to implement.

**Comment by wintermeyer** [comment]
> Why? :-)

Because one aim is to make it possible to use the system via a JSON API from a 3rd party application.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , if we have the many to many relationship , to fetch the role of a user it will be as such

```

User.by_username!("Michael").roles

[
  #Animina.Accounts.Role<
    __meta__: #Ecto.Schema.Metadata<:loaded, "roles">,
    id: "8fa710b0-bc67-46fb-b573-2fc79d5775b0",
    name: :admin,
    created_at: ~U[2024-05-08 01:43:41.320723Z],
    updated_at: ~U[2024-05-08 01:43:41.320723Z],
    aggregates: %{},
    calculations: %{},
    ...
  >
]

```

will it be okay if it comes in the format of an array , asking because I am assuming a user will only have one role

**Comment by wintermeyer** [comment]
Good question and I am not a 100% happy with the answer: A user can have multiple roles. I would have the user and the admin role. So list is perfect.

**Comment by wintermeyer** [comment]
Maybe we’ll add something like current_role in the future.

**Comment by MICHAELMUNAVU83** [comment]
Okay , I will have it as such
