### ISSUE TITLE
Add a user avatar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#39]
Right now we use the gravatar images for new users. That will not fly for most users. As a third step in the registration process we have to ask the user to upload or take a photo.

## Thoughts

- We need a SQUARE avatar photo of the user. If a user uploads a non square photo we have to autocrop it. Tricky. Maybe a task for AI. Worst case: We just auto crop it for now without any AI. Just do it and optimise it later.
- In case a Gravatar photo exists we should use that as a default. Saves the user some time.
- The photo has to have a minimum and a maximum resolution (size).
- We need to save the original uploaded file and a compress version (which we compress on the command line).
- In future steps we are going to ask the user for more photos which will be displayed in his/her profile. So this is going to be a `has_many` thing. 
- In the future the user has to have the possibility to change/delete those photos.
- We actually have to implement some sort of workflow to control all uploaded photos by a human team. Otherwise people will upload illegal stuff. So a new photo will be visible for the user but for everybody else only after a human has checked it.

@briankariuki In case you have a good idea: Please a) just go for it or b) discuss it here in the issue first. Feel free to create new issues and to split this one up.

**Comment by philipp-kempgen** [comment]
> Right now we use the gravatar images for new users. That will not fly for most users. As a third step in the registration process we have to ask the user to upload or take a photo.

I wouldn't do that in the registration process.
Let the user edit/complete his/her profile later on.

> * We need a rectangle avatar photo of the user. If a user uploads a non rectangle photo we have to autocrop it. Tricky. Maybe a task for AI.

Rectangular: yes. Square: not necessarily.
Yes, it's an easy task for an AI model (if there's a face), but it might be easier to let the user move the picture in a rectangular box.
Maybe there's a good JavaScript widget available for the process of uploading (drag-n-drop) and cropping a photo?

**Comment by philipp-kempgen** [comment]
Examples (didn't take a closer look):

- https://github.com/bytescale/bytescale-upload-widget
- https://shareurcodes.com/blog/create-a-jquery-image-upload-widget-with-preview-and-image-cropping-in-laravel
- https://foliotek.github.io/Croppie/
- https://medium.com/geekculture/send-a-cropped-image-from-react-to-rails-for-attachment-and-storage-f7d46d84abca

**Comment by wintermeyer** [comment]
> > Right now we use the gravatar images for new users. That will not fly for most users. As a third step in the registration process we have to ask the user to upload or take a photo.
> 
> I wouldn't do that in the registration process. Let the user edit/complete his/her profile later on.

We do need a photo of the user. Anybody who uses a dating platform is going to upload a photo at some point. We need the code solution for that. We can move it along the workflow if needed but we need the resource code anyhow.

> > * We need a rectangle avatar photo of the user. If a user uploads a non rectangle photo we have to autocrop it. Tricky. Maybe a task for AI.
> 
> Rectangular: yes. Square: not necessarily. Yes, it's an easy task for an AI model (if there's a face), but it might be easier to let the user move the picture in a rectangular box. Maybe there's a good JavaScript widget available for the process of uploading (drag-n-drop) and cropping a photo?

Right now I think: Let's just auto crop it to a square without any magic. Just make a choice for now. Once we are ready we can fine adjust it with AI or some JavaScript tool. Always keep in mind that 90% of all users will use this on their mobile phone. Hard to solve this problem GUI wise on a mobile devise.

**Comment by philipp-kempgen** [comment]
A plain file picker would be:

```
<input
    type="file"
    accept="image/*"
    name="upload_avatar"
    id="input-upload_avatar"
    class="rounded-sm w-full border-none"
    placeholder=" "
/>
```

On a mobile device this allows the user to either select one of the photos or use the camera to take a picture.

- https://web.dev/articles/media-capturing-images
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#examples

**Comment by philipp-kempgen** [comment]
- https://hexdocs.pm/phoenix_live_view/form-bindings.html#file-inputs
- https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#live_file_input/1
