### ISSUE TITLE
Update user profile if stories or flags change

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#393]
See https://github.com/animina-dating/animina/issues/391

We have the same problem with stories and flags. I want the user profile LiveView to automatically change its content when there is a change in the `User` resource or its has_many relationships. This should be done in the resource. I guess in the action but I am not familiar enough with the inner workings to make this call.

When ever the resource is changed and I don't care how (e.g. command line or 3rd party API) I want the content of an open profile LiveView page to change to.

- [ ] Send broadcast if a create action is called in the `Credit `resource.
- [ ] Send broadcast  if a create or delete action is called in the `Reaction` resource (for this , publish to both the receiver and sender)
- [ ] Send broadcast when a create action is called in the `UserRole` resource .
- [ ] Send broadcast when a create action is called in the `UserFlags` resource

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , @briankariuki  had a different view about how we had previously handled the  `User` resource where we would subscribe to  a user's topic and send broadcasts to it once stories and flags are added . He suggests we fetch the stories  and flags seperately as it would be expensive to do so.

I will therefore work on the following tasks for this PR and open another issue where we can continue with this discussion.


1. Send broadcast if a create action is called in the `Credit` resource.
2.  Send broadcast if a create or delete action is called in the `Reaction` resource (for this , publish to both the receiver and sender)
3.  Send broadcast when a create action is called in the `UserRole` resource .
4.  Send broadcast when a create action is called in the  `UserFlags` resource
