### ISSUE TITLE
Add a public boolean to the User resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#397]
Add a `is_public` boolean to the `User` resource. The default should be `true`. If it is true that profile can be viewed by anybody. Even anonymous has access to that profile. 

Please add a "Is only accessible for logged in animina users?" checkbox on the second registration page.

# What happens if it is set to true

- Anybody (including search engines) has access to that profile.

The tricky part is stuff like the heart. We do want it on the page even for non logged in users but if somebody clicks on it we want to redirect to a log-in page and wait for the log-in or registration to proceed with the like action. Please take a moment and think about this and similar problems. Create new issues if needed.

# What happens if it is set to false

- Users who are logged in have access to that profile.
- Anybody else gets a proper 404. No redirect! Just a 404 page with the text "This account profile either doesn't exist or you don't have the needed privileges to access it."

Thought: We should make it easy to add a black list in the future. I might not want my ex partner to have access to my profile.

- [x] Add is_private boolean to `User` resource
- [x] Add the checkbox on the second registration page
- [x] Move the "/:username" route to a use the :live_optional_user sesssion
- [x] Ensure users who are not logged in can view pages of public users
- [x] Ensure users who are not logged in  are taken to the sign up page if they click like and add story buttons
- [x] Ensure users who are not logged in do not see intersecting flags
- [x] Users can see a 404 page if either the user being accessed does not exist or they have not logged in and the profile they are looking at is not public

**Comment by MICHAELMUNAVU83** [comment]
For users who are not logged in , they should not see buttons to add likes , intersecting flags and for these users , we should have a call to action for them to sign up on the system

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we add the profile view credit points if a user who is not logged in is viewing a profile?

**Comment by wintermeyer** [comment]
> @wintermeyer , should we add the profile view credit points if a user who is not logged in is viewing a profile?

Very good catch! No, we do not add credit points for anonymous visits.

**Comment by wintermeyer** [comment]
> For users who are not logged in , they should not see buttons to add likes , intersecting flags and for these users , we should have a call to action for them to sign up on the system

They should see add likes buttons and what not. This is our chance to reel in new users. We want them to become curious. And we want the process to be as smooth as possible.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , for the functionality where an anonymous user likes a profile , they should be taken to the signup page then the like function should be performed kindly allow me to have that as a seperate issue as it is a huge task with some bit of logic.

How I have it now is that when you either hit the like or add story , you are taken to the home page

**Comment by wintermeyer** [comment]
> allow me to have that as a seperate issue as it is a huge task with some bit of logic.

No need to ask for permission for this kind of splitting up. Just create a new issue and link it to this one so that we have some sort of paper trail.

**Comment by MICHAELMUNAVU83** [comment]
> Please add a "Is only accessible for logged in animina users?" checkbox on the second registration page.
> 

![Screenshot 2024-05-04 at 18 39 41](https://github.com/animina-dating/animina/assets/86654131/2183d4db-43fc-4107-8b32-1949c8d7ac78)

@wintermeyer  , this may be confusing , I think it would be better to read , make my account public , then when we check the box , the user now has `is_public=true` , in the current state , we have it as the opposite  , if we check the button , we have `is_public=true` but we are saying the account is only accessible to animina users

**Comment by wintermeyer** [comment]
I want the wording of the checkbox as it is. But I don’t care about the attribute name. That checkbox should be unchecked by default.

**Comment by MICHAELMUNAVU83** [comment]
Okay , well understood , for clarity , I will change the attribute to `is_private`  that defaults to `false` hence the checkbox will be unchecked by default
