### ISSUE TITLE
Deactivate button when invalid form data

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#40]
<img width="483" alt="Bildschirmfoto 2024-02-15 um 13 10 27" src="https://github.com/animina-dating/animina/assets/69770/2e2b49b9-b205-4898-805a-85bda9f63252">

Since we know when the form data is valid we should use Tailwind CSS to deactivate the "Register new account" button until the form data is valid.

**Comment by philipp-kempgen** [comment]
See `/demo` page.

`<form class="group" …>` and:
https://github.com/animina-dating/animina/blob/897fb9bb1fa1623d276ce3b79c2a4cc559771676/lib/animina_web/controllers/page_html/demo.html.heex#L380
