### ISSUE TITLE
Coding of religion

### ISSUE THREAD

**Issue by philipp-kempgen** [wintermeyer/animina#402]
The current choice of religions is not that great, because it mixes up levels of detail.

https://github.com/animina-dating/animina/blob/8ae0328255735fd4660e0ac7e9ddd854a84170a7/priv/repo/migrations/20240228210500_seed_flag.exs#L1347

It's also a topic which you can easily get wrong.
I don't think this is the number one priority, but I would adopt an established scheme instead of inventing a custom scheme:

Bormann, Nils-Christian: EPR Ethnic Dimensions Data: Codebook. Version 2021. <https://icr.ethz.ch/data/epr/ed/>
(Look at the Codebook, Table 1: EPR-ED Classiﬁcation of Religious Segments, on page 5.)

Think of this as a tree.

- Someone may describe their religion as "`EARC1A1`" (Southern Taoism).
  Give them a choice of what level of detail they want to match with their partner, e.g.:
  - "`EARC1A1`" (Southern Taoism)
  - "`EARC1A`" (Taoism)
  - "`EARC1`" (Shenism)
  - "`EARC`" (Chinese Religions)
  - "`EAR`" (EAST ASIAN RELIGIONS)
  - "" (any)

- Someone else may not want to divulge so much detail and simply describe their religion as "`EARC`" (Chinese Religions) or "" (unspecified).

In theory someone describing their religion as e.g. "`EARC1A1`" (Southern Taoism) or "" (unspecified) might specifically look for a partner outside of their own "branch", such as "`ERB2A`" (Nichiren Buddhism), but I don't think this is an actual use case, so I wouldn't account for searches outside of the branch.

Maybe don't include the most detailed level in a `<select>` input so the usability doesn't suffer.

@wintermeyer You may potentially want to do that after the MVP milestone, I think. Just leave the issue for future reference then.

It's just an example of data that can't really be coded as flags.

**Comment by wintermeyer** [comment]
The religion is a test ballon. I just want to see if people use it. It is good enough for now. We might improve or delete these flags in the future.
