### ISSUE TITLE
<ul> and <ol> indention

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#404]
This is related to #384 

<img width="545" alt="Bildschirmfoto 2024-05-05 um 09 33 52" src="https://github.com/animina-dating/animina/assets/69770/95a7705f-834c-4e4d-b453-276e4f8a1c8f">

- `<ol>` should be numbers
- Both `<ol>` and `<ul>` should be indented a bit to the right. Please have a look at the E of the first sentence. The first bullet point should be intended to the right from that position. It used to work in the past. Something was changed.

Please doublecheck this with stories and in the chat.

## Example

If I use this here (in GitHub) it gets indented.

- a
- b
- c

1. a
2. b
3. c

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , adding vanilla css styles work for this problem
