### ISSUE TITLE
visit_log_entry Resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#416]
#415 creates a bookmark system for visited profiles. I want to enrich this with a `visit_log_entry` 

- [x] Create a `visit_log_entry` resource with these attributes
  - bookmark_id
  - user_id
  - inserted_at (or is it created_at? I always mix this one up)
  - updated_at
  - duration (integer which represents the length of the visit in seconds)
- [x] Add validations
- [x] Add relationships
- [x] Create a set of policies which make sense (see #415)
- [x] Policies for this resource will be the following
    - [x]  For Create Action , make sure I can create a visit_log_entry for a bookmark that I own
    - [x]  For the update action , I can only update it if I am the one who created it
     
- [x] We already have a system to add points for visits. Use that update the `duration`. It has not to be super exact. We don't have to track every ms.
- [x] Add a list entry for the bookmarks in the navigation part of the page with the name `most often visited` which lists the 10 most often visited bookmarks. Please don't forget to use the PubSub mechanism to update this list automatically.
- [x] Add a list entry for the bookmarks in the navigation part of the page with the name `longest overall visited` which lists the 10 bookmarks which have been visited the longest overall. Please don't forget to use the PubSub mechanism to update this list automatically.
- [x] Add Pubsub from resources
- [x] Add Tests

As always: Please create solutions so that a 3rd party API can do use this feature too. So the `most often visited` and `longest overall visited` lists should be some sort of custom read action.

Yes, the `duration` is a tricky thing to be updated by a 3rd party API since we have no way to check if that entry is correct or not. We have to trust the 3rd party for that.

> [!NOTE]
> Write tests.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , can we also add user_id to the visit _log_entry resource?

**Comment by wintermeyer** [comment]
Go for it!

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , do you mean that here ,
![Screenshot 2024-05-19 at 13 33 52](https://github.com/animina-dating/animina/assets/86654131/172072cb-9ddc-46c1-9924-41cc1ba9c2d9)



 on the sidebar , we should have tabs for `most_often_visited` and `longest_overall_distance` that should go to live views?


> * [ ]  Add a list entry for the bookmarks in the navigation part of the page with the name `most often visited` which lists the 10 most often visited bookmarks. Please don't forget to use the PubSub mechanism to update this list automatically.
> * [ ]  Add a list entry for the bookmarks in the navigation part of the page with the name `longest overall visited` which lists the 10 bookmarks which have been visited the longest overall. Please don't forget to use the PubSub mechanism to update this list automatically.

**Comment by MICHAELMUNAVU83** [comment]
I have also made it such that we update the duration every second , is that too fast and if so , after what time would you prefer we update it?

**Comment by wintermeyer** [comment]
> on the sidebar , we should have tabs for `most_often_visited` and `longest_overall_distance` that should go to live views?

I have to see this. So please go for it and be prepared that I'll ask for some sort of change. I think it would be good to have it there but I have to see it to understand the GUI consequences.

**Comment by wintermeyer** [comment]
> I have also made it such that we update the duration every second , is that too fast and if so , after what time would you prefer we update it?

Duration of the visit? hmmm... can we find a more clever way to solve this? Like trigger something when the site is opened and closed and take the difference for this value? If we update it every second this will become massive traffic on the DB.

Always think of a couple of 10,000 concurrent users who are logged in at the same time.

**Comment by MICHAELMUNAVU83** [comment]
I will look into this and advise , found some resources , phoenix does not have an unmount callback , Chris Mccord suggests a Genserver to monitor the process https://github.com/phoenixframework/phoenix_live_view/issues/123
> Duration of the visit? hmmm... can we find a more clever way to solve this? Like trigger something when the site is opened and closed and take the difference for this value? If we update it every second this will become massive traffic on the DB.

**Comment by wintermeyer** [comment]
What about presence? Can we misuse that? We don’t need to be super exact.

**Comment by MICHAELMUNAVU83** [comment]
Good idea ,I will also look into how we can use presence and share my findings here

**Comment by MICHAELMUNAVU83** [comment]
> What about presence? Can we misuse that? We don’t need to be super exact.

I will create this as a seperate issue to enchance how we calculate duration spent on a website
