### ISSUE TITLE
Deduct credit points for visits

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#417]
A user has to pay points to visit a profile. Only public profiles are free to visit. I don't know how much we will charge for that. Let's assume - for now - we charge 20 points for the first visit. Following visits are free of charge.

Please think about this problem and come up with a solution which works for a 3rd party API too.

I guess policies are the best angle of attack for this. We have to make sure that an actor has enough points to read a user resource.

Use the `Credit` resource with a -20 points entry for the bookkeeping.

- [ ] Add an action in the user resource  `by_username_as_an_actor` that we use to check if a user has enough points to view a profile , in this case , if the profile has liked the user and this is the first time , they need at least 10 points , if they have not likes , 20 points
- [ ] For anonymous users they should call `by_username` as there is no actor in this case thus no deduction
- [ ] Add a credit with points of either -10 or -20 for first profile views

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  just a thought , should we deduct points if I am viewing a profile that has liked my profile too?

**Comment by wintermeyer** [comment]
> @wintermeyer just a thought , should we deduct points if I am viewing a profile that has liked my profile too?

Good thinking! hmmm… let’s implement it so that it costs points both ways but less in your example. Let’s say 10 for now.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , when for example I view your page and a credit is created with -20 or -10 should I make you the donor or that does not make sense as I am not giving you any points , I am deducting

**Comment by wintermeyer** [comment]
Good thinking! Make me the donor. Since it doesn’t harm. Maybe we’ll use that info in the future. Maybe not.
