### ISSUE TITLE
Fetch Stories and Flags Seperately without preloading on the User resource

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#418]
- Previously , we were preloading the User resource with the stories and flags , there is a suggestion from @briankariuki  to handle it diffrently and fetch them seperately .

**Comment by wintermeyer** [comment]
Go for it!

**Comment by briankariuki** [comment]
This is partially done for the profile_live page. Just wondering if there is any other place we were using `user.stories` before the change

**Comment by wintermeyer** [comment]
> This is partially done for the profile_live page. Just wondering if there is any other place we were using `user.stories` before the change

AFAIK we only have that one page where we display `stories`.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , making some changes for this issue by fetching flag and story resources seperately  and the system is much faster  , loading the user with flags and stories with more preloads made it slow.
