### ISSUE TITLE
PubSub.broadcast(Animina.PubSub, username

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#421]
I had a look at this code:

```elixir
  changes do
    change after_action(fn changeset, record ->
             username =
               User.by_id!(record.user_id)
               |> Map.get(:username)
               |> Ash.CiString.value()

             PubSub.broadcast(Animina.PubSub, username, {:user, User.by_id!(record.user_id)})

             {:ok, record}
           end),
           on: [:create]
  end
```

What happens if a user changes his/her username and an other user takes the old username in the same timeframe? Could that result into a problem? If yes, we should use the user.id for that. Which would probably simplify the code to a bit.

Fire at will.

I add the `bug` label but I am not 100% sure about this. Feel free to close the issue with a comment that this is not a problem at all.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , that is true , the username changes , but the id never changes , it would be wiser to subscribe to that instead .
