### ISSUE TITLE
Price list for points

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#424]
The more we use points to pay for stuff the more I realise that we need a better mechanism to handle how much something costs or how many points I get for something. Hard coding is too limited.

Example: There will be times with very low traffic and times with very high traffic. Wouldn't it be cool to have a tool to raise prices in peek times and lower prices in slow times?

But I don't want to invest too much time for this right now. I just want to make sure that we don't hard code point prices everywhere.

Please create one module which we can use to hard code the prices for now but which we can change in the future to make it more flexible. We should call that module/function in the rest of the code base when we need the amount of points needed for a specific thing (plus and minus points).

**Comment by MICHAELMUNAVU83** [comment]
I was thinking for this we can have a pricelist format as follows
```
  %{
        action: action_name, 
        points: points,
        price: price
}
```
- > The action can be `view_profile` , `read_story` , `send_message` etc
- > The points would be the amount of points needed for the action to be perfomed
- > The price is the price you would pay for the points         


I will also look into whether I can get total number of users on the system online to make this list dynamic , thoughts @wintermeyer

**Comment by wintermeyer** [comment]
When calling the function to get the price we also have to use the current_user as an argument. I can think of scenarios where different users get different prices. And nil must be possible too.

**Comment by MICHAELMUNAVU83** [comment]
Aha Interesting , mind sharing some scenarios like that?

**Comment by wintermeyer** [comment]
> Aha Interesting , mind sharing some scenarios like that?

Power users might get a rebate.
