### ISSUE TITLE
connection not available and request was dropped bug

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#432]
We have some performance or database issue with the current version. When I start to use the application and want to sign in I get the following error:

<img width="889" alt="Bildschirmfoto 2024-05-13 um 21 48 16" src="https://github.com/animina-dating/animina/assets/69770/17de283d-0e20-404c-9375-740177bba36e">

**Comment by wintermeyer** [comment]
Is it possible that this started with Oban and that we need a different database configuration in dev to tackle this? Or is it a programming bug? I want to understand what happens here so that we don't run into problems in production. Please leave a comment when you found the problem.

**Comment by briankariuki** [comment]
Could you try increasing the pool size in the repo config for dev. This is a temporary fix as I look deeper into the issue. I have not encountered this on my end.On 15 May 2024, at 09:11, Stefan Wintermeyer ***@***.***> wrote:﻿
Is it possible that this started with Oban and that we need a different database configuration in dev to tackle this? Or is it a programming bug? I want to understand what happens here so that we don't run into problems in production. Please leave a comment when you found the problem.

**Comment by wintermeyer** [comment]
@briankariuki I did double the pool size to 20. After that I get this error:

```elixir
[error] GenServer #PID<0.2553.0> terminating
** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (animina 0.1.0) lib/animina_web/components/profile/stories_components.ex:53: anonymous fn/2 in AniminaWeb.StoriesComponents."story_with_flags (overridable 1)"/1
```

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , from my research here https://michaldolata.appunite.com/post/how-to-deal-with-db-connection-connection-error as I cannot duplicate this bug , you can try adding the timeout here https://hexdocs.pm/ecto/Ecto.Repo.html#module-shared-options , then tell me what you get

**Comment by wintermeyer** [comment]
I set a 25_000 timeout. But I still run into this error:

```elixir
[error] GenServer #PID<0.2063.0> terminating
** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (animina 0.1.0) lib/animina_web/components/profile/stories_components.ex:53: anonymous fn/2 in AniminaWeb.StoriesComponents."story_with_flags (overridable 1)"/1
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
```

**Comment by wintermeyer** [comment]
These are the steps I do:

```elixir
$ mix ash_postgres.reset
$ mix create_dummy_accounts 5
$ iex -S mix phx.server
```

And than I open user profiles of the 5 users.

**Comment by wintermeyer** [comment]
The error:

```elixir
↳ anonymous fn/3 in AshPostgres.DataLayer.run_query/2, at: lib/data_layer.ex:701
[error] GenServer #PID<0.1431.0> terminating
** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (animina 0.1.0) lib/animina_web/components/profile/stories_components.ex:53: anonymous fn/2 in AniminaWeb.StoriesComponents."story_with_flags (overridable 1)"/1
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:546: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:773: Phoenix.LiveView.Diff.render_component/8
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:711: Phoenix.LiveView.Diff.zip_components/5
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:694: anonymous fn/4 in Phoenix.LiveView.Diff.render_pending_components/6
    (stdlib 5.2) maps.erl:416: :maps.fold_1/4
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:639: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:962: anonymous fn/4 in Phoenix.LiveView.Channel.render_diff/3
    (telemetry 1.2.1) /Users/stefan/GitHub/animina/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:957: Phoenix.LiveView.Channel.render_diff/3
Last message: {:phoenix, :async_result, {:start, {#Reference<0.0.183171.1222929939.1010106369.219780>, nil, :fetch_stories_and_flags, {:ok, [%{flags: [%{id: "f7c92bae-3a2b-42b6-b501-4fd39aea5dd8", name: #Ash.CiString<"Häkeln">, emoji: "🧵"}, %{id: "9b6fd797-2fa6-4369-a0d4-acd8b56564eb", name: #Ash.CiString<"Griechisch">, emoji: "🥙"}, %{id: "04b87b17-c907-494d-9102-d2775810943f", name: #Ash.CiString<"Thailand">, emoji: "🇹🇭"}, %{id: "e0d2fdd6-756c-402b-a7e1-9faccc127cbd", name: #Ash.CiString<"Achtsamkeit">, emoji: "🧘"}, %{id: "545e536d-4619-43df-9a2e-2c3c4ecfa630", name: #Ash.CiString<"Serien">, emoji: "📺"}, %{id: "accdbc3a-2e0f-4881-9c3a-1ff710ed2de0", name: #Ash.CiString<"Biografien">, emoji: "👤"}, %{id: "d9426e87-d2e3-4385-a014-670c496c3619", name: #Ash.CiString<"Romantik">, emoji: "💘"}, %{id: "cb3fa8ae-8023-40f6-a5b6-8c47a94270fc", name: #Ash.CiString<"Konzerte">, emoji: "🎵"}, %{id: "336bdf11-8076-479c-960e-330ce70f09c9", name: #Ash.CiString<"Elektro">, emoji: "🔊"}, %{id: "2a2d51a7-4a87-49eb-b3f6-c3e8415f554f", name: #Ash.CiString<"Australien">, emoji: "🇦🇺"}, %{id: "c40594d5-a08a-4e12-bb03-360aa543232b", name: #Ash.CiString<"Kinder- und Jugend">, emoji: "👧👦"}, %{id: "eb543119-ee40-4394-bf4b-679e454b0a2c", name: #Ash.CiString<"Hund">, emoji: "🐶"}, %{id: "7ad4b9f6-572e-4f43-8401-2eb6b0301434", name: #Ash.CiString<"Reality TV">, emoji: "📺"}, %{id: "b6e29d05-d457-4bc3-8f8f-1858a418f8a4", name: #Ash.CiString<"Aktiv">, emoji: "🏃"}, %{id: "6f501a35-1dcb-4dde-a292-295fc573a32c", name: #Ash.CiString<"Dokumentarfilme">, emoji: "🎥"}, %{id: "f5405e1d-80da-44de-9d33-7f5d4b2a5c86", name: #Ash.CiString<"Ski">, emoji: "⛷"}, %{id: "1bdcc271-f1b6-4413-a5c4-95e7b2419700", name: #Ash.CiString<"Reiten">, emoji: "🏇"}, %{id: "0799831f-2ffb-4a03-8305-5a9099fbdd29", name: #Ash.CiString<"Volleyball">, emoji: "🏐"}, %{id: "d99e3ee5-e273-4c82-b996-222cd4aac843", name: #Ash.CiString<"Ernährung">, emoji: "🍏"}, %{id: "972a7667-f9d6-44c8-8a43-766a46fa91dd", name: #Ash.CiString<"Vogel">, emoji: "🐦"}, %{id: "2646fef8-8670-44b0-915c-3e4b9f6568d3", name: #Ash.CiString<"Action">, emoji: "💥"}, %{id: "83f3e6a3-2507-454f-ae78-0acb98edf9d1", name: #Ash.CiString<"Fitnessübungen">, emoji: "🏋️‍♂️"}, %{}, %{}, %{}, %{}, %{}], id: "98a27e89-d96c-434c-bb1a-9f477ad4250d", story: #Animina.Narratives.Story<photo: #Animina.Accounts.Photo<story: #Ash.NotLoaded<:relationship, field: :story>, user: #Ash.NotLoaded<:relationship, field: :user>, __meta__: #Ecto.Schema.Metadata<:loaded, "photos">, id: "63d3914d-0832-4aeb-a59a-63e4ee3a3829", filename: "6e933725-c019-4b8d-bc46-fa6bff45c668.png", original_filename: "6e933725-c019-4b8d-bc46-fa6bff45c668.png", mime: "image/png", size: 1689062, ext: "png", dimensions: nil, error: nil, error_state: nil, state: :pending_review, created_at: ~U[2024-05-15 07:40:40.659540Z], updated_at: ~U[2024-05-15 07:40:40.659540Z], user_id: "a3636fa2-19a7-4d8f-b07f-1326f782ff63", story_id: "98a27e89-d96c-434c-bb1a-9f477ad4250d", aggregates: %{}, calculations: %{}, ...>, headline: #Animina.Narratives.Headline<__meta__: #Ecto.Schema.Metadata<:loaded, "headlines">, id: "80a04b46-4de0-474a-89a5-3382df729130", subject: "About me", position: 44, is_active: true, aggregates: %{}, calculations: %{}, ...>, user: #Animina.Accounts.User<city: #Animina.GeoData.City<__meta__: #Ecto.Schema.Metadata<:loaded, "geo_data_cities">, id: "ee12e87a-c7d7-4936-846d-2c0a8ed988e9", name: #Ash.CiString<"Winningen">, zip_code: "56333", county: #Ash.CiString<"Landkreis Mayen-Koblenz">, federal_state: #Ash.CiString<"Rheinland-Pfalz">, lat: 50.3219798791, lon: 7.51298799714, aggregates: %{}, calculations: %{}, ...>, profile_photo: #Animina.Accounts.Photo<story: #Ash.NotLoaded<:relationship, field: :story>, user: #Ash.NotLoaded<:relationship, field: :user>, __meta__: #Ecto.Schema.Metadata<:loaded, "photos">, id: "ede17001-1b01-4be3-8006-4e7a0bee77b8", filename: "6e933725-c019-4b8d-bc46-fa6bff45c668.png", original_filename: "6e933725-c019-4b8d-bc46-fa6bff45c668.png", mime: "image/png", size: 1689062, ext: "png", dimensions: nil, error: nil, error_state: nil, state: :pending_review, created_at: ~U[2024-05-15 07:40:40.630990Z], updated_at: ~U[2024-05-15 07:40:40.630990Z], user_id: "a3636fa2-19a7-4d8f-b07f-1326f782ff63", story_id: nil, aggregates: %{}, calculations: %{}, ...>, age: 73, credit_points: 0, bookmarks: #Ash.NotLoaded<:relationship, field: :bookmarks>, send_reactions: #Ash.NotLoaded<:relationship, field: :send_reactions>, received_reactions: #Ash.NotLoaded<:relationship, field: :received_reactions>, received_messages: #Ash.NotLoaded<:relationship, field: :received_messages>, sent_messages: #Ash.NotLoaded<:relationship, field: :sent_messages>, stories: #Ash.NotLoaded<:relationship, field: :stories>, traits: [#Animina.Traits.UserFlags<flag: #Animina.Traits.Flag<category: #Ash.NotLoaded<:relationship, field: :category>, flag_translations: [#Animina.Traits.FlagTranslation<flag: #Ash.NotLoaded<:relationship, field: :flag>, __meta__: #Ecto.Schema.Metadata<:loaded, "traits_flag_translations">, id: "c94ca109-105e-43dd-911e-7989d2c43c3f", language: "de", name: #Ash.CiString<"Häkeln">, hashtag: #Ash.CiString<"#Häkeln">, flag_id: "f7c92bae-3a2b-42b6-b501-4fd39aea5dd8", aggregates: %{}, calculations: %{}, ...>, #Animina.Traits.FlagTranslation<flag: #Ash.NotLoaded<:relationship, field: :flag>, __meta__: #Ecto.Schema.Metadata<:loaded, "traits_flag_translations">, id: "13c8f0d2-75b8-4384-a82a-c8433fd89168", language: "en", name: #Ash.CiString<"Crocheting">, hashtag: #Ash.CiString<"#Crocheting">, flag_id: "f7c92bae-3a2b-42b6-b501-4fd39aea5dd8", aggregates: %{}, calculations: %{}, ...>], __meta__: #Ecto.Schema.Metadata<:loaded, "traits_flags">, id: "f7c92bae-3a2b-42b6-b501-4fd (truncated)
iex(1)> 
```

**Comment by MICHAELMUNAVU83** [comment]
Thanks for this insight , let me see if i get the same on my side

**Comment by briankariuki** [comment]
```
<img
            :if={
              @story.user_id == @current_user.id ||
                @story.photo.state == :approved
            }
            class="object-cover rounded-lg aspect-square"
            src={AniminaWeb.Endpoint.url() <> "/uploads/" <> @story.photo.filename}
          />
```

This is the code block with the error. Clearly its the @current_user that's causing the issue.

**Comment by briankariuki** [comment]
@MICHAELMUNAVU83 You can walk back and log the assigns in the story_component to see what's the current value of the current_user. It should always be set and not nil.

**Comment by MICHAELMUNAVU83** [comment]
@briankariuki  , yes , this was the problem , sent a PR already

**Comment by MICHAELMUNAVU83** [comment]
@briankariuki  , we have anonymous users who can view public profiles so in their case , the current user would be nil

**Comment by wintermeyer** [comment]
BTW: The original problem still exists.

**Comment by philipp-kempgen** [comment]
> We have some performance or database issue with the current version. When I start to use the application and want to sign in I get the following error:

@wintermeyer Thought: Write a test that reproduces the problem. Maybe have that test run the action multiple times, if the problem doesn't happen all the time. Make sure the test fails in the GitHub action. That way you know the problem doesn't exist because of local configuration on a specific device, and you also know when it's fixed.

**Comment by philipp-kempgen** [comment]
> I did double the pool size to 20. After that I get this error:

That seemed to fix the original problem, as you then encountered a different, unrelated error.
(Maybe hide the unrelated comments here?)
So maybe a test would have to run the same action multiple times in parallel for the problem to occur reliably.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , when does the problem now occur so we can look at the best ways to test for it as @philipp-kempgen  suggested

**Comment by briankariuki** [comment]
> ```elixir
> mix create_dummy_accounts 5
> ```

I've tried these steps and the first error I got was about the zip code and then the database connection error

```
** (Ash.Error.Invalid) Input Invalid

* Invalid value provided for zip_code: must be a valid German city zip code.

nil

  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 2.21.14) lib/ash/error/exception.ex:59: Ash.Error.Changes.InvalidAttribute.exception/1
  (ash 2.21.14) lib/ash/changeset/changeset.ex:4859: Ash.Changeset.to_change_error/1
  (ash 2.21.14) lib/ash/changeset/changeset.ex:4805: Ash.Changeset.add_error/3
  (ash 2.21.14) lib/ash/changeset/changeset.ex:2279: Ash.Changeset.do_validation/5
  (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 2.21.14) lib/ash/changeset/changeset.ex:1401: Ash.Changeset.do_for_action/4
  (animina 0.1.0) deps/ash/lib/ash/code_interface.ex:565: Animina.Accounts.User.create!/2
  (animina 0.1.0) lib/mix/tasks/create_dummy_accounts.ex:46: anonymous fn/2 in Mix.Tasks.CreateDummyAccounts.generate_users/1
  (elixir 1.16.2) lib/enum.ex:992: anonymous fn/3 in Enum.each/2
  (elixir 1.16.2) lib/enum.ex:4388: Enum.reduce_range/5
  (elixir 1.16.2) lib/enum.ex:2532: Enum.each/2
  (animina 0.1.0) lib/mix/tasks/create_dummy_accounts.ex:25: Mix.Tasks.CreateDummyAccounts.run/1
  (mix 1.16.2) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.16.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
  /usr/local/bin/mix:2: (file)
  (elixir 1.16.2) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4
  (elixir 1.16.2) src/elixir_compiler.erl:52: :elixir_compiler.compile/4
  (elixir 1.16.2) src/elixir_compiler.erl:39: :elixir_compiler.maybe_fast_compile/3
  (elixir 1.16.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3

Unknown Error

* Unknown Error

* ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1948ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

```

**Comment by briankariuki** [comment]
@wintermeyer @MICHAELMUNAVU83 @philipp-kempgen 

I've boiled down the issue to using `User` instead of `BasicUser`. The user resource is very heavy as it loads related user resources. Specifically this code block.

```
preparations do
    prepare build(
              load: [
                :age,
                :credit_points,
                :profile_photo,
                :city,
                :flags,
                :traits,
                :roles
              ]
            )
  end
```

Every time a user is created it will preload these resources and return the user struct with them which is read heavy especially for flags and traits. If you switch to  using `BasicUser` the database connection will not timeout

**Comment by briankariuki** [comment]
> > ```elixir
> > mix create_dummy_accounts 5
> > ```
> 
> I've tried these steps and the first error I got was about the zip code and then the database connection error
> 
> ```
> ** (Ash.Error.Invalid) Input Invalid
> 
> * Invalid value provided for zip_code: must be a valid German city zip code.
> 
> nil
> 
>   (elixir 1.16.2) lib/process.ex:860: Process.info/2
>   (ash 2.21.14) lib/ash/error/exception.ex:59: Ash.Error.Changes.InvalidAttribute.exception/1
>   (ash 2.21.14) lib/ash/changeset/changeset.ex:4859: Ash.Changeset.to_change_error/1
>   (ash 2.21.14) lib/ash/changeset/changeset.ex:4805: Ash.Changeset.add_error/3
>   (ash 2.21.14) lib/ash/changeset/changeset.ex:2279: Ash.Changeset.do_validation/5
>   (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
>   (ash 2.21.14) lib/ash/changeset/changeset.ex:1401: Ash.Changeset.do_for_action/4
>   (animina 0.1.0) deps/ash/lib/ash/code_interface.ex:565: Animina.Accounts.User.create!/2
>   (animina 0.1.0) lib/mix/tasks/create_dummy_accounts.ex:46: anonymous fn/2 in Mix.Tasks.CreateDummyAccounts.generate_users/1
>   (elixir 1.16.2) lib/enum.ex:992: anonymous fn/3 in Enum.each/2
>   (elixir 1.16.2) lib/enum.ex:4388: Enum.reduce_range/5
>   (elixir 1.16.2) lib/enum.ex:2532: Enum.each/2
>   (animina 0.1.0) lib/mix/tasks/create_dummy_accounts.ex:25: Mix.Tasks.CreateDummyAccounts.run/1
>   (mix 1.16.2) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
>   (mix 1.16.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
>   /usr/local/bin/mix:2: (file)
>   (elixir 1.16.2) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4
>   (elixir 1.16.2) src/elixir_compiler.erl:52: :elixir_compiler.compile/4
>   (elixir 1.16.2) src/elixir_compiler.erl:39: :elixir_compiler.maybe_fast_compile/3
>   (elixir 1.16.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
> 
> Unknown Error
> 
> * Unknown Error
> 
> * ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1948ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
> ```

I pulled the latest main and did not get this error.

**Comment by wintermeyer** [comment]
I do have the feeling that this is a programming bug. Have a look how long the login takes. Some sort of recursion problem?

![ScreenFlow](https://github.com/animina-dating/animina/assets/69770/e476b34c-b5a2-4e46-9002-03f788c4aa1a)

**Comment by briankariuki** [comment]
@wintermeyer I can see @MICHAELMUNAVU83 changed the sign in function. Let me check it out

**Comment by briankariuki** [comment]
> I do have the feeling that this is a programming bug. Have a look how long the login takes. Some sort of recursion problem?
> 
> ![ScreenFlow](https://private-user-images.githubusercontent.com/69770/330869327-e476b34c-b5a2-4e46-9002-03f788c4aa1a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODgyNTcsIm5iZiI6MTcxNTc4Nzk1NywicGF0aCI6Ii82OTc3MC8zMzA4NjkzMjctZTQ3NmIzNGMtYjVhMi00ZTQ2LTkwMDItMDNmNzg4YzRhYTFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1NDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzEyZmZhMTk5ZTliNmY1MTBiNmU0YmFkZDkwN2FjY2M5YjQyMWMyMzAxYWMxZDY4ZjRhZjVmYjExYmFiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLn2f7E-v47EaMtghvGinI7x9TOBIfBK5v8joZKnleU) [ ![ScreenFlow](https://private-user-images.githubusercontent.com/69770/330869327-e476b34c-b5a2-4e46-9002-03f788c4aa1a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODgyNTcsIm5iZiI6MTcxNTc4Nzk1NywicGF0aCI6Ii82OTc3MC8zMzA4NjkzMjctZTQ3NmIzNGMtYjVhMi00ZTQ2LTkwMDItMDNmNzg4YzRhYTFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1NDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzEyZmZhMTk5ZTliNmY1MTBiNmU0YmFkZDkwN2FjY2M5YjQyMWMyMzAxYWMxZDY4ZjRhZjVmYjExYmFiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLn2f7E-v47EaMtghvGinI7x9TOBIfBK5v8joZKnleU) ](https://private-user-images.githubusercontent.com/69770/330869327-e476b34c-b5a2-4e46-9002-03f788c4aa1a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODgyNTcsIm5iZiI6MTcxNTc4Nzk1NywicGF0aCI6Ii82OTc3MC8zMzA4NjkzMjctZTQ3NmIzNGMtYjVhMi00ZTQ2LTkwMDItMDNmNzg4YzRhYTFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1NDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzEyZmZhMTk5ZTliNmY1MTBiNmU0YmFkZDkwN2FjY2M5YjQyMWMyMzAxYWMxZDY4ZjRhZjVmYjExYmFiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLn2f7E-v47EaMtghvGinI7x9TOBIfBK5v8joZKnleU) [ ](https://private-user-images.githubusercontent.com/69770/330869327-e476b34c-b5a2-4e46-9002-03f788c4aa1a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODgyNTcsIm5iZiI6MTcxNTc4Nzk1NywicGF0aCI6Ii82OTc3MC8zMzA4NjkzMjctZTQ3NmIzNGMtYjVhMi00ZTQ2LTkwMDItMDNmNzg4YzRhYTFhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1NDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzEyZmZhMTk5ZTliNmY1MTBiNmU0YmFkZDkwN2FjY2M5YjQyMWMyMzAxYWMxZDY4ZjRhZjVmYjExYmFiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLn2f7E-v47EaMtghvGinI7x9TOBIfBK5v8joZKnleU)

I think this might be the problem. In root_live there should be no current_user or session hence no need to fetch user.

```

 @impl true
  def mount(_params, %{"language" => language} = session, socket) do
    # current_user = Registration.get_current_user(session)

    # if connected?(socket) do
    #   if current_user != nil,
    #     do: PubSub.subscribe(Animina.PubSub, "credits")

    #   PubSub.subscribe(Animina.PubSub, "messages")
    # end
```

commenting out this code block now loads the login/register pages faster.

![register_update](https://github.com/animina-dating/animina/assets/34672053/56c43a33-bc57-4207-8c89-3e471218c841)

**Comment by MICHAELMUNAVU83** [comment]
> commenting out this code block now loads the login/register pages faster.
@briankariuki  The essence of subscribing here is to ensure if I am logged in and I go to the root page , if I get a message or my points are added , I see them on the sidebar .

**Comment by briankariuki** [comment]
> > commenting out this code block now loads the login/register pages faster.
> > @briankariuki  The essence of subscribing here is to ensure if I am logged in and I go to the root page , if I get a message or my points are added , I see them on the sidebar .

I think we can make the sidebar its own  liveview and do the subscribe there. This would also prevent having to subscribe to these topics in every liveview that will render the navbar.

But then I don't expect a logged in user to be able to visit the root liveview. They are already registered
