### ISSUE TITLE
Sign in via email address or username

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#433]
It should be possible to sign in with the email address or the username or is this a lot of work to achieve? We can use the `@`  character to find out if it is an email address.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , after some research and help from James Harton on discord there are 2 approaches
1. We can have a toggle where someone would have to either choose whether they want to sign in via email or username then we display 2 seperate forms (this would take a shorter period of time)
2. We could write our own custom action that would now check if a user has either that email or username , he suggested [Discord ](https://discord.com/channels/711271361523351632/955933117573652563/1239786257819631627) I write my own custom preparation which would take more time . 

Wanted to get your take on which route I should go down on

**Comment by wintermeyer** [comment]
> 2. We could write our own custom action that would now check if a user has either that email or username , he suggested [Discord ](https://discord.com/channels/711271361523351632/955933117573652563/1239786257819631627) I write my own custom preparation which would take more time .

I prefer the second version. But please only pursue this direction if you have the feeling that this can be done in a day or less. Otherwise assign me to the issue and add a time estimate to it.

TBH: I do not know if the Ash authentication is the best solution for us. It seemed to be a good start at the beginning but it became a constant problem. But that is a different thing.

**Comment by wintermeyer** [comment]
Use the `@` character as a differentiator and add it to the validation of the `User` and `BasicUser` model for the `username` attribute in a way that this character can not be used in a `username`.

**Comment by briankariuki** [comment]
> @wintermeyer , after some research and help from James Harton on discord there are 2 approaches
> 
> 1. We can have a toggle where someone would have to either choose whether they want to sign in via email or username then we display 2 seperate forms (this would take a shorter period of time)
> 2. We could write our own custom action that would now check if a user has either that email or username , he suggested [Discord ](https://discord.com/channels/711271361523351632/955933117573652563/1239786257819631627) I write my own custom preparation which would take more time .
> 
> Wanted to get your take on which route I should go down on

Check this out. Might give you a few pointers on how to use ash_authentication built in methods

https://gist.github.com/ahey/0c81097f0ce23054a00c8b77a26a0ab5

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , this gave me an idea , a custom read action , takes 2 args username_or_email and password , we validate the password and generate a token , the part I am stuck at is in the live view , is there any way I can put this user in the session the same way we do in conn with 
```
 conn
    |> delete_session(:return_to)
    |> store_in_session(user)
```


> TBH: I do not know if the Ash authentication is the best solution for us. It seemed to be a good start at the beginning but it became a constant problem. But that is a different thing.



Got this working btw , writing tests now
