### ISSUE TITLE
Integration test for user profile

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#446]
Write an integration test for the following scenarios. Setup: Create a profile for the users `alice` and `bob`. `alice` being a not public profile. `bob` being a public profile.

- Anonymous gets a 200 for `/bob`
- Anonymous gets a 404 for `/alice`
- Bob logs in and gets a 200 for `/bob` and `/alice`
- Bob logs in and logs out and after that gets a 200 for `/bob` and a 404 for `/alice`

There might be some overlapping with #444 I just want to make sure with this test that the profile page itself works and that we don't run into any nil this and nil that issues which result in 404 without being catched by the CI.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer just for clarity , should I check that I see "This profile either doesn't exist or you don't have enough points to access it. You need 20 points to access a profile page." , kindly expound here , thanks

**Comment by wintermeyer** [comment]
> @wintermeyer just for clarity , should I check that I see "This profile either doesn't exist or you don't have enough points to access it. You need 20 points to access a profile page." , kindly expound here , thanks

Why not. Doesn't harm to check for that too.

**Comment by MICHAELMUNAVU83** [comment]
What did you mean by the 200 and 404 though? Can we do this with live view tests?

**Comment by wintermeyer** [comment]
HTTP Code 200 for a normal page and 404 for a page that doesn't exist. Should be possible for LiveView too since this is a normal HTTP page which has to be fetched initially.

**Comment by MICHAELMUNAVU83** [comment]
Aha , tested it out and you can actually test for that ,  I will have to change some code that ensured we see the 

`This profile either doesn't exist or you don't have enough points to access it. You need 20 points to access a profile page`.  when you go to a page that does not exist or a text , this was actually a text , but the body is there and returns a 200 , apologies , I had not understood you well in that part  , I will fix it in the PR that closes this.

**Comment by wintermeyer** [comment]
That page should be an 404! One could argue about a 403. But not a 200. See my issue description.

**Comment by MICHAELMUNAVU83** [comment]
Okay , thanks
