### ISSUE TITLE
Limit PubSub.subscribe(Animina.PubSub, "credits") to the user

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#447]
I saw code like `PubSub.subscribe(Animina.PubSub, "credits")` in the application and I wondered why it wasn't something like `PubSub.subscribe(Animina.PubSub, "#{current_user.id}:credits")`

I am not so familiar with the PubSub idea but in case I understand the code and PubSub idea correctly any user would subscribe to all credits and that doesn't make sense and will just blow up workload for the system. Let the users just subscribe to their stuff and not to stuff from other users.

In case I misunderstood the code and functionality: Close the issue and think of me as an idiot. 😉

In case I did not misunderstand the problem: Go through the whole code base and fix it for similar situations (e.g. not just for credits). Use user_id instead of user_name because the first will not change ever.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I would love to get your thoughts here  , the main reason we do `PubSub.subscribe(Animina.PubSub, "credits")` is because of the 2 second system timer mechanism , say in 2 seconds , user x , y and z all get credit points updated, to which topic would we push to ? , with one topic "credits" , we now push them as such

```
[
   %{
        user: x,
         credit_points: 5,
},
  %{
        user: y,
         credit_points: 5,
},
  %{
        user: z,
         credit_points: 10,
}
]

```

If we want to remove the one credits topic and have a user subscribe to their credits topic , we would have to scrap off the 2 second thing , if you remember the issue here #406  , this was caused by a user subscribing to his/her own credit topic.

Do you think it would be better to remove the 2 second system timer , in this case , we update points as soon as you receive them , I remember you had reservations for this if someone is being viewed by 50-100 people at the same time.

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Let us assume that we have 10,000 concurrent users logged in the system. I doubt that it would be a good idea to push a list for all credit_points updates to each of them every 2 seconds. IMO it would be best to ping a trigger for each user which fetches an updated user profile including the credit_points from the database (since credit_points are automatically aggregated anyway). I don't like that we user `credit_points` when we have `user.credit_points` already.

I am aware that this would mean that we select all 10,000 users every 2 seconds from the database. I am not happy with that either but I think that by this way we keep the system clean and we get a mechanism to create different trigger timings for different users. In high load scenarios we might want to downgrade specific users to every 5 second updates.

IMO we should have one PubSub which is subscribed by any logged in user. We should use that to figure out who is logged in and use that information to publish update triggers every 2 seconds.

But I am open to discussion. I am not saying that my suggestion is flawless.

**Comment by MICHAELMUNAVU83** [comment]
> I am aware that this would mean that we select all 10,000 users every 2 seconds from the database. I am not happy with that either but I think that by this way we keep the system clean and we get a mechanism to create different trigger timings for different users. In high load scenarios we might want to downgrade specific users to every 5 second updates.
> 

Interesting idea , so in this case , after 2 seconds , we would send a broadcast to each user , so if 100 users are in the system , we send it to all the 100 ? 100 broadcasts , would it be something like that?

**Comment by briankariuki** [comment]
I think we should also move broadcast_user/1 to use ash pubsub instead to broadcast changes made to a user.

And then liveviews/genservers can subscribe to a topic and receive those changes

**Comment by wintermeyer** [comment]
Maybe this "every 2 seconds" thing is not the right way to go. The longer I think about it the more I come to the conclusion that the benefit is not that big but the potential problems are. I'll close this issue for now and think about it a bit more. I'll create new issues as soon as I have a better solution.

**Comment by wintermeyer** [comment]
> I think we should also move broadcast_user/1 to use ash pubsub instead to broadcast changes made to a user.
> 
> And then liveviews/genservers can subscribe to a topic and receive those changes

@briankariuki Please do create an issue about this and assign it to me. Describe the problem and the solution. I am open for that but I don't fully understand all the consequences yet.

**Comment by philipp-kempgen** [comment]
> we now push them as such
> 
> ```
> [
>    %{
>         user: x,
>          credit_points: 5,
> },
>   %{
>         user: y,
>          credit_points: 5,
> },
>   %{
>         user: z,
>          credit_points: 10,
> }
> ]
> ```

Is this what goes to every user?
I.e. does everyone get to know what other users are logged into the system?
