### ISSUE TITLE
When to display photos

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#452]
In the spirit of MVP we have to postpone the manual check of the images/photos. 

- [x] create a new `:nsfw` state which gets set by the AI when it thinks that the photo is not suitable for work. Don't delete the photo.
- [x] display `:nsfw` images only for their owner and admins
- [x] display a NSFW label over or near the that `:nsfw` image
- [x] For anybody else: Only display images with `[:pending_review, :in_review, :approved]` state

Use policies to make sure that images can not be read by users who don't have access to them. Remember the public boolean.

**Comment by MICHAELMUNAVU83** [comment]
> Use policies to make sure that images can not be read by users who don't have access to them. Remember the public boolean.


Hello @wintermeyer  , could you expound more here , should we display different images for  public users

**Comment by MICHAELMUNAVU83** [comment]
> Use policies to make sure that images can not be read by users who don't have access to them. Remember the public boolean.


Hello @wintermeyer  , could you expound more here , should we display different images for  public users

**Comment by MICHAELMUNAVU83** [comment]
> Use policies to make sure that images can not be read by users who don't have access to them. Remember the public boolean.


Hello @wintermeyer  , could you expound more here , should we display different images for  public users

**Comment by wintermeyer** [comment]
Use the same logic we use for stories for images.

**Comment by wintermeyer** [comment]
If `is_private` is false than a photo can be displayed for anybody. Otherwise follow the same logic as with the profiles and stories.
