### ISSUE TITLE
Different link and different information for bookmarks

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#458]
IMO the link to the profile in the bookmarks wastes to much real estate. The whole bookmark should be a link to that profile.

<img width="905" alt="Bildschirmfoto 2024-05-19 um 11 53 19" src="https://github.com/animina-dating/animina/assets/69770/cfae3e51-be6a-48df-8263-d80a41d0a4c6">

And we should include the information about existing red and green flags in case they are > 0. And if we display the points we have to make sure that they update otherwise remove them.

Bonus: A last visited information would be useful. And maybe a total number of visits.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  would you want to maintain the functionality of disliking a user you previously liked directly from the bookmarks page as it is 


https://github.com/animina-dating/animina/assets/86654131/fd34b2a3-c4da-4b3b-8dbe-e8c6068b7ccd



Also , I have it as in the real estate all we see is

username , intersecting flags , image , last visited information and total number of visits arranged as follows

![Screenshot 2024-05-21 at 18 38 30](https://github.com/animina-dating/animina/assets/86654131/3a660d95-003c-477d-a2d2-411d1969eaa6)



Is there anything important you would love to add here?

**Comment by wintermeyer** [comment]
> Hello @wintermeyer would you want to maintain the functionality of disliking a user you previously liked directly from the bookmarks page as it is

Yes, let's keep that.

> Is there anything important you would love to add here?

No, not now.
