### ISSUE TITLE
Add link to Bookmarks in the navigation bar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#459]
The navigation bar entry "Bookmarks" should link to /my/bookmarks
And while we are at it: The "Home" entry should link to the current_users profile URL.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , as I was working on links , I realized we do not have any link to direct a user to message another user . 
Would this be a good idea to have the chat icon on every profile as such .


![Screenshot 2024-05-20 at 10 33 25](https://github.com/animina-dating/animina/assets/86654131/3aafbedc-1e45-4e22-8465-3488d990d6f5)

**Comment by wintermeyer** [comment]
Good thinking! Go for it.
