### ISSUE TITLE
Add validation for zip codes (5 digits)

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#46]
In the current version of the application all zip codes are in Germany. German zip codes always have 5 digits. They can start with a 0 but they always have to be 5 digits long.

Please display a validation error:

<img width="463" alt="Bildschirmfoto 2024-02-16 um 13 24 46" src="https://github.com/animina-dating/animina/assets/69770/b79b2317-5607-48fa-a8cb-b3d2c2703930">

**Comment by philipp-kempgen** [comment]
The "Postal code" input field lets me enter "abcde".
The validation should probably make sure, that this field is digits only.

**Comment by wintermeyer** [comment]
@philipp-kempgen Good catch! Do you want to give that one a try? Add some sort of [0-9] regex to the validation.

Please reassign it to me in case you run into problems.
