### ISSUE TITLE
Tests for Async Loading on Profile and Bookmark Page

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#460]
When doing integration tests for pages that have Async Loading , we have an error where the html only shows the loading components , this may be because we are fetching a resource like the user that takes time?

If we remove the async loading , the tests work , but I believe we should keep the loading components and find a way to test it

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Why do you prefer async loading? What are the advantages for our application?

**Comment by MICHAELMUNAVU83** [comment]
I was indifferent about it but @briankariuki  advised for it. In the case that we are loading 20 stories , a user will not see empty space before the stories load . They see some sort of shadow . IMO it is very good for user experience , @briankariuki  can elaborate more

**Comment by wintermeyer** [comment]
IMO we will never have users with 20 stories. And I am willing to bet that the user experience is faster/better without async loading in our case. We do not have a lot of data. And we do not have a feed like Twitter which gets more updated all the time. 

@briankariuki Please share your thoughts.

**Comment by wintermeyer** [comment]
I have even seen a lack of async loading on 
my localhost dev environment and that is the best case scenario. I do have the feeling that it slows down the general experience for the user.

**Comment by MICHAELMUNAVU83** [comment]
It would make live view integration testing more direct if we removed the loading , we would have more confidence in the system with integration tests on each live now

**Comment by MICHAELMUNAVU83** [comment]
In that case @wintermeyer  , my next PR that will close the issue  #416  will remove the loading and will allow me to write integration tests on the Bookmarks page , so that will close this issue and #416 . The live page for the bookmarks looks as such now

![Screenshot 2024-05-20 at 07 17 57](https://github.com/animina-dating/animina/assets/86654131/991b0b01-62e3-49c1-bc07-228ac77a716b)

**Comment by briankariuki** [comment]
@wintermeyer @MICHAELMUNAVU83 async_loading fails in tests as Michael had shared with me. I think we can just use streams without loading the data in async.

We can still show a loader with some cool css tricks.

I have no idead why it doesnt work with tests. Maybe a bug in liveview.

**Comment by briankariuki** [comment]
@MICHAELMUNAVU83 I can work on this as tests was the last task left in that issue. I will include also a test for the liveview. That's if you have not yet started on the fix.

**Comment by MICHAELMUNAVU83** [comment]
Okay ,  I will test the most often visited and longest overall only .

**Comment by wintermeyer** [comment]
@briankariuki But the question still isn't answered: Why should we use Async Loading in our use case? **I am not against it but I really would like to understand why.** And that is totally independent of the testing.

**Comment by wintermeyer** [comment]
> We can still show a loader with some cool css tricks.

Before we start implementing trickery I really would like to dive into the problem. We have a very simple application. We don't have to do much calculation. We should be able to render the whole HTML on the server in let's say 50 ms. I'd be happier with below 35 ms but anything under 100 ms is fine for me in the MVP context.

So why would we want to introduce async loading with this kind of application? I understand it with a Twitter or Pinterest like application which has a constant feed which needs to load but we don't have that.
