### ISSUE TITLE
About me story page crashes

### ISSUE THREAD

**Issue by briankariuki** [wintermeyer/animina#464]
I create a new user and follow the onboarding steps. On reaching the create first story page, it crashes. 

<img width="1565" alt="image" src="https://github.com/animina-dating/animina/assets/34672053/9aae99c8-e8c4-4578-955d-6b1970af62ac">

**Comment by briankariuki** [comment]
Diving deeper, I think this is caused by the pubsub to the current_user's topic. Not sure what's broadcasting it. @MICHAELMUNAVU83 maybe you have an idea what's going on. 

```
PubSub.subscribe(
        Animina.PubSub,
        "#{socket.assigns.current_user.id}"
      )
```

**Comment by briankariuki** [comment]
A quick fix would be to add a `handle_info({:user, user}, socket)` callback, but we need first to know what's broadcasting the user. I couldn't find any function that's doing it in story_live. Maybe somewhere else?

**Comment by MICHAELMUNAVU83** [comment]
Yes , this was added to the lives to handle the credits update , if I am adding my story and someone views my page , the points on the sidebar should update . We were using that topic to catch this

**Comment by briankariuki** [comment]
> Yes , this was added to the lives to handle the credits update , if I am adding my story and someone views my page , the points on the sidebar should update . We were using that topic to catch this

But it crashes when a new user creates a new about me story. Please try it out on your end with a new user

**Comment by briankariuki** [comment]
> Yes , this was added to the lives to handle the credits update , if I am adding my story and someone views my page , the points on the sidebar should update . We were using that topic to catch this

I have refreshed my database and I don't have any other logged in user apart from the account I am using. In this case I should not receive any pubsub message for credits/user on this page.

**Comment by MICHAELMUNAVU83** [comment]
I have found the error , let me fix it on the next PR
