### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#474]
The finish line for the MVP is right in front of us. Only one thing is missing: We need some sort of dashboard for the `current_user`. It should become the home screen for him/her.

- [x] Create a `/my/dashboard` LiveView
- [x] Add Neccessary PubSub subscriptions
- [x] Add a [grid](https://tailwindcss.com/docs/grid-template-columns) system to that LiveView. We use that to add cards to the dashboard. 
- [x] Create a card component which we can use for all the cards (use [Card with header](https://tailwindui.com/components/application-ui/layout/panels#component-5a45d30370f33848da982e8b0879e0a3) as the initial starting point). Add a couple of dummy cards to the `dashboard` to see how the design works.
- [x] Ensure the card is responsive and works for both light and dark modes
- [x] Redirect `/my` to `/my/dashboard`
- [x] Adjust the navigation elements so that they link to `/my/dashboard`
- [x] `/my/profile` should display the same as `/:username` for `current_user` (I am not 100% about the duplication of content but let's tackle that one later)
- [x] Add `/my` and everything belong to the robots.txt file in a way that we ask search engines not to crawl it.
- [x] After login the `current_user` should be redirected to `/my/dashboard` in case there is no other logical target.

Did I forget anything?

**Comment by MICHAELMUNAVU83** [comment]
> * [ ]  Adjust the navigation elements so that they link to `/my/dashboard`

Hello @wintermeyer  , would you want the `Home` link to now navigate to the dashboard or should we add another link `dashboard` that should edirect to `/my/dashboard`

![Screenshot 2024-05-29 at 06 05 44](https://github.com/animina-dating/animina/assets/86654131/cb10964d-9dba-4fb0-ae77-cfd2996914da)

**Comment by wintermeyer** [comment]
Home is going to be the dashboard.

**Comment by MICHAELMUNAVU83** [comment]
> * [ ]  Redirect `/my` to `/my/dashboard`


@wintermeyer  , kindly clarify on this , I am not sure at which point someone would go to the `my` route

**Comment by wintermeyer** [comment]
> > * [ ]   Redirect `/my` to `/my/dashboard`
> 
> @wintermeyer , kindly clarify on this , I am not sure at which point someone would go to the `my` route

A poweruser might enter the /my URL. I would. So I want that user to be redirected to /my/dashboard

**Comment by MICHAELMUNAVU83** [comment]
Thanks
