### ISSUE TITLE
Report a user

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#479]
In case a user does something which is not appropriate other users have to be able to flag that account.

- [ ] Add a `Report` resource which belongs_to a `accuser_id` and a `accused_id` and has a `description` text field and an `internal_memo` text field. Plus a state `[:under_investigation, :denied, :accepted]`. Plus the usual timestamps. Plus an `admin_id` belongs_to field to save the admin who investigated the report.
- [ ] Please add common sense policies for reports. A report should only be readable be admins. Admins should only be able to edit the `internal_memo` attribute and change the state.
- [ ] Add a "Report this account" link in the bottom of the profile page.
- [ ] When that link is clicked the user has to be asked "To report an account is a serious act. The account will be deactivated right away and will be investigated by our team. Please tell us why you report the account."  In addition there has to be an entry field where that user can enter the description.
- [ ] The state of the accused account has to move to `:under_investigation` (#478) right away.

**Comment by wintermeyer** [comment]
Change to the states `:denied, :accepted` has to trigger a state change in the `user` resource too. `:accepted` will lead to a `:banned` and `:denied` to a `:normal` or `:validated` state.

We might have to add one more attribute to the `report` resource which saves the former `user` state. Otherwise we have to way of finding out if that user was `:normal` or `:validated`. Or we have to store that in the `user` model (might be wiser).

**Comment by wintermeyer** [comment]
`description` and `internal_memo` should accept and render markdown.

**Comment by MICHAELMUNAVU83** [comment]
> . Plus a state `[:under_investigation, :denied, :accepted]`.
> 

@wintermeyer  , would this be the state of the report of the state of the user.
If it is the state of the report , ie , as an admin , I am yet to look at that report , when I do and see that it is valid , the user's state is transitioned to banned , and if it is not valid , it is taken back to normal.
This can help when many people submit  reports , we keep track of reports we have already looked at.

I also think we should store the initial state of the user in the report resource.

**Comment by wintermeyer** [comment]
> would this be the state of the report of the state of the user.

State of the report.

> I also think we should store the initial state of the user in the report resource.

No need to ask me for this. It makes sense. Go for it.
