### ISSUE TITLE
Validate unique email address

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#48]
Email addresses have to be unique.

A validation error should be displayed:

<img width="464" alt="Bildschirmfoto 2024-02-16 um 13 29 02" src="https://github.com/animina-dating/animina/assets/69770/638dff0e-5fe5-427b-b296-86b043aad69d">

PS: Yes, this is a tricky problem because one could use this validation to check if a user has an account in the system. I have no idea how to solve this otherwise. We need a unique email address.

**Comment by philipp-kempgen** [comment]
Note that URIs such as e-mail addresses should go through a library that handles normalization, as e.g. "`Bücher.example`" and "`xn--bcher-kva.example`" is the same domain name, semantically, and we probably don't want to end up with 2 users
- "`user@Bücher.example`" and
- "`user@xn--bcher-kva.example`"

(<https://en.wikipedia.org/wiki/Internationalized_domain_name>)

Granted, if someone wanted multiple accounts, getting more e-mail addresses is an easy thing (think "+" notation, think disposable e-mail addresses).

But normalization would likely still be required for non-ASCII addresses. (Or make sure they are ASCII, for now.)

**Comment by wintermeyer** [comment]
@philipp-kempgen I see your point but I'd like to kick this can a bit more down the road. We can tackle that later. 

PS: https://github.com/kdeldycke/awesome-falsehood#emails
