### ISSUE TITLE
Add post resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#481]
It would be nice to have a basic blogging functionality. Just a `post` resource.

- [x] #494
- [x] #495
- [x] #496
- [x] #497
- [x] #498
- [x] #499

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , curious , what would be the difference between a post and a story? Would it just be that for stories we have pre defined headlines?

**Comment by wintermeyer** [comment]
> @wintermeyer , curious , what would be the difference between a post and a story? Would it just be that for stories we have pre defined headlines?

Yes, you are right. There are similarities. I haven't thought about that before.

- The main difference is that I would probably write multiple posts in a month but wouldn't change my stories for a very long time. 
- Ever user has to define stories about himself. Not every user has to create blog posts. I guess most will not. 
- Right now a post doesn't contain any images.

But again: Yes, there are similarities. There might be a chance to merge both in the future.
