### ISSUE TITLE
Tracking down slow queries

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#487]
This works without a problem (a DB reset and server start):

```bash
mix ash_postgres.reset 
iex -S mix phx.server
```

But this will result in problems (a DB reset, creating 5 dummy account and server start):

```bash
mix ash_postgres.reset 
mix create_dummy_accounts 5
iex -S mix phx.server
```

## The error message

In the past this was always a problem with slow queries. Please fix the problem and provide additional info in the issue. I really want to understand why we run into this problem again and again. This kind of problem has the potential to become a foot gun for a production system.

```elixir
[debug] QUERY OK source="photos" db=2.0ms
UPDATE "photos" AS p0 SET "state" = $1, "updated_at" = $2 WHERE (p0."id" = $3) RETURNING p0."id" [:in_review, ~U[2024-05-29 08:06:01.145232Z], "6f78c5c6-547f-459c-b1bd-c9c340faf634"]
↳ AshPostgres.DataLayer.update/2, at: lib/data_layer.ex:2647
[error] GenServer {Oban.Registry, {Oban, {:producer, "default"}}} terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1984ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (db_connection 2.6.0) lib/db_connection.ex:1059: DBConnection.transaction/3
    (oban 2.17.10) lib/oban/engine.ex:223: anonymous fn/4 in Oban.Engine.fetch_jobs/3
    (oban 2.17.10) lib/oban/engine.ex:319: anonymous fn/3 in Oban.Engine.with_span/4
    (telemetry 1.2.1) /Users/stefan/GitHub/animina/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.17.10) lib/oban/queue/producer.ex:245: Oban.Queue.Producer.start_jobs/1
    (oban 2.17.10) lib/oban/queue/producer.ex:236: anonymous fn/2 in Oban.Queue.Producer.dispatch/1
    (telemetry 1.2.1) /Users/stefan/GitHub/animina/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.17.10) lib/oban/queue/producer.ex:235: Oban.Queue.Producer.dispatch/1
    (oban 2.17.10) lib/oban/queue/producer.ex:168: Oban.Queue.Producer.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: :dispatch
State: %Oban.Queue.Producer{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: true, log: false, name: Oban, node: "Bimini", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Lifeline, [rescue_after: 1800000]}, {Oban.Plugins.Pruner, [max_age: 5184000]}, {Oban.Plugins.Cron, [crontab: [{"* * * * *", Animina.Accounts.Photo.AshOban.Scheduler.Process, []}]]}], prefix: "public", queues: [default: [limit: 10], photos: [limit: 10]], repo: Animina.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, foreman: {:via, Registry, {Oban.Registry, {Oban, {:foreman, "default"}}}}, meta: %{name: Oban, node: "Bimini", queue: "default", started_at: ~U[2024-05-29 08:05:51.871107Z], limit: 10, paused: false, updated_at: ~U[2024-05-29 08:05:51.871108Z], uuid: "3c359d5d-427d-4823-b8dd-e9e7737cbc35", refresh_interval: 30000}, name: {:via, Registry, {Oban.Registry, {Oban, {:producer, "default"}}}}, dispatch_timer: #Reference<0.2952353240.916979714.69743>, refresh_timer: #Reference<0.2952353240.916979714.69211>, dispatch_cooldown: 5, running: %{}}
[error] GenServer {Oban.Registry, {Oban, {:producer, "default"}}} terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1984ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information
```

**Comment by wintermeyer** [comment]
I am not against increasing the pool_size and what not. But I want to be sure that this is not an other problem. Until now it was always an architectural problem in the application and not a too small pool_size.

**Comment by briankariuki** [comment]
> I am not against increasing the pool_size and what not. But I want to be sure that this is not an other problem. Until know it was always an architectural problem in the application and not a too small pool_size.

@wintermeyer Will investigate this. But one thing I can think of is maybe reducing the queue size for photos in the oban config.

**Comment by wintermeyer** [comment]
I did a little bit of debugging. It seems that Oban is pumping too many jobs simultaneous into the system and that those jobs take all the CPU power. My laptop gets really warm.

As a first work around I'll change the Oban config to limit the number of photo jobs to 2. But I have the feeling that we have to have a look at the jobs itself too.

**Comment by wintermeyer** [comment]
@briankariuki What exactly do the Oban photo jobs do and how can I find out what takes so long?

**Comment by briankariuki** [comment]
It just runs the photo through the ML model with Nx.Serving

**Comment by wintermeyer** [comment]
> It just runs the photo through the ML model with Nx.Serving

Give me an idea how long that takes for a photo. Are we talking milliseconds, seconds, minutes or hours?

**Comment by briankariuki** [comment]
Thinking about it, maybe we can batch the photo jobs. Say like process 10 photos instead of one each time. Nx.Serving performs better when handling a batch of tasks instead of only one task. We can refactor the `process_photo` action to be a scheduled action that can run periodically and process the photos that are pending in one batch

**Comment by briankariuki** [comment]
> Should be seconds.

That I have some sort of problem on my dev system. 

```bash
PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP
30037  beam.smp     200.7 25:06.71 49/2   0    71    1082M+ 0B     346M   30037
```

@briankariuki Are you using `mix create_dummy_accounts 5` for testing your dev code locally?

Just a wild guess: Is it possible that we feed the AI with too big images?

**Comment by wintermeyer** [comment]
> Thinking about it, maybe we can batch the photo jobs. Say like process 10 photos instead of one each time. Nx.Serving performs better when handling a batch of tasks instead of only one task. We can refactor the `process_photo` action to be a scheduled action that can run periodically and process the photos that are pending in one batch

Please create a separate issue for that. Good idea!

**Comment by wintermeyer** [comment]
I opened a new issue for the performance problem: #491

**Comment by briankariuki** [comment]
> > Should be seconds.
> 
> That I have some sort of problem on my dev system.
> 
> ```shell
> PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS  PGRP
> 30037  beam.smp     200.7 25:06.71 49/2   0    71    1082M+ 0B     346M   30037
> ```
> 
> @briankariuki Are you using `mix create_dummy_accounts 5` for testing your dev code locally?
> 
> Just a wild guess: Is it possible that we feed the AI with too big images?

Your right. My implementation did not have a resize step for the image to a smaller size. Its enhance we can add
