### ISSUE TITLE
Performance issues while running photos through the ML model with Nx.Serving 

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#491]
My setup:

```bash
mix ash_postgres.reset 
mix create_dummy_accounts 5
iex -S mix phx.server
```

Than my Apple M1 laptop gets really warm/hot:

```bash
PID    COMMAND      %CPU      TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS
30037  beam.smp     200.2     34:55.92 49/2   0    71    1132M- 0B     346M
```

Something is not right here. I don't see any results in the database. The system is working like crazy but no result.

**Comment by wintermeyer** [comment]
Is it possible that we feed the AI with too big images? I remember that the AI only needs a relatively low resolution. But maybe I misread this.

**Comment by briankariuki** [comment]
Will fix this!

**Comment by wintermeyer** [comment]
@briankariuki I like the idea of setting up the system that multiple images at once are run to improve the ML performance. But I doubt that this will help with this problem.

Anyhow: When you improve the system by running multiple images at once please make sure that a single image will not stay unprocessed for ever just because there are no other images to process.

**Comment by wintermeyer** [comment]
Feel free to use convert. That is installed on the production server. 

https://fly.io/phoenix-files/resizing-images-using-elixir/

**Comment by wintermeyer** [comment]
https://huggingface.co/Falconsai/nsfw_image_detection

> The images in the pre-training dataset are resized to a resolution of 224x224 pixels, making it suitable for a wide range of image recognition tasks.
