### ISSUE TITLE
Second avatar in the notification box

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#5]
We need Tailwind CSS for this scenario (a second avatar on the left side):

<img width="441" alt="Bildschirmfoto 2024-01-19 um 08 16 24" src="https://github.com/animina-dating/animina/assets/69770/08ee511c-a2d7-415e-9ec2-84b6cc320e56">

**Comment by philipp-kempgen** [comment]
19290acece41ef1d83a1e923ace6deb5064df1b9

**Comment by philipp-kempgen** [comment]
19290acece41ef1d83a1e923ace6deb5064df1b9
