### ISSUE TITLE
Potential problem with a lot of photos

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#508]
If I understand it right the Oban jobs run once every 60 seconds. The NSFW AI check runs with a maximum of 6 images parallel. I can think of scenarios where a lot of people upload images and the queue gets so big that it would take for ever. In the meantime the CPUs are free.

I have no good solution for this. Please offer suggestions.

**Comment by wintermeyer** [comment]
@briankariuki Please have a look at this and think of a good solution. Right now it can happen that we have a big pile of unprocessed images while all the CPUs are idling most of the time.

**Comment by wintermeyer** [comment]
I believe that we might have a architectural problem with the 1 minute Oban way of doing things:
https://elixirforum.com/t/how-to-make-oban-run-more-frequently-than-once-in-a-minute/53595

Running `mix seed_demo_system` is a good example for the problem. It takes for ever for all the photos to be checked. With no need since the CPU could do the work right away with out a problem.

**Comment by briankariuki** [comment]
> I believe that we might have a architectural problem with the 1 minute Oban way of doing things:
> 
> https://elixirforum.com/t/how-to-make-oban-run-more-frequently-than-once-in-a-minute/53595
> 
> 
> 
> Running `mix seed_demo_system` is a good example for the problem. It takes for ever for all the photos to be checked. With no need since the CPU could do the work right away with out a problem.

In the forum post they are suggesting using a GenServer to queue the oban jobs

**Comment by wintermeyer** [comment]
I don't really care how we solve the problem. We just have to find a way to use the available CPU power without overloading the system. I don't know if Oban is the right tool for the given problem. But I am not saying that it isn't. I am just saying that the current implementation is a bottle neck and that we have to find a better one. Again `mix seed_demo_system` is a good example for the problem.

**Comment by wintermeyer** [comment]
We might have to reinvent the wheel here. We can use the state of an image to keep track of it. When somebody uploads a new image we count how many images are processed right now. If it is less than 6 we process it right away. If it is more than 6 than we don't but trigger every 20 seconds a process which just checks for not yet processed images and does them within that 6 limit. Maybe this is the death of Oban in this project (at least for this feature).

- When there is nothing do to on the system an upload should be handled right away.
- We have to make sure that we don't loose any images in case we upgrade the system and have to stop everything for that.

**Comment by wintermeyer** [comment]
#578

**Comment by briankariuki** [comment]
> We might have to reinvent the wheel here. We can use the state of an image to keep track of it. When somebody uploads a new image we count how many images are processed right now. If it is less than 6 we process it right away. If it is more than 6 than we don't but trigger every 20 seconds a process which just checks for not yet processed images and does them within that 6 limit. Maybe this is the death of Oban in this project (at least for this feature).
> 
> * When there is nothing do to on the system an upload should be handled right away.
> * We have to make sure that we don't loose any images in case we upgrade the system and have to stop everything for that.

If I get you right, we should process a batch of six images at a go. If there are less than 6 images to be processed, we process them. If there are more, we just pick six and the rest to be processed in the next run.

**Comment by wintermeyer** [comment]
> If I get you right, we should process a batch of six images at a go. If there are less than 6 images to be processed, we process them. If there are more, we just pick six and the rest to be processed in the next run.

Yes, but have a look at #578. Let us pick the low hanging fruit and kick the can down the road a little bit longer.
