### ISSUE TITLE
Navigation where user can go to reselect flags

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#514]
- @wintermeyer  , do we need a navigation link in the sidebar where a user can reselect flags?

**Comment by wintermeyer** [comment]
> do we need a navigation link in the sidebar where a user can reselect flags?

We do need some way for the user to do this, yes. Intuitively I would search this on the profile page because I can edit stories there. So it would be nice to add an edit button/link within the flag clouds.

Good catch!

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , would it be better on the sidebar and top nav or having one on each flags component , by flags component , I mean 

![Screenshot 2024-06-04 at 08 06 32](https://github.com/animina-dating/animina/assets/86654131/4bf55e23-d442-458c-bbdb-1e11f878f5ed)


So an edit icon at the top right of each of these .

**Comment by wintermeyer** [comment]
> would it be better on the sidebar and top nav or having one on each flags component , by flags component

I really don't know. I have to see it. Please make a call and go forward. Maybe I'll overrule it. Maybe not. 🤷‍♂️
