### ISSUE TITLE
Tell if there is nothing to show (e.g. no bookmarks)

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#535]
We have this problem at multiple points in the application. Please fix it when you stumble upon.

On the bookmark page http://localhost:4000/my/bookmarks it looks like this in the beginning:

<img width="851" alt="Bildschirmfoto 2024-06-02 um 09 58 08" src="https://github.com/animina-dating/animina/assets/69770/a0bd8cae-0ef0-40ba-8b32-0bca3299c38c">

A normal user need the information that currently he/she has 0 bookmarks. We are just not displaying anything. That is confusing for a normal user.

Please add a "No bookmarks yet" at the location where normally the bookmarks would be listed.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we do this for a profile that has no stories ? So we have `no stories ` on the profile.

**Comment by wintermeyer** [comment]
A profile with no stories is invalid. It cannot be displayed anyway. Otherwise, we would have a buggy validation system.
