### ISSUE TITLE
Reload potential partners

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#547]
At the end of the red arrow we need some sort of reload button/thing which will display 4 new profiles. Don't show that button if there are no new profiles possible because of a lack of potential profiles.

<img width="1340" alt="Bildschirmfoto 2024-06-02 um 18 02 09" src="https://github.com/animina-dating/animina/assets/69770/8736d5f7-1f50-45c8-873f-862c01236ba6">

Important: 

- When somebody clicks that reload button the next run shouldn't contain any of the profiles of the former screen.
- Reloading costs 20 credit points. Make sure that enough credits are available. Otherwise show the button but in an inactive state (grey).

Please discuss potential solutions in the issue. I have no idea how to solve this best.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , if I have 5 potential partners , I show the first 4 , then i reload , should I just see the 1 that was not shown before?

**Comment by wintermeyer** [comment]
> @wintermeyer , if I have 5 potential partners , I show the first 4 , then i reload , should I just see the 1 that was not shown before?

Yes. But wait for a moment. This is related to #548. I have an idea but I have to think about it a little bit longer.

**Comment by MICHAELMUNAVU83** [comment]
Similar to #641
