### ISSUE TITLE
Keep the potential partner list

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#548]
**Problem:** When I click on a profile in the dashboard and use the back button in the browser I see totally new profiles. But what if I like more than one profile from the original dashboard (the normal user not knowing that he could open multiple tabs)? In that case I would loose the others. And not just with the browser back button but also with the dashboard URL.

![ScreenFlow](https://github.com/animina-dating/animina/assets/69770/a76999f5-4af8-4462-a7e1-7eb74e3f51dc)

## Task

- Think of a way to solve this. Use this issue to discuss. Have a look at #547

**Comment by wintermeyer** [comment]
I think we need something like a `DisplayedCandidates` resource which stores those 4 `users`. When I reload/reshuffle them that resource would give us a way to a) not display the same ones and b) a time line so that we see how long ago a user was presented.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , this issue should be closed as now  we store them in the database so the list remains, what should stay is how best to reload the list of potential partners

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 Don't be afraid of closing issues without discussing it with me in case you are sure.
