### ISSUE TITLE
Show the user the error state of an image

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#555]
We have to give the user feedback in case there is a problem with an image. We should treat the "error" state as the "nsfw" state. Add a label to the image that the user can see. Make it visible (e.g. red). In your face visible!

<img width="669" alt="Bildschirmfoto 2024-06-03 um 11 51 54" src="https://github.com/animina-dating/animina/assets/69770/af09c0fd-3f1a-4454-9b14-1ebf44f28d9d">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should admins also see the error state?

**Comment by wintermeyer** [comment]
> @wintermeyer , should admins also see the error state?

Yes!

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 You know what? It makes more sense to display all error states to the owner and to admins. Only in the case of "approved" display nothing.

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 I meant all states. Only "approved" not.

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 The "error" state image should not be displayed to anybody else than the owner and admins. Because we don't know if it a potential nsfw image.

**Comment by MICHAELMUNAVU83** [comment]
Okay , that makes sense , the other states will also only be displayed to owners or admins

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we do this on the chat component too? Looks odd if I have it absolute and also on the bottom , is it necessary or we just do it for bookmark images and stories?

![Screenshot 2024-06-03 at 14 57 49](https://github.com/animina-dating/animina/assets/86654131/9c884ce5-3c27-4c29-964e-2c17e0e8195b)

**Comment by wintermeyer** [comment]
> @wintermeyer , should we do this on the chat component too? Looks odd if I have it absolute and also on the bottom , is it necessary or we just do it for bookmark images and stories?

Do it for chat too. If this error occurs it should be visible everywhere because the user should see it as soon as possible. Actually we should inform the user by email or chat DM but that is for an other issue.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I guess in that case , we should display photos with both`nsfw` and `error` to admins , previously , we only displayed for `nsfw`

**Comment by wintermeyer** [comment]
> @wintermeyer , I guess in that case , we should display photos with both`nsfw` and `error` to admins , previously , we only displayed for `nsfw`

We should display **everything** which is not `approved` to admin and to the owner.
