### ISSUE TITLE
Photos are not displayed at all

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#559]
I can see my own images but not those of other users.

<img width="1340" alt="Bildschirmfoto 2024-06-03 um 14 06 34" src="https://github.com/animina-dating/animina/assets/69770/2470c310-7eb3-4d99-ac6d-c38fc51aad90">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I am currently working on this , kindly advise if all the photos on this profile have the state `:error`

**Comment by wintermeyer** [comment]
> @wintermeyer , I am currently working on this , kindly advise if all the photos on this profile have the state `:error`

Truth be told: I did not check this one where I took the screenshot. I believe the photos were approved. But I am not 100% sure. I used `mix seed_demo_system` (which is new) to generate accounts.

**Comment by MICHAELMUNAVU83** [comment]
Okay , kindly pull the next PR I make and check this  page .

If the images are either NSFW or error , you do not see them , you will if you are an admin user though or the owner of that profile.

**Comment by wintermeyer** [comment]
All good now. Thank you, Michael!
