### ISSUE TITLE
"Could interest you" in navigation

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#593]
Please add a "Could interest you" section and put 5 dummy names there. Just for design purposes. I think we can use this space for customised updates for the current_user. If they get a DM from an other user we can display it there. Same with a like. A couple of possibilities. Static dummy is fine for now.

<img width="1340" alt="Bildschirmfoto 2024-06-05 um 07 42 37" src="https://github.com/animina-dating/animina/assets/69770/5699900c-272e-4492-8a7e-f525598be624">

**Comment by MICHAELMUNAVU83** [comment]
This would be good , we can have .

Most recent like
Most recent person who viewed your profile
Most recent chats 

etc
