### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#599]
This is just to make sure that it is heading in the right direction. AFAIK @MICHAELMUNAVU83 is not finished with the mobile version yet. I thought that it would be easier with the given example. But (again!) what is easy in software?! 😂

Current version:

<img width="387" alt="Bildschirmfoto 2024-06-05 um 09 29 58" src="https://github.com/animina-dating/animina/assets/69770/a1742c76-f342-4877-8b73-1a5cbfdc2553">

How it should be:

![ScreenFlow](https://github.com/animina-dating/animina/assets/69770/2617f5c4-39e0-4e15-8b14-3189f05614d6)

**Comment by MICHAELMUNAVU83** [comment]
Yes ,  working on this next , I will close #580  , as the next PR will close this issue .

**Comment by MICHAELMUNAVU83** [comment]
Also @wintermeyer  , I know you are not a fan of sticky elements , any idea what we can do with the footer when the page content is little?

![Screenshot 2024-06-05 at 11 04 03](https://github.com/animina-dating/animina/assets/86654131/9ad8e7e8-7919-4643-8492-c9de0871608d)

**Comment by wintermeyer** [comment]
> Also @wintermeyer , I know you are not a fan of sticky elements

😂

> , any idea what we can do with the footer when the page content is little?

Leave it as it is.
