### ISSUE TITLE
New CSS for the top navigation bar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#6]
For the top navigation bar we need the following additions:

- A way to highlight the current topic
- A way to display a count of new chat messages and new likes (chat message count example see screenshot)

<img width="489" alt="Bildschirmfoto 2024-01-19 um 08 20 21" src="https://github.com/animina-dating/animina/assets/69770/447967a3-6559-41a8-960f-cf7b2ed07465">

**Comment by philipp-kempgen** [comment]
#12
