### ISSUE TITLE
Remove opening animation of the left navigation menu

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#603]
Please remove the animation of the left menu when a new page gets rendered. I find it distracting and without feels the page faster.

![ScreenFlow-2](https://github.com/animina-dating/animina/assets/69770/24db9b10-d151-4cb8-8068-2ba164895435)

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , does this behavior happen on mobile or desktop.

**Comment by wintermeyer** [comment]
Desktop. I didn’t test mobile.

**Comment by MICHAELMUNAVU83** [comment]
This is the behaviour I get on my side  @wintermeyer 


https://github.com/animina-dating/animina/assets/86654131/799f6bc2-ff02-49ed-b3ee-32f64987616a



@briankariuki , could you test this out on your side

**Comment by wintermeyer** [comment]
It seems to be a Safari/MacOS problem. Can it be an Alpine.js "feature" which doesn't trigger on all browsers?

**Comment by wintermeyer** [comment]
Chrome doesn't show this animation.

**Comment by MICHAELMUNAVU83** [comment]
Let me do some research on this

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , It seems you have to customise the extensions on safari , check here https://github.com/alpinejs/alpine/issues/2808#issuecomment-1160260067

**Comment by wintermeyer** [comment]
> Hello @wintermeyer , It seems you have to customise the extensions on safari , check here [alpinejs/alpine#2808 (comment)](https://github.com/alpinejs/alpine/issues/2808#issuecomment-1160260067)

No, that's not it. That issue is 2 years old. Today's Safari and today's Alpine.js is totally different.

**Comment by wintermeyer** [comment]
It definitely has to do with Alpine.js. BUT it has self healed on my system. I guess it was a faulty cache.
