### ISSUE TITLE
Nudge the user to understand what is saved in bookmarks

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#613]
When a profile is displayed we could try to nudge the @current_user to understand that he/she will find that profile within the bookmarks again. I tried to draw a little ASCII art with an arrow but failed:

<img width="711" alt="Bildschirmfoto 2024-06-06 um 14 23 34" src="https://github.com/animina-dating/animina/assets/69770/85ef464f-5f65-4a8c-9f68-5641b20e3373">

Please think of something in that way but nicer.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer could this be better with a flash message..we check with the visit log entry..say when it gets to 20 seconds..we have ' It seems you like this profile , you can also find it in the bookmarks section'

**Comment by wintermeyer** [comment]
A flash message is too much in your face. I want this to be subtle.

Worst case: Just highlight the bookmark entry in the menu.
