### ISSUE TITLE
Visits counter in bookmarks doesn't work

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#620]
When I am in the bookmark section and click on a profile that profiles counter gets added +2 and not +1.

<img width="1022" alt="Bildschirmfoto 2024-06-07 um 17 06 33" src="https://github.com/animina-dating/animina/assets/69770/b1bd2a2c-caf3-43e7-b8ed-8f2c5a367b14">

**Comment by MICHAELMUNAVU83** [comment]
We need to call the function to create the visit log entry only when the socket is connected , if not , it will run twice , before and after the socket connects
