### ISSUE TITLE
sign_in with @wintermeyer and wintermeyer

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#627]
A user should be able to login with his/her email address, the `wintermeyer` and `@wintermeyer` account. Just in case somebody adds a `@` (people will for sure).

AFAIK we use the `@` as a differentiator between email address and username. We have to add a ' @' as a first character rule which would make it a username.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , the @ is actually not the differentiator , whether you add your name or email , we check whether that email or username matches the password provided

**Comment by wintermeyer** [comment]
> Hello @wintermeyer , the @ is actually not the differentiator , whether you add your name or email , we check whether that email or username matches the password provided

Please add this kind of differentiator. Otherwise I could create a username which is your email address. I want to be 100% that we don't run into any trouble here. 2 years down the road a developer might not remember this and will open some sort of security nightmare.

We should have a validation that `@` is not a valid character for the `username` too. I guess we already have that in place.

PS: This is just me being paranoid. 😉 Better safe than sorry.

**Comment by MICHAELMUNAVU83** [comment]
Okay @wintermeyer  , would now the idea be that when someone logs in and their username or email field has an @ , we check for it against email and not username .

For this feature we want to add , would this then be that if there is an @ at the start of the `username or email` , we check for it purely on usernames

**Comment by wintermeyer** [comment]
> Okay @wintermeyer , would now the idea be that when someone logs in and their username or email field has an @ , we check for it against email and not username .

Correct!

If I use `stefan@wintermeyer.de` that would mean: Only check for email addresses.
If I use `wintermeyer` that would mean: Only check for usernames.
if I use `@wintermeyer` that would mean: Get rid of the `@` and than check for usernames.

> For this feature we want to add , would this then be that if there is an @ at the start of the `username or email` , we check for it purely on usernames

Correct. Some sort of `s/^@//` search and replace regex is needed here.
