### ISSUE TITLE
All anonymous pages should only display "Could interest you"

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#636]
Pages which are viewed by anonymous users should not display the home, profile, bookmark, ... stuff. But they should display more of the "Could interest you" stuff. For them we should display 6 random of the 30 most popular users who are public. Just to make anonymous users curious.

<img width="1342" alt="Bildschirmfoto 2024-06-08 um 17 48 12" src="https://github.com/animina-dating/animina/assets/69770/8f2a8969-4446-470a-afe9-2848ec1a4b37">

**Comment by wintermeyer** [comment]
I let’s narrow it down to the female and male users who created an account within the last 60 days.

**Comment by wintermeyer** [comment]
50:50 male and female

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer ...and we should also only show users who are public on this page
