### ISSUE TITLE
Photo check doesn't work

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#644]
Here's what I did:

```bash
mix ecto.reset
mix seed_demo_system
iex -S mix phx.server
```

All the used photos are known by us and should easily go through the NTFW filter.

But the images are not being processed. After 5 minutes this is the database:

<img width="759" alt="Bildschirmfoto 2024-06-10 um 10 20 59" src="https://github.com/animina-dating/animina/assets/69770/0f9163ef-5a77-4303-b4c3-b7e81900bf6a">

**Comment by wintermeyer** [comment]
Related to #643 ?

**Comment by briankariuki** [comment]
@wintermeyer could you paste here the values in the error column?

**Comment by wintermeyer** [comment]
<img width="845" alt="Bildschirmfoto 2024-06-11 um 07 49 57" src="https://github.com/animina-dating/animina/assets/69770/86d8b773-0aa3-44d1-a6d3-841df272e41a">

Please ping me in case you need more or better.

**Comment by wintermeyer** [comment]
BTW: In case the system is started without ML we have to rubber-stamp all photos as being OK. Not a perfect solution but the best we can do. @MICHAELMUNAVU83 Please double check that once it is merged.
