### ISSUE TITLE
Replace Photo state words with dots

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#648]
@wintermeyer  , looking at the chat section , we have

![Screenshot 2024-06-11 at 12 41 49](https://github.com/animina-dating/animina/assets/86654131/369ee6c1-9488-4109-9c3b-28e55eb44f40)

![Screenshot 2024-06-11 at 12 41 58](https://github.com/animina-dating/animina/assets/86654131/426b28a2-7956-456d-ac27-606566d8248d)
 i think we can have different dots instead of full words at these places where we have an avatar ? Thoughts

**Comment by wintermeyer** [comment]
Yes, dots would be better. But to be honest I am not a big fan of the current chat design anyway. It feels off compared to the other pages. But I haven't had a better idea yet.

**Comment by MICHAELMUNAVU83** [comment]
okay , In case you get any inspiration , reach out and I will impliment it
