### ISSUE TITLE
Different size of the current_user avatar in the top right corner

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#654]
I changed this to 12 because I wanted the avatars in the left menu to be bigger. But the top right one should be more like 8.

<img width="1330" alt="Bildschirmfoto 2024-06-11 um 13 43 07" src="https://github.com/animina-dating/animina/assets/69770/63cbf1f1-813e-43f3-a42d-60021730c4f5">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , seems you had a look at this , on code we have it as w-8 h-8

![Screenshot 2024-06-12 at 19 43 53](https://github.com/animina-dating/animina/assets/86654131/8b55386c-c9c1-4114-9028-627f1658c4c0)
