### ISSUE TITLE
current_user defines 20 tags

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#67]
With https://github.com/animina-dating/animina/pull/66 a system of tags got introduced to the application.

After uploading a photo of him/herself a user has to choose a maximum of 20 out of those tags. The GUI should display the number of already picked tags. I think it would be best to display all tags (as pills?) in a long page. Separated by the Categories. Choosing a tag should be able by clicking on it. By that its color has to change to signal that it was chosen. Once the maximum of 20 choices has been made all other tags should be displayed in a way that it makes clear that they can't be clicked on. An already clicked on tag can be unchosen by clicking again on it.

It would be good to program it in a way that we can recycle it to choose red and green flags after this step. 

# The Idea

Each user can choose red and green flags for his/her future partner.

I haven't thought about a data model yet. Please feel free to discuss it in this issue or just go ahead and implement one. Please do remember to run a `mix run priv/repo/flag_seeds.exs` to seed the flags. Right now the database contains `de` and `en` versions. We should display the right one for the user.

Let's set the 20 as an easy to change variable somewhere. I am not sure if 20 is going to be THE number.

**Comment by philipp-kempgen** [comment]
Do you need to define hashtags in addition to title? Won't some method that takes the title, removes spaces, then camelCases and Titlecases do?

Actually, maybe the other way around: How about storing hashtags as fixed strings in the database and translating them with `gettext()`?

Just thinking out loud.

**Comment by wintermeyer** [comment]
> Do you need to define hashtags in addition to title? Won't some method that takes the title, removes spaces, then camelCases and Titlecases do?

Within limits I want to be sure that Hashtags are unique (within their scope). I have the feeling that this could be useful.

> Actually, maybe the other way around: How about storing hashtags as fixed strings in the database and translating them with `gettext()`?

That was my first idea too. But I think the database gives us an easier way to query for stuff. But I am not 100% sure. I think it has little downside and we can go the other way in the future if needed.
