### ISSUE TITLE
Add Reverse User State Actions

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#673]
- We need to have reverse user state actions eg `unban , recover , reactivate and normalize `

**Comment by wintermeyer** [comment]
Reactivate

**Comment by MICHAELMUNAVU83** [comment]
You would rather the action name start with a capital?

**Comment by wintermeyer** [comment]
No. Always use common sense. This was just me answering something from my iPhone which autocorrected to a capital letter.
