### ISSUE TITLE
Incognito User Actions

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#675]
Tasks are the following

For a profile that is incognito,
- [x] They can log in
- [x]  Other People cannot view their profile
- [x]  Admins Can view their profile
- [x] If the current user is incognito and they view their own profile , they should see it 
- [x]  We do not use them in the potential partners query

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , a question , if my account is hibernated or incognito , should I be able to see my own profile?

**Comment by wintermeyer** [comment]
Yes. It just would be nice to have a marker/sign on the profile which displays the current state and an easy way to go back to the normal state.
