### ISSUE TITLE
key :username not found in: nil

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#677]
I did a 

```bash
$ mix ecto.reset
$ mix seed_demo_system
$ iex -S mix phx.server
```

And when I want to open a profile I get this error:

<img width="1280" alt="Bildschirmfoto 2024-06-19 um 09 43 20" src="https://github.com/animina-dating/animina/assets/69770/8fe7bd8d-74b7-45e1-9a00-199376bf0bf2">

PS: Please write a test for this too.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , did you access this as an anonymous user?

**Comment by wintermeyer** [comment]
> @wintermeyer , did you access this as an anonymous user?

Yes, I did.

**Comment by MICHAELMUNAVU83** [comment]
Okay , the test is actually there , these problems occurs if the session is cached , which happens when you run the reset commands , and we cannot have tests for cached sessions. We will have to sort them out as they come.
