### ISSUE TITLE
Pick green flags

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#68]
After https://github.com/animina-dating/animina/issues/67 the current_user picks a maximum of 20 green flags for his/her future partner.

**Comment by briankariuki** [comment]
> After #67 the current_user picks a maximum of 20 green flags for his/her future partner.

Will these green flags be from the current flags list that we have?

**Comment by wintermeyer** [comment]
> Will these green flags be from the current flags list that we have?

Yes, the green and red flags are from the same current flag list.

**Comment by wintermeyer** [comment]
`UserGreenFlag` seems to be a good resource name.

**Comment by philipp-kempgen** [comment]
Do green and red flags (#69) (hashtags?) go into the same database table?
I think they probably should, with some kind of `type` as `ENUM('green', 'red')`.

Edit: Or maybe with some kind of `value` as `smallint` with green = 1, red = -1. You could then later add values 2 and -2 meaning green/red, but more important.

**Comment by wintermeyer** [comment]
> Do green and red flags (#69) (hashtags?) go into the same database table? I think they probably should, with some kind of `type` as `ENUM('green', 'red')`.

That is a brilliant idea! We can actually put all three types in the same database. 

`ENUM('own', 'green', 'red')`

- own: The flags of the user.
- green: Green flags the user is searching or in other users.
- red: Red flags the user wants to avoid in other users.

**Comment by wintermeyer** [comment]
Let's use colours only to name the flags. Than we can add an attribute `colour`

`ENUM('white', 'green', 'red')`

- white: The flags of the user.
- green: Green flags the user is searching or in other users.
- red: Red flags the user wants to avoid in other users.

**Comment by wintermeyer** [comment]
https://github.com/animina-dating/animina/issues/109
