### ISSUE TITLE
Markers to change that allow  a user to change their state.

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#681]
We need to allow a user to change their state, they can change it to hibernate , archived or incognito then back to normal.

@wintermeyer  , I have a couple of ideas for this . We could have this in the /my/profile page , a profile/user icon will have a dropdown with

```
Go incognito
Hibernate
Archive My Account
```

Or we have a full settings page dedicated to changing my name , location , phone number and now my state , something like'

![Screenshot 2024-06-20 at 07 13 53](https://github.com/animina-dating/animina/assets/86654131/5bdf7207-9e8e-494d-b61b-2a7aece5441b)

The second option would allow us to give the user more context about the state they are changing to.
Would love to hear your thoughts on this.

**Comment by wintermeyer** [comment]
I’d like to do this the “let’s just do something and see how it feels” way. I do not know what the best approach is. Follow your gut feeling and let us see where that brings us.
