### ISSUE TITLE
Send Email Notifications to Admins to Check when a report is filled

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#690]
- @wintermeyer  , we would want to ensure we have no overload of pending reports.
- We shiuld have email notifications that we can send to admins to look at a report and accept  or deny it.

**Comment by wintermeyer** [comment]
Good catch!

For now: Let's send an email to sw@wintermeyer-consulting.de whenever a profile is reported.

**Comment by MICHAELMUNAVU83** [comment]
I would recommend we use sendgrid.com , they have good styled template emails we can use.
We should also think about adding email notifications in the system for actions eg , signing up , when someone reports you , messages etc .

**Comment by wintermeyer** [comment]
No need to pay an external provider for something as basic as sending an email. We just use the locally installed postfix and SMTP. Vanilla setup.

**Comment by wintermeyer** [comment]
BTW: In case you are not familiar with how an email is send via SMTP just create a dummy function for it and assign an issue to me with the information for that function.

**Comment by MICHAELMUNAVU83** [comment]
Done , thanks . https://github.com/animina-dating/animina/issues/693

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we also send email notifications to the accuser and accused?

**Comment by wintermeyer** [comment]
> @wintermeyer , should we also send email notifications to the accuser and accused?

Please create an issue and assign it to me. We don't do this right now but maybe in the future. In case somebody is false accused we can set the profile free again within minutes. No need to alarm everybody for this.
