### ISSUE TITLE
Setup SMTP For Sending Email Notifications

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#693]
I propose we have a module as such
```
defmodule Animina.Notifications.Emails do
  @moduledoc """
    This module contains functions for sending emails notifications

  """

  def send_test_email do
    # send test email here
  end
end

``` 

@wintermeyer  , once you set this up , we can move on to classifying the notifications we need and sending them out

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , did you get a chance to look at this . If not , is it the same as following these https://hexdocs.pm/phoenix/1.3.0-rc.0/sending_email_with_smtp.html#:~:text=Sending%20email%20from%20a%20Phoenix,to%20try%20out%20the%20service.

If it the same and you have an SMTP username and password ,  I can give it a go

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , have you had time to look at this . It would be good to have welcome emails sent to our users for the MVP in the next couple of weeks

**Comment by wintermeyer** [comment]
> @wintermeyer , hello , have you had time to look at this . It would be good to have welcome emails sent to our users for the MVP in the next couple of weeks

@MICHAELMUNAVU83 I created a working solution.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , is there something I must confugure. Tried this 

```
UserEmail.UserEmail.send_email("Michael" , "michaelmunavu83@gmail.com" , "Test" , "testing...")
```

And I did not get an email

**Comment by wintermeyer** [comment]
You don’t get the email in dev env. Have a look at the README how to see that email.
