### ISSUE TITLE
Use dots for photo state in bookmarks

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#716]
@wintermeyer  , should we maintain the text that we currently have to show the state of the photo or should we move to dots

![Screenshot 2024-07-02 at 06 32 48](https://github.com/animina-dating/animina/assets/86654131/43dc8fa6-b7f9-4f2e-8b20-4e14f114c3c8)

**Comment by wintermeyer** [comment]
Keep the text. We have bigger fish to fry right now.
