### ISSUE TITLE
An admin view where they can make other users admins

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#723]
@wintermeyer  would this be needed or would you be essentially the only admin?

**Comment by wintermeyer** [comment]
Good idea. But for now a code example in the README is enough. How can I give a user admin rights in the console?

**Comment by MICHAELMUNAVU83** [comment]
You would have to do 
```
UserRole.create(%{role_id: admin_role.id , user_id: user.id})
```
I will work on adding a custom function eg
```
UserRole.make_admin(user)
```

and add it to the README Documentation
