### ISSUE TITLE
Move or delete change visibility

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#744]
Currently a user has access to http://localhost:4000/my/profile/visibility but that shouldn't be. Only an admin should be able to make that change. We have to think about how to solve this usability wise.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , shouldn't the user  be able to make changes to their state eg , if I want to archive my account or make it incognito?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , did you find clarity on this issue , asking as it has a 'bug' label and we are nearing launch day

**Comment by wintermeyer** [comment]
I am still thinking about this.
