### ISSUE TITLE
Freak "scroll up and delete form" problem

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#76]
Since a couple of days (I wanna say it is related to the ImageCropping shenanigans - but I have no proof for that) I have the following problem: I pull new code from GitHub. Do a DB reset. Fire up the Phoenix application. Visit http://localhost:4000 and start filling out the form. In the `birthday` field something strange happens: The form deletes itself and the curser jumps up to the `username` field again. I have a hard time to replicate the problem because it doesn't happen the second time. It has happened multiple times in the last 2-3 days. Current macOS and Safari.

![freak-scroll](https://github.com/animina-dating/animina/assets/69770/07e4abb6-6e77-4498-91dd-0420bbae9199)

**Comment by philipp-kempgen** [comment]
The autofocus on the username annoyed me during development. I removed it in #60.
Haven't seen the form reset though, so that's some other problem.
