### ISSUE TITLE
Used Optimized Photos in The System

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#766]
@wintermeyer  kindly advise where we should use thumbnail , normal and big images

**Comment by wintermeyer** [comment]
Use the normal everywhere and make it so that there is a `:normal` argument when including the image. So that everybody can exchange that to `:thumbnail` or `:big` if needed.

**Comment by MICHAELMUNAVU83** [comment]
I was thinking about creating a reusable function that we can pass in the type, so this would work

**Comment by wintermeyer** [comment]
> I was thinking about creating a reusable function that we can pass in the type, so this would work

Yes, please do so.
