### ISSUE TITLE
%File.Error{reason: nil, path: nil, action: ""}

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#787]
When I run `mix seed_demo_system` I get this error:

```elixir
** (Ash.Error.Unknown) Unknown Error

* %File.Error{reason: nil, path: nil, action: ""}
  (mogrify 0.9.3) lib/mogrify.ex:13: Mogrify.open/1
  (animina 0.2.0) lib/animina/accounts/resources/photo.ex:272: Animina.Accounts.Photo.resize_image/3
  (animina 0.2.0) lib/animina/accounts/resources/photo.ex:261: anonymous fn/2 in Animina.Accounts.Photo.resize_image/1
```

@MICHAELMUNAVU83 Please test it on our testing server.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , does your imagemagick implimentation work locally?

**Comment by wintermeyer** [comment]
> @wintermeyer , does your imagemagick implimentation work locally?

Yes, it does. But please be more specific. How can I test for what you are looking for?

**Comment by MICHAELMUNAVU83** [comment]
Upload a new story with a photo and confirm in your logs if 3 optimized images will be created

**Comment by wintermeyer** [comment]
My guess is that this triggers the problem while running `mix seed_demo_system`.

**Comment by MICHAELMUNAVU83** [comment]
Yes ,do you  get any error running that test?

**Comment by wintermeyer** [comment]
`mix test` doesn't through any error.

`mix seed_demo_system` stops with that error. Please have a look into your email and try it on the testing server:

```bash
cd GitHub/animina
mix seed_demo_system
```

**Comment by MICHAELMUNAVU83** [comment]
I have an idea where the issue might be , have you automated deploys . I want to push and test something

**Comment by wintermeyer** [comment]
Automated deployment is still a work in progress. But you can do a `git pull` with your account on the testing system.

**Comment by wintermeyer** [comment]
You should be able to debug it with `iex -S mix phx.server` on the testing system.
