### ISSUE TITLE
Can't register a new account 😱

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#799]
When I try to register a new account I can't click on the button on the index page.

<img width="919" alt="Bildschirmfoto 2024-07-30 um 10 17 41" src="https://github.com/user-attachments/assets/f9f0d1e4-0c65-46d4-9840-4acbcf25f89f">

And I don't see any validation errors.

PS: This must not happen at all. We need a test for this to cover. Code can not become part of the main branch if this basic feature doesn't work.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , this works for me locally , have you checked the terms and condition box?

**Comment by wintermeyer** [comment]
My bad! When re-installing I didn't do a `cd assets && npm install`

Sorry, for the confusion.
