### ISSUE TITLE
Could interesting you on mobile is right in your face

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#801]
Have a look at this screenshot for http://localhost:4000 on a mobile devise:

<img width="404" alt="Bildschirmfoto 2024-07-30 um 10 40 03" src="https://github.com/user-attachments/assets/545764a5-85bf-40a0-a4f7-bda3971a087f">

This doesn't make sense. It should be in the top menu or not there at all.

**Comment by MICHAELMUNAVU83** [comment]
I think we can remove this for mobile , it would be huge for the dropdown as well

**Comment by wintermeyer** [comment]
My bad! I forgot to do a `cd assets && npm install` and that was the problem here.
