### ISSUE TITLE
Registration needs to check the email address

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#805]
Right now the registration process is streamlined to be as fast as possible. So after http://localhost:4000/ the workflow opens http://localhost:4000/my/potential-partner

After thinking about this I'd like to change that before we go online. Thoughts:

- We need to ensure that the email address exists. Of course it will slow down the registration process but on the other hand the user will have "something" in his/her inbox and we can make sure that they look into the spam folder too.
- We need a mechanism to slow down registrations in case we get flooded with new users. This is the easiest point we can change to make this happen. 

## The idea/workflow

After I filled out http://localhost:4000/ I'll get to http://localhost:4000/my/email-validation which says "We just send you an email to #{@user.email} with a confirmation link. Please click it to confirm your email address. The email is already on its way to you. Please check your spam folder in case it doesn't show up in your inbox."

> [!CAUTION]
>  We need to make sure that not a man in the middle can use that link in the email to attach to the on going registration process. I believe that Ash Authentication takes care of that but we have to double check. 

After that user clicks on that link we will display http://localhost:4000/my/potential-partner and go on with the registration process.

> [! IMPORTANT]
>  In case we use the Ash Authentication mechanism for this we need to make sure that the link doesn't time out. And we have to make sure that it can't be used once the registration process is one step further in the process.

## Limiter

We can use this new workflow to add a registration limiter. For the beginning we assume that we don't want more than 200 registrations within one hour. So we look into the User database and count how many new registrations are there in the last hour. If that number is higher than 200 we redirect to http://localhost:4000/my/too-successful after a user clicked on the registration link in the email. That page displays "Hi #{user.name}, we currently have too many new registrations to handle. That is a good problem for us to have but for you it means that you just landed on a waiting list. We'll send you an email once our systems are ready. In case this is a spike we are talking minutes or hours. In case we need to add new server hardware this means days. Thank you for your patients. Viele Grüße Stefan Wintermeyer PS: Do not hesitate to complain by email to stefan@wintermeyer.de The buck stops in my inbox.

The limiter needs to be a function which we can easily adapt. We might use that functionality for hardware upgrade windows too in the future.

> [! IMPORTANT]
>  We need to make sure that power users can not bypass this limiter by trying out other URLs.

We need to add a mechanism to ensure that those waiting list users get an email once we are ready for them with a link.

> [!NOTE]  
> All emails should be written in the lang of the user. 

PS: Please add stuff or ask questions in case I missed something.

**Comment by wintermeyer** [comment]
Please make sure to add text in the README.md which describes how to test this in the dev environment (e.g. how to read the emails and use the ANIMINA application in parallel).

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , I had an issue adding the functionality and I shared my issues on discord , https://discord.com/channels/711271361523351632/955933117573652563/1268889466538561546 , kindly read through the texts , Zach Daniel suggested we remove migrations and snapshots and generate the migrations a fresh and now it works , I just wanted to run this by you before I push in case you have already started having users

**Comment by wintermeyer** [comment]
Go!

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , we will probably have to have this as a seperate issue.
Anonymous users can visit /:username , should we treat users that have signed up but not confirmed as anonymous?
