### ISSUE TITLE
Translation mechanism

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#806]
@MICHAELMUNAVU83 Please have a look into https://github.com/curiosum-dev/kanta to check if this a good way for us to handle translations for non English users. In case it is: Implement it. In case it isn't: Write into the issue why and close it.

Please feel free to add an other language than English and German to the application for you to play with this.

**Comment by MICHAELMUNAVU83** [comment]
Hello @wintermeyer  , I have added this but upon adding migrations I get

```
** (FunctionClauseError) no function clause matching in String.replace/4    
    
    The following arguments were given to String.replace/4:
    
        # 1
        nil
    
        # 2
        "'"
    
        # 3
        "\\'"
    
        # 4
        []
    
    Attempted function clauses (showing 1 out of 1):
    
        def replace(subject, pattern, replacement, options) when is_binary(subject) and (is_binary(replacement) or is_function(replacement, 1)) and is_list(options)
```


Although I am not sure the impact this would add if we still have gettext
