### ISSUE TITLE
Notification Text in Mobile

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#812]
![Screenshot 2024-08-01 at 09 06 44](https://github.com/u@wintermeyer  r-attachments/assets/a08f6257-1351-4bbb-a9c3-ca75013849b4)

@wintermeyer  , on mobile we have this ,should we maintain the text here or is it too much on mobile?

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 I can't see the image.

**Comment by MICHAELMUNAVU83** [comment]
apologies  @wintermeyer  , here it is


![Screenshot 2024-08-15 at 10 44 48](https://github.com/user-attachments/assets/5a1ec5f4-c09c-4040-9ba7-239a88ed3b14)

**Comment by wintermeyer** [comment]
Good thinking!

I just shortened the text in #893:

<img width="336" alt="Bildschirmfoto 2024-08-15 um 10 13 21" src="https://github.com/user-attachments/assets/7af02496-6762-4c82-b104-3ca1ca5d7c79">

But it would be nice if the text could flow around the image. So that we lose even less restate.
