### ISSUE TITLE
Limiter when people get email verification links

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#814]
Limiter
We can use this new workflow to add a registration limiter. For the beginning we assume that we don't want more than 200 registrations within one hour. So we look into the User database and count how many new registrations are there in the last hour. If that number is higher than 200 we redirect to http://localhost:4000/my/too-successful after a user clicked on the registration link in the email. That page displays "Hi #{user.name}, we currently have too many new registrations to handle. That is a good problem for us to have but for you it means that you just landed on a waiting list. We'll send you an email once our systems are ready. In case this is a spike we are talking minutes or hours. In case we need to add new server hardware this means days. Thank you for your patients. Viele Grüße Stefan Wintermeyer PS: Do not hesitate to complain by email to [stefan@wintermeyer.de](mailto:stefan@wintermeyer.de) The buck stops in my inbox.

The limiter needs to be a function which we can easily adapt. We might use that functionality for hardware upgrade windows too in the future.

[! IMPORTANT]
We need to make sure that power users can not bypass this limiter by trying out other URLs.

We need to add a mechanism to ensure that those waiting list users get an email once we are ready for them with a link.

Note

All emails should be written in the lang of the user.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should the emails in the waitlist go out after lets say an hour?

**Comment by wintermeyer** [comment]
I don’t understand your question. Please elaborate.

**Comment by MICHAELMUNAVU83** [comment]
if 210 users register in one hour. 200 get the email right then , what time should the remaining 10 get their email verification links?

**Comment by wintermeyer** [comment]
They get their validation emails right away but their further registration workflow is halted.

**Comment by wintermeyer** [comment]
Probably a waitlisted_at attribute to the User model is a good idea.

**Comment by MICHAELMUNAVU83** [comment]
> They get their validation emails right away but their further registration workflow is halted.

Okay , makes sense , at which point then will they have access to the system? Is is after a certain  amount of time?
What will be the trigger that now allows users in the waitlist to access the system?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer , hello  , could you provide some insight on this

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 We will trigger manually when they'll have access. We "just" need to have a tool which we can trigger manually.

So users will stay on the waiting list until we "un waitlist" them. User by user. That is the point the normal workflow should kick in.

**Comment by MICHAELMUNAVU83** [comment]
Thanks , Let me get to it
