### ISSUE TITLE
Add Info In the Readme about how to access the verification emails 

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#816]
Please make sure to add text in the README.md which describes how to test this in the dev environment (e.g. how to read the emails and use the ANIMINA application in parallel).

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I wanted your advise on this , I started the mailbox server on 4000 and the system on 5000 , I signed up and when I inspect 
```
send_email(
      user.name,
      Ash.CiString.value(user.email),
      subject,
      text_body <>
        "\n#{"https://animina.de/auth/user/confirm_new_user?#{URI.encode_query(confirm: confirm)}"}"
    )
```

I get 
```
{:ok, %{id: "01bd79ff0a8c93434c1f68f00de03c1e"}}
```

But I do not see anything in the mailbox eg 

![Screenshot 2024-08-04 at 09 38 32](https://github.com/user-attachments/assets/afdbb1af-0d7c-4b7d-8622-98999475bf3d)



Is there anything I may be missing?

**Comment by wintermeyer** [comment]
So you start two different Phoenix applications? I guess that is the problem. That email will be in memory only. The 4000 system doesn’t have access to the 5000 memory. 

Please try to find out if one can do both with the same Phoenix application while using a subpath for the email browsing. 

We can’t be the only one with this problem.

**Comment by MICHAELMUNAVU83** [comment]
I have remembered in phoenix apps , we usually have `/dev/mailbox` , in the routes
```
if Application.compile_env(:animina, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AniminaWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
```

and when you just start up the system , messages go here

![Screenshot 2024-08-04 at 10 35 40](https://github.com/user-attachments/assets/fdae2336-0ba4-4415-9b8c-c480ff0cb182)



Not Sure how this would work in production though

**Comment by wintermeyer** [comment]
This should (not) work just fine in production because it should be in the dev section in the route. If it isn’t you should create an issue.

**Comment by wintermeyer** [comment]
Please rewrite the README.md too.
