### ISSUE TITLE
Use Different Email Verification Links for Dev and Prod

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#823]
-  For Development , we want the prefix for the email verification link  to be `localhost:4000` while in production `animina.de` .
- `https://chatgpt.com/share/056c8924-dfbb-4ced-b5cf-096d5f2b2bbd` - context on options Chat GPT Provided
- Also @wintermeyer  , kindly check if the emails are sent out in production with swoosh

**Comment by wintermeyer** [comment]
This is related to https://github.com/animina-dating/animina/pull/821

The main goal is to streamline it and clean the code up. No not needed duplication of information.

**Comment by wintermeyer** [comment]
Yes, but we have bigger fish to fry right now.
