### ISSUE TITLE
config :ash, :pub_sub, debug?: true

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#848]
Do we want to have `debug?: true` in production? I don't care if we do but if we don't, please fix it. Otherwise close the issue.

**Comment by MICHAELMUNAVU83** [comment]
I have removed it in `config.exs` , just to understand how you have set up prod , are you using `dev.exs`?

**Comment by wintermeyer** [comment]
> I have removed it in `config.exs` , just to understand how you have set up prod , are you using `dev.exs`?

I use `dev.exs` for the development environment and `prod.exs` for production.
