### ISSUE TITLE
inputmode="numeric"

### ISSUE THREAD

**Issue by philipp-kempgen** [wintermeyer/animina#87]
I think you missed the `inputmode="numeric"` for the input fields for postal code, height and phone number.
- https://github.com/animina-dating/animina/pull/60/files#diff-3316be0ff6561abc3ef61f59beadb725b9fc7071e4b3e9e5097559ff92bbd039L303
- https://github.com/animina-dating/animina/pull/60/files#diff-3316be0ff6561abc3ef61f59beadb725b9fc7071e4b3e9e5097559ff92bbd039L331
- https://github.com/animina-dating/animina/pull/60/files#diff-3316be0ff6561abc3ef61f59beadb725b9fc7071e4b3e9e5097559ff92bbd039L359

https://caniuse.com/input-inputmode

It shows you a numeric keyboard instead of the text keyboard on a mobile device.

**Comment by wintermeyer** [comment]
Go ahead and fix it please. Thanks! Good catch.
