### ISSUE TITLE
Registration email not going out

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#872]
- @wintermeyer  , I have pulled the changes and restarted the server environement
![Screenshot 2024-08-13 at 18 53 30](https://github.com/user-attachments/assets/02b33a26-42d3-4c5c-a7d4-013056581264)

No email has been sent though , is this something you are currently working on?

**Comment by wintermeyer** [comment]
Are we talking production?

There is. I auto deployment CI yet. I have to trigger deployment manually. It takes some 2-4 minutes. I just did. 

The time of the last commit in a given production version is in the version number on every page.

**Comment by MICHAELMUNAVU83** [comment]
Okay... I'll give this a go again and advise

**Comment by wintermeyer** [comment]
There was a bug in the deployment script. I just fixed it. At least I hope. Deployment is running right now.

**Comment by MICHAELMUNAVU83** [comment]
This works on animina.de , but not on my server , I think we can close this as it works on the most important ENV , we shall come to it later

**Comment by wintermeyer** [comment]
Just a guess: You probably don't have a running `postfix` or `sendmail` on your dev system and there for the `:prod` setup can't send an email. If this is the case you will never be able to send emails locally.
