### ISSUE TITLE
Freak bug where the register form deletes itself and the cursor jumps to the first field

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#90]
I did some GitHub time traveling. This problem was introduced with the commit 
https://github.com/animina-dating/animina/commit/008ffc9d3a8c07811751449711ac45da681dcd08

Here is the original issue with a screencast of the effect:
https://github.com/animina-dating/animina/issues/76

**Comment by wintermeyer** [comment]
I can't find anything in this diff (which is from that time to today):

https://github.com/animina-dating/animina/compare/008ffc9d3a8c07811751449711ac45da681dcd08..ef7ab3499a0d3fca680c8a2f5405496fe7ef805a

**Comment by wintermeyer** [comment]
@philipp-kempgen I need a second pair of eyes to debug this. Please double check if you can a) reproduce the problem and b) if I am right with my finding that the problem didn't exist a couple of days earlier.

**Comment by briankariuki** [comment]
I'll try to reproduce this

**Comment by philipp-kempgen** [comment]
I can't reproduce the problem in Waterfox. That's when Waterfox opens a pop-up dialog asking me if I want to store the password though, right in the middle of filling out the form. Somewhat inconvenient, at least during development, and also unexpected, as you usually get that dialog on submitting the form. Maybe that's just how it is with LiveView?

Can't reproduce the problem in Safari either, so I can't help with `git bisect`ing the problem.

**Comment by philipp-kempgen** [comment]
@wintermeyer Can you reproduce the problem when running `docker-compose build && docker-compose up`?
I don't know how you are doing that now, but I imagine that would be an easy thing to run between iterations of `git bisect`. (Maybe even remove the containers in Docker Desktop, so you start with a fresh database every time.)

**Comment by wintermeyer** [comment]
> Can you reproduce the problem when running `docker-compose build && docker-compose up`?

I don't have Docker installed.

**Comment by philipp-kempgen** [comment]
> I don't have Docker installed.

It's a matter of either `brew install --cask docker` or downloading from <https://docs.docker.com/desktop/install/mac-install/>.

But then again, even if there shouldn't be a problem when using Docker that doesn't mean there isn't a bug that maybe only manifests depending on some timing thing (local network performance?).

I'm pretty clueless.

**Comment by wintermeyer** [comment]
> It's a matter of either `brew install --cask docker`

I don't need it. I don't develop with Docker.

> I'm pretty clueless.

No worries.

**Comment by wintermeyer** [comment]
I haven't seen this one in a while. I'll reopen the issue when needed.
