### ISSUE TITLE
Duplicate Green Flag

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#902]
<img width="383" alt="Bildschirmfoto 2024-08-15 um 18 52 04" src="https://github.com/user-attachments/assets/9878589c-805d-4b08-a5cb-5c0168024868">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , the problem is in `mix seed_demo_system` and not in how we count and filter interseting flags , this is a random user from a new reset and seed

```
 flags = UserFlags.by_user_id!(user.id) |> Enum.filter(fn x -> x.color == :green end) |> Enum.map(fn x -> %{id: x.id , name: x.flag.name} end)

[
  %{id: "bbc06f94-850b-4e0a-bb80-ebd42cb2dad6", name: #Ash.CiString<"Modesty">},
  %{id: "0ccf5b70-b1fa-46dc-a09b-a749b3235ee7", name: #Ash.CiString<"Modesty">},
  %{
    id: "e313f40f-f3e2-452d-99bc-445b9d6ced0e",
    name: #Ash.CiString<"Sense of Justice">
  },
  %{
    id: "ca48f20e-88aa-4a2b-a041-beaf66e2fde2",
    name: #Ash.CiString<"Sense of Justice">
  },
  %{id: "df0362bd-f6b9-43a9-84cf-0b989a1d788c", name: #Ash.CiString<"Modesty">},
  %{
    id: "c676bd0b-fff3-4c5a-a764-75bc001d35e2",
    name: #Ash.CiString<"Sense of Justice">
  },
  %{
    id: "e330642c-2a69-4aca-af17-775df5c36d77",
    name: #Ash.CiString<"Sense of Justice">
  },
  %{id: "7bcdcdb2-9740-458b-a754-a2ab0dd27eed", name: #Ash.CiString<"Modesty">}
]

```

You can see here we have double of each user flag

Let me have a  look at that mix task , if I get lost I will let you know as you have interacted with that file more

**Comment by wintermeyer** [comment]
Shouldn’t the validation kick in here?

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 But don't invest too much time into this right now. It is not worth it. We have bigger fish to fry till the conference.

**Comment by MICHAELMUNAVU83** [comment]
Okay , for new users this feature should work properly , We can move this to a different milestone.


The validation does not kick in as we do not pass an actor probably
