### ISSUE TITLE
Flag real estate on mobile

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#905]
<img width="383" alt="Bildschirmfoto 2024-08-15 um 19 12 47" src="https://github.com/user-attachments/assets/398286d9-53f4-44aa-bb7d-9ee71201ee6f">

There shouldn't be a "new line" between the point "flag" and the first real flag. We can not waste the real estate on mobile devises.

**Comment by MICHAELMUNAVU83** [comment]
![Screenshot 2024-08-16 at 15 27 14](https://github.com/user-attachments/assets/8a362726-3b21-4ce2-b207-48da6645a502)

Seems like it is a `flex-wrap` that we have , on some screens it wraps well as such , is this the case on your side for every user?

**Comment by wintermeyer** [comment]
If this is an edge case I’ll close the issue.
