### ISSUE TITLE
Chat: Generating the messages like ChatGPT

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#906]
Right now we wait till Llama3.1 is finished with the answer until we display the messages. And this takes a lot of time. So much that some people will move on because they think the system is broken.

Is there a chance that we display the messages as they are generated? Word by word?

Please move it to a later milestone in case this is a lot of work.

**Comment by MICHAELMUNAVU83** [comment]
I'll have a look at this , have you tested to see if it works though?

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 It works like a charm! I am very happy! This is a very useful feature for so many people.

**Comment by MICHAELMUNAVU83** [comment]
Amazing, adding AI engineer to my resume 😂😂

**Comment by MICHAELMUNAVU83** [comment]
I will move this to a later milestone , AFAIK  , we are waiting for an API Reponse which comes at once , down the road we can do more research on how to have it like GPT

**Comment by wintermeyer** [comment]
https://hexdocs.pm/ollama/Ollama.html#module-streaming

**Comment by Kimutai01** [comment]
I have found a way to do this,
Working on it
<img width="1440" alt="Screenshot 2024-08-20 at 10 43 01" src="https://github.com/user-attachments/assets/15bf5a67-d371-44cd-a094-6b15e34a21f1">

**Comment by Kimutai01** [comment]
But I think we will have to generate only 1 message

**Comment by wintermeyer** [comment]
> But I think we will have to generate only 1 message

What do you mean by that?

**Comment by Kimutai01** [comment]
What I meant was generating one message but I've found a way to have the three messages
