### ISSUE TITLE
See who liked you

### ISSUE THREAD

**Issue by paintdog** [wintermeyer/animina#918]
I want to see who liked me. At the moment I can only see whom I liked. Not usefull.

**Comment by wintermeyer** [comment]
> I want to see who liked me. At the moment I can only see whom I liked. Not usefull.

Right now I consider not having this functionality a feature and not a bug. But I might reconsider this in the future. This is much trickier than one would expect.

**Comment by wintermeyer** [comment]
To everyone who is reading this issue: Please do upvote it in case you agree with @paintdog
