### ISSUE TITLE
Everything should be a clickable tag.

### ISSUE THREAD

**Issue by paintdog** [wintermeyer/animina#919]
It would be great if you could click on 'nearly' everything to get profiles with the same tags. It would be great if you could combine several tags to filter profiles, for example: Click on profiles from Bonn and than profiles from Bonn who like hip-hop.

**Comment by wintermeyer** [comment]
We want to avoid Online Dating Fatigue which results by crawling through too many profiles on a single day. So the system will provide potential candidates. A classic search would be counter productive.

I will write a blog post about this in the near future at https://animina.de/wintermeyer
