### ISSUE TITLE
Chat functionality

### ISSUE THREAD

**Issue by paintdog** [wintermeyer/animina#920]
A Chat by city or region would be nice to meet people by chat or to organize group events with several people. This could help to make new friends and to get to know each other easily.

**Comment by wintermeyer** [comment]
That is a very good idea! Let me think about this. We have some other things to do first but I really like the idea of this.

**Comment by wintermeyer** [comment]
I'll close this issue for now. It is more complex than initially thought. If we offer such a chat room we have to have some sort of policing mechanism for that. That is out of scope right now.
