### ISSUE TITLE
Could Interest You: Clickable area is much smaller than the visual button

### ISSUE THREAD

**Issue by jaller94** [wintermeyer/animina#921]
## Expected
This is the visible area that will change the cursor and change its background colour on hover.
![2024-08-19_21-02](https://github.com/user-attachments/assets/3a71f307-954a-4de6-987d-daa5f99e200d)

## Actual
This is the clickable area which will navigate to the profile.
![2024-08-19_21-03](https://github.com/user-attachments/assets/424bc5f8-56b0-4495-a950-8f217ae9b191)

## Other issues
* For accessibility `<button>` shouldn't be used. It's all a link `<a>` (because it navigates). It may still look like a button if that's what the designer prefers.

**Comment by wintermeyer** [comment]
Good catch! Thank you!
