### ISSUE TITLE
Could Interest You should only have users who are normal or validated .

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#925]
On Production , I visited [animina.de/leo](https://animina.de/leo) , which is a public account but I get 
![Screenshot 2024-08-20 at 08 09 15](https://github.com/user-attachments/assets/93b6f191-a23d-4681-9ed6-db2f2c39d872)

which probably means they are do not have a status of normal or validated , @wintermeyer  , could you confirm if this is the case?

**Comment by wintermeyer** [comment]
The state of this user is "hibernate" on production.
