### ISSUE TITLE
A profile without a single story shouldn't be active

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#933]
I saw a profile which doesn't have a story. That shouldn't be possible. At least that profile shouldn't be listed and available for others to see in the system.

**Comment by MICHAELMUNAVU83** [comment]
What should we display when someone visits this page?

**Comment by wintermeyer** [comment]
> What should we display when someone visits this page?

The 404 message that this account doesn't exist. And we have to make sure that the profile's owner understand that he/she has to create a story.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , should we list users with no story on could interest you?

**Comment by wintermeyer** [comment]
NO! Think of those profiles as not existing yet. They are not finished.

**Comment by wintermeyer** [comment]
I think it would be best to establish some sort of state or a boolean which gets set to true once all is good. Then we can easily filter it with SQL and don't have to walk through all the rules every time.

**Comment by MICHAELMUNAVU83** [comment]
Yeah , I will set this up as a seperate issue
