### ISSUE TITLE
Add AI assistance to write better stories

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#934]
https://animina.de/my/stories/new and the edit page of a story look like this:

<img width="1533" alt="Bildschirmfoto 2024-08-20 um 21 01 05" src="https://github.com/user-attachments/assets/cf9b02a5-9ab0-4fb6-811d-aeb49704de58">

A lot of users are not born story tellers and they might have language problems. We should offer them help.

I'd like to add the following functionalities:
- `Correct any spelling, grammar, and punctuation errors.`
- `Improve the story to be funnier.`
- `Improve the story to be more exciting.`
- `Lengthen the story.`
- `Shorten the story.`

Use AI to do it. Feed the original story into the AI and return the output in the input field. We right the prompt in English but we tell the AI to use the language the story was written in.

**Comment by wintermeyer** [comment]
There should be a minimum length before the user can use this functionality (e.g. a minimum of 50 characters). Before that the button or link for that functionality is visible but disabled.

**Comment by Kimutai01** [comment]
should  this be on the content alone or also the header

**Comment by wintermeyer** [comment]
Only content. The header is fixed. But should be fed into the AI for context.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer should we have different button options for Lengthen the story, 
Shorten the story etc?

**Comment by Kimutai01** [comment]
@wintermeyer another question
After someone uses the AI can they use it again
Does it deduct points?

**Comment by wintermeyer** [comment]
> @wintermeyer another question After someone uses the AI can they use it again Does it deduct points?

It does not deduct points (an exemption). 

I don’t know about the GUI. Fire at will. Please make sure that it is usable on mobile and desktop.

**Comment by wintermeyer** [comment]
They can use it again.

**Comment by wintermeyer** [comment]
Let us feed the AI not just with this story but with other existing stories of that user too and with all the white flags. So that the AI can generate a better and more natural sounding text. @wintermeyer will take care of the prompt fine-tuning later.

**Comment by Kimutai01** [comment]
Okay I'll update it to take the previous stories
This feature is almost done, 
I'm doing the streaming then I'll create a pr
