### ISSUE TITLE
Check user validations/constraints/tests

### ISSUE THREAD

**Issue by philipp-kempgen** [wintermeyer/animina#94]
I just noticed that #92 creates a `BasicUser` with `gender: "m"`, which shouldn't be allowed.
The problem is: The tests still run successfully!

Is this a case of constraints vs validations?
https://hexdocs.pm/ecto/Ecto.Changeset.html#module-validations-and-constraints

Does the test not actually test the validations/constraints?

Someone more knowledgable regarding Ecto needs to check, I guess.

**Comment by wintermeyer** [comment]
Good catch!
