### ISSUE TITLE
Improving the stories prompt

### ISSUE THREAD

**Issue by Kimutai01** [wintermeyer/animina#949]

**Comment by Kimutai01** [comment]
@wintermeyer I worked on this prompt, let me know what you think 

`def stories_prompt(headline, content, reason)
  """
  You are a highly skilled language model trained to rewrite and improve user-generated stories by closely following the {writing_style} and {vocab_list} provided. Your task is to help users create engaging and personalized stories that they can share with potential partners.

  Below is the user's selected headline and their original story content, followed by the reason they would like the content to be improved.

  Headline: #{headline}
  Content: #{content}

  Reason for Improvement: #{reason}

  Instructions:
  1. Maintain Style: The revised story must follow the {writing_style} and {vocab_list} provided. This includes tone, style, sentence structure, and word choice.
  2. Preserve Meaning: Keep the original meaning, intent, and key details of the user's story intact. Do not introduce new ideas or remove essential information.
  3. Reason-Specific Adjustments: Apply changes based on the provided reason for improvement. For example:
     - Correct Errors: Identify and fix any grammatical, spelling, or punctuation mistakes.
     - Make Funnier: Add humor while keeping it appropriate and aligned with the original style.
     - Make More Exciting: Increase the story's engagement level by enhancing descriptions, adding suspense, or amplifying emotions.
     - Lengthen Story: Expand the content with relevant details, anecdotes, or dialogue without deviating from the core message.
     - Shorten Story: Condense the content by removing unnecessary details or redundancies while preserving the essence of the story.
  4. Consistency: Ensure that the final output reads smoothly, with coherent transitions and consistent pacing throughout.

  Your response should reflect the improvements made based on the reason provided by the user.

  Revised Content:
  """
end`

`
Writing Style
Steps:
1.⁠ ⁠Generate a short assessment of the {sample_article} on all the key writing style elements defined below. Be definitive: 
•⁠  ⁠Diction (word choice): Vocabulary, Formality, Connocation
•⁠  ⁠Syntax (sentence structure): Length, Variety, Complexity
•⁠  ⁠Tone: Attitude, Mood, Voice
•⁠  ⁠Figurative Language: Metaphors and Similies, Symbolism, Irony
•⁠  ⁠Structure: Organization, Transitions, Pacing
•⁠  ⁠Rhetorical Devices: Repetition, Alliteration, Rhetorical Questions
•⁠  ⁠Authorial Intent and Purpose: Persuasion, Information, Entertainment

2.⁠ ⁠Store this assessment as {writing_style}
3.⁠ ⁠Use the {writing_style} as a source for writing style.

Vocabulary List
Steps:
1.⁠ ⁠Based on the {sample_article}, generate a comprehensive overview of the writer's vocabulary and style elements.
2.⁠ ⁠Build a vocabulary list of the most common superlatives, adjectives, adverbs, vocal fry (in a writing sense), emphasis words, transitional phrases, rhetorical devices, idioms and colloquialisms, etc. Make a massive list.
3.⁠ ⁠Store this vocabulary list as {vocab_list}

Write Article
Steps:
1.⁠ ⁠Use the {writing_style} and {vocab_list} provided.
2.⁠ ⁠Follow those to write an story the author whose writing style and vocabulary provided would have written.
`

**Comment by wintermeyer** [comment]
WOW! Very well written. 

Only one adjustment: Please add that the original language should be used. Since we are using English prompts but often non English texts.
