### ISSUE TITLE
Run flag seeding as a migration

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#95]

**Comment by philipp-kempgen** [comment]
> I'll create a migration to run the seeds: #95

A migration was my first thought too.
But some people oppose running seeds in migrations:
https://elixirforum.com/t/seeds-as-migrations/20490/4
Really depends on what kind of seeds are added.
I.e. is this example data or an integral part of the system. Not sure.

**Comment by wintermeyer** [comment]
https://github.com/animina-dating/animina/commit/c026eda8823169b569a150354cd735f8ba10fdb8
