### ISSUE TITLE
No need with your first message when answering a message

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#952]
The help with an initial message should only be offered for the very first initial message. Not for the answer.

<img width="1148" alt="Bildschirmfoto 2024-08-22 um 17 43 31" src="https://github.com/user-attachments/assets/a6f3f21b-703d-4d2d-819e-4bbc7af50acf">

**Comment by MICHAELMUNAVU83** [comment]
So only one person between the user and receiver can use the AI Chat then?

**Comment by wintermeyer** [comment]
> So only one person between the user and receiver can use the AI Chat then?

Yes, only the very first message can get assistance. It is just a little help at the beginning.
