### ISSUE TITLE
Make indicator for new chat message clickable

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#953]
The indicator that there is a new chat message should be clickable and lead to that chat (if it is one) or to an overview (if it is from multiple people).

<img width="312" alt="Bildschirmfoto 2024-08-22 um 17 45 51" src="https://github.com/user-attachments/assets/6d78061b-f8aa-4fee-b4ea-edecc4343474">

**Comment by Kimutai01** [comment]
@wintermeyer should there be a different page for the notifications?

**Comment by wintermeyer** [comment]
AFAIK the link doesn't do anything right now. It should lead to the chat.

**Comment by wintermeyer** [comment]
Always ask yourself: What would I expect this to do?

**Comment by Kimutai01** [comment]
@wintermeyer 
I'm currently working on this and I want to group messages based on the sender_id and receiver_id. But I'm not able to find the group by function. How can I go about that?

**Comment by wintermeyer** [comment]
> How can I go about that?

Problem solving steps:

1. Ask @MICHAELMUNAVU83 
2. Ask the Ash group (I guess this is an Ash problem) in https://elixirforum.com but give them enough information so that they can answer the question.
3. Ask me

**Comment by Kimutai01** [comment]
@wintermeyer 
This is what I want to achieve, I want to write a query that can group the messages based on the sender_id and receiver_id

**Comment by wintermeyer** [comment]
> @wintermeyer This is what I want to achieve, I want to write a query that can group the messages based on the sender_id and receiver_id

Go to https://elixirforum.com/ and post the question there. Give an example.

PS: With a bit of luck this question can be answered by ChatGPT.

**Comment by Kimutai01** [comment]
@wintermeyer 
What's your opinion on this design
<img width="1440" alt="Screenshot 2024-10-07 at 16 56 07" src="https://github.com/user-attachments/assets/35f1a7fc-42c0-4ff2-86b7-a60c85298860">

Also, I'm just displaying the unread messages on this page.

**Comment by wintermeyer** [comment]
> What's your opinion on this design

The messages should have a timestamp and we can display two columns on the desktop view.
