### ISSUE TITLE
registration should accept zip codes following scheme "123-4567"

### ISSUE THREAD

**Issue by christianhorn** [wintermeyer/animina#962]
Trying to register with a zip code following scheme "123-4567", which is common in Japan, this error message is output:

"Zip code must have 5 digits"

**Comment by wintermeyer** [comment]
Right now we only support Germany. But I just created #963 to cover this problem in the future. Thank you for your input!

**Comment by wintermeyer** [comment]
Everybody who wants other countries: Please do upvote this issue. That is a good signal for us. Thank you!
