### ISSUE TITLE
Profiles without a single photo

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#969]
How is it possible that I can see the https://animina.de/juli profile but that it doesn't contain a single photo?

Is this a bug in our validation or is that a bug in my thinking?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , I  doubt if Julia has any photo , could you check in the DB

**Comment by wintermeyer** [comment]
> @wintermeyer , I doubt if Julia has any photo , 

I assume so too. But how can that be. She should have a minimum of two photos (avatar and about me). Which means that we have a buggy validation which needs to be fixed.

> could you check in the DB

Please give me the Elixir code which I can use to check this in the iex. So that other developers can follow us along the ride.

**Comment by MICHAELMUNAVU83** [comment]
It is not mandatory to have the avatar , and she was in the DB when we did the update of setting the `registration_complete_at` value to the 22nd August if you remember

**Comment by wintermeyer** [comment]
> It is not mandatory to have the avatar

That is a bug:
https://github.com/animina-dating/animina/issues/972

I remember the `registration_complete_at` thing. But we need to make sure that in the future an "About me" photo is mandatory too. https://github.com/animina-dating/animina/issues/973

Maybe this is my fault. I don't remember.
