### ISSUE TITLE
avatar is mandatory

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#972]
Please add validations to make this happen. No account without an avatar.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , when you say no account if no avatar , do you mean the user is not added to the database at all or the  `registration_completed_at` field is not nil.

If it is the first scenario, we would have to have the interface for uploading a photo on `/` together with fields like name etc

**Comment by wintermeyer** [comment]
I meant no NEW account.

**Comment by MICHAELMUNAVU83** [comment]
are you comfortable in that case then with having the upload photo UI here 
![Screenshot 2024-08-27 at 17 41 24](https://github.com/user-attachments/assets/7ca56ee2-cc5c-420e-865b-fd26432f33c4)


and if so , where exactly should we have it

**Comment by wintermeyer** [comment]
I don’t like to have the avatar upload functionality there. 

I think I miscommunicated: Of course we can have a ‘User’ without an avatar in the DB but that user wouldn’t be active. I forgot the state we use to handle this.

**Comment by MICHAELMUNAVU83** [comment]
Aah , this makes sense, we will also have to communicate that to them when they are viewing their profile , that they need to add an avatar .

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , hello , I have a questions

1 . Would you want us to ensure you cannot delete your profile photo at all , or can we let guys do that , but they know their profile wil be inactove , also if it is this way , should we communicate this on the profile photo page as such a way
"For your profile to be active , kindly upload your profile photo" . We should probably have this too when a user is viewing their profile and they have not added an avatar.

**Comment by wintermeyer** [comment]
> Would you want us to ensure you cannot delete your profile photo at all

You can not delete the avatar. But you can replace it with a new one. I do not want any profiles without an avatar.

> We should probably have this too when a user is viewing their profile and they have not added an avatar.

Yes, we should. But on the other hand this shouldn't happen in the future anyway. That's what validations are for. But add it. It can't harm.

**Comment by MICHAELMUNAVU83** [comment]
> You can not delete the avatar. But you can replace it with a new one. I do not want any profiles without an avatar.

Aah Interesting , currently , we have to delete the current photo when uploading the new one , I can make sure deletions do not work on the GUI and in another issue figure out how to do it from the resource
