### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#991]
<img width="1562" alt="Bildschirmfoto 2024-08-30 um 13 51 07" src="https://github.com/user-attachments/assets/c2d4878e-b6f2-475c-b6fe-9901cad1d7ff">

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , we have an overflow here if the users are too big /many for that space. Option would be to reduce the size of the image and text , would you want this?

**Comment by wintermeyer** [comment]
Warning: I have very little understanding of CSS. So please don't hesitate to describe it to me like I am 5 years old.

> Option would be to reduce the size of the image and text , would you want this?

No, definitely not. Why is that space limited anyway? Can't we just use all the vertical space?

**Comment by MICHAELMUNAVU83** [comment]
Aaah , my bad  , I have managed to fix it , sending a PR for it asap

![Screenshot 2024-09-01 at 12 15 27](https://github.com/user-attachments/assets/22c70fc2-0852-455f-89ba-23f68cec3999)
