### ISSUE TITLE
use international date format yyyy-mm-dd (RFC-3339)

### ISSUE THREAD

**Issue by jonasstein** [wintermeyer/animina#992]
The website uses the date format mm/dd/yyyy for the `Date of birth:` field
Please use RFC-3339 yyyy-mm-dd
See also https://wiki.gentoo.org/wiki/Systemwide_RFC-3339_Dateformat

**Comment by wintermeyer** [comment]
Can you do me a favour and add the used OS, Browser and maybe a screenshot?

Here is what I see with Safari on macOS:

<img width="265" alt="Bildschirmfoto 2024-09-01 um 08 09 45" src="https://github.com/user-attachments/assets/96ba60bc-aa31-4edb-83c4-8390491f2b20">

**Comment by wintermeyer** [comment]
Since I got no response from @jonasstein about this I close this issue. Can be reopened any time.
