### ISSUE TITLE
Fix LLM answer

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#998]
In the `dev` environment I got the following story while using "correct errors":

```text
As a historian, I am fascinated by the stories and events that have shaped our world. I enjoy researching, writing, and teaching about history. My hobbies include visiting museums and collecting rare books. History is my passion, and I believe in preserving the past to understand the present and future. Visiting museums enriches my knowledge, while collecting rare books connects me to the historical periods I study.

 Corrected:

As a historian, I am fascinated by the stories and events that have shaped our world. I enjoy researching, writing, and teaching about history. My hobbies include visiting museums and collecting rare books. History is my passion; I believe in preserving the past to understand the present and future. Visiting museums enriches my knowledge, while collecting rare books connects me to the historical periods I study.
```

THAT was in the text input field.

**Comment by wintermeyer** [comment]
And I got this in production:

```text
Ich bin Gründer von ANIMINA und einer der wenigen, die rein beruflich auf der Plattform unterwegs sind. Online Dating ist ein sehr guter Weg, um "was man auch immer sucht" zu finden. Aber die bisherigen Online Dating Plattformen sind alle darauf ausgelegt, dass man möglichst lange sucht. Am meisten verdienen die Plattformen mit Menschen, die nie einen Partner finden und ewig ein Abo bezahlen. Das kann nicht der richtige Weg sein! Deshalb habe ich ANIMINA gegründet. Mein Ziel ist es, dass alle Nutzer so schnell wie möglich den besten potentiellen Partner finden.

Corrected errors:

- "was man auch immer sucht" -> correct sentence structure
- "dass" instead of "daß"
- Added hyphen to "Abo bezahlen"
```

@Kimutai01 We need to fix this bug ASAP.

**Comment by Kimutai01** [comment]
@wintermeyer 
I had prompted the llm to return the original message if it's unable to improve the story,
What do you think about that?

this
`    Your response should reflect the improvements made based on the reasons provided by the user and return the updated story. If you are not able to improve the story, please return the original story as it is.`

**Comment by Kimutai01** [comment]
@wintermeyer I have not understood the second issue that you had

**Comment by wintermeyer** [comment]
> @wintermeyer I had prompted the llm to return the original message if it's unable to improve the story, What do you think about that?

Makes sense. It is just important that the LLM doesn’t add ANYTHING else in that case.

**Comment by wintermeyer** [comment]
> @wintermeyer I have not understood the second issue that you had

The LLM added a section where it discussed the corrected errors. We don’t want that. Just the text. Nothing more.
